### ISSUE TITLE
Weird behavior of menus (probably a 4k issue)

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1007]
I'm experiencing troubles with the menus in the latest beta release (0.19.3.17733). When more than one menu window is open, one of them turns completely black. See attached screenshot:
![stellarium-028](https://user-images.githubusercontent.com/37028368/77236286-74282380-6bbd-11ea-91c0-c40f5b4dc52a.png)

Also, when scrolling through e.g. HiPS, the menu looks really weird. See attached screenshot:
![stellarium-029](https://user-images.githubusercontent.com/37028368/77236354-134d1b00-6bbe-11ea-9532-65a505b06586.png)

This seems to be an error experienced on 4k screens, as this is solved by running Stellarium with scaling.

OS: Windows 10 64 bit
Graphics card: RX 5700 XT (with latest driver)
Running on a 4k screen (of course)

**Bonus**: Huh, appearantly, the screenshots are messed up too. The menu windows were centered and a lot bigger when I saved the screenshots!

**Comment by henrysky** [comment]
@alex-w I am looking into this issue as well besides #763 and removing this line in ``scr/gui/StelDialog.cpp`` seems to have fixed the issue

```c
proxy->setCacheMode(QGraphicsItem::ItemCoordinateCache);
```

The line has already been disabled on MacOS due to this bug #393 coincidentally reported by me almost 6 years ago

Deleting that line also seems to have fixed the issue scrolling issue (the last two images in the bug report) reported in #830

**Comment by alex-w** [comment]
Please check version 0.20.2.18210

**Comment by alex-w** [comment]
Please check the latest beta

**Comment by henrysky** [comment]
I have checked 0.20.2.18227 and the problem is fixed.

**Comment by alex-w** [comment]
Thanks!
