### ISSUE TITLE
Remember last entered objects

### ISSUE THREAD

**Issue by Astrotourist-info** [Stellarium/stellarium#1050]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to enter and reenter next night some objects with long names. Ex. NGC 6946, NGC 2685, NGC 2403 - it is easy to make a mistake in the name especially deep at night.

**Describe the solution you'd like**
I want that Stellarium remember last 10-20 entered objects in the search field F3.

**Comment by dimitri-rebrikov** [comment]
Hello @Astrotourist-info ,
i think the existing bookmark functionality fits exactly you needs.
To bookmark an object:
1. Find and select the object,
2. Press Alt+B to open the bookmark dialog,
3. Press "Add bookmark".

In your next Stellarium session you can then:
1. Press Alt+B to show the bookmark dialog,
2. Navigate to the bookmarked object by the double click on the corresponging bookmark entry.
There are even more convenience functions like visualising all bookmarked object, export/import bookmarks.

**Comment by chithihuynh** [comment]
Hi @alex-w 

I want to pick up this project but I wanted to change the search format before I did it.

My goal is to display only one object per line (instead of all search on one line) like so:

![searchObjectList](https://user-images.githubusercontent.com/35203957/86426401-d60c2500-bca4-11ea-8f38-cc85f1fdf657.png)

Would that be OK? If so, should I submit a new issue or just fix it on this one?

**Comment by alex-w** [comment]
But for what? Why you do not want to see a list with comma delimiter (the list is compact) and why header of window at bottom side?

**Comment by chithihuynh** [comment]
Header was a mistake, I was playing around with the settings. That part isn't changing.

Currently, we use the up and down arrow to move from one selection to another but with a comma delimiter, it seems like we should be using the left and right arrow instead. That's why I thought it would be more intuitive to have it list out per line.
