### ISSUE TITLE
local hour angle

### ISSUE THREAD

**Issue by johnbellora** [Stellarium/stellarium#1058]
1.) When highlighting a star, all the information pops up on the left. Can you add local hour angle just below the Transit calculation?  I thought I saw that on a very old version. It is quite important to me for many reasons. It is how I determine celestial navigation figures.

2.) Please add an option to where when clicking a button, the program places the operator randomly somewhere in the world and in is up to the user to practice celestial navigation skills to determine location. Once determined another button reveals true longitude & latitude.
The program will then become quite popular among a new genre of client all over the world and the addition is minor but fantastic.

John Bellora
858-776-2189

**Comment by axd1967** [comment]
Hello @johnbellora have you tried the Navigational Stars plugin? It provides LHA for navigational stars when you enable it and show the nav stars.

![image](https://user-images.githubusercontent.com/3529789/79839841-64b31a80-83b5-11ea-8666-48bfca85350c.png)

About the random location: you could do following:
* open the location dialog (F6) and just click somewhere. you could also make that dialog smaller before clicking. it is already challenging to find the exact spot, and usually a navigator already has a very rough idea of where (s)he is, but it must be possible to get a rough idea of where one is on the globe by looking at the stars.

But maybe the location dialog could provide a button and a keyboard shortcut to trigger a random location jump.

* you could ask someone else to choose a location for you, by using the Remote Control (browser) plugin, and let someone choose a location via their browser.

**Comment by alex-w** [comment]
Second proposal may be solved by script also.

**Comment by gzotti** [comment]
The local hour angle has been in the display for ages. We just don't call it "Local". Info line HA/Dec.

**Comment by johnbellora** [comment]
Hello Alex,
It is quite the honor to chat with you. The news is great about the LHA. I will check it out tonight. I must tell that Stellar navigation is quite different and quite accurate, developed for simplicity but the accuracy is near perfect but limited by my crude measuring device limits me to a +/- 0.1 degree which is close enough for emergency situations. Once i develop a more accurate magnified  optical divece i expect the accuracy to close approach reality. I was given an appointment with the celestial navigation instructor at the Naval academy to give a demonstration. He told me in all his years of Celestial Navigation, He had never heard of someone being able to tell longitude by making one star angle measurement without the use of the horizon.  It is not an approximation. The Celestial Navigation instructor Gavin Lowe contacted his counterpart in the Royal Navy and wanted him to see what I have. That is pending because he is in England. The US Coast Guard seemed quite enthusiastic and quite surprised at the demonstration and asked me to give a detailed course to three head instructors with the thought of using this as a back up. The Naval guy said he will wait to see the Coast Guard assessment. Currently the Patent is for the method and the manual astronomical device. But the patent covers an electronic version as well. This is where I was hoping you may come is. The Coast Guard instructors want to see the electronic version where you make a manual measurement and plug into the program. An app for a cell phone where GPS is down. I had a chat with a scientist with Lina Space who actually owns some working cubesats currently operating in space supplying the information the the website Marinetraffic.com. His comment was that NASA might already be using a similar method. But nothing came up in the patent search and the patent was awarded.

 If you give me a watch set to UTC with no measuring instruments I can tell you my location in longitude routinely with +/- 7 degrees just by eyeball anywhere on earth by visualizing the anges I see in the stars and comparing to the UTC. I know of no one who can do such a thing.  When i use measuring instruments without magnification ,+/- 0.1 % is routine clearly adequate for sea and air emergency navigation. I practice this all the time with the Aciqra planetarium program with the random feature enabled. It was developed for GPS deficient environments. It is quite fun, challenging and rewarding.
Since Aciqra program does this so I am set but the author is to busy to modify any further to add a few features that would allow me to verify actual empirical measurements results so the Coast Guard can use the random feature and use the screen. I am using your program but Coordinates are displayed and i have to choose the city anyway so it is not quite as adventurous but adequate.
Best regards
John Bellora

-----Original Message-----

**Comment by johnbellora** [comment]
Hello Alex, I just t


-----Original Message-----

**Comment by johnbellora** [comment]
Hello Alex,
I just tried the Navigational stars plug-in.Actually i had already tried that and it was installed but the LHA does not appear. I am using version 0.19.3. I am sure i am doing something wrong. I have all available information loaded. Help! By the way for some reason version 0.20.0 does not run. Every previous version rums. I downloaded the 32 bit Win version 0.20.0. I have windows 7. Please see attached
John


-----Original Message-----

**Comment by alex-w** [comment]
Couple days ago we released version 0.20.1 - please check it.

**Comment by johnbellora** [comment]
Thank you, I do have a win 10 laptop 64 bit but I have not tried the new version as of yet on that laptop because all the engineering software I have written over the years will not run on the win 10 OS so i am milking my win & 32 bit until it dies. This program is very impressive. I was told by one of the developers that the LHA is the same as the HA but the figures don't seem to match up. I am sure I write a spaghetti code program to convert transit time to LHA but I would rather it be displayed in the program. The screen shot you sent me shows LHA. Is that an older version? 


John

-----Original Message-----

**Comment by alex-w** [comment]
Just convert HMS into DM or DM into HMS and compare it

**Comment by johnbellora** [comment]
This is fantastic display you sent which also shows longitude and latitude. How do i get my screen to read like this? By the way a certainly want to send a donation. Best way to do that?
John


-----Original Message-----

**Comment by alex-w** [comment]
Two Alex here :)

Please play with settings of Navigational Stars plugin ;)

**Comment by gzotti** [comment]
These new data came in 0.20.0 which does not run if you have not installed proper GPU drivers (ANGLE mode broken), which is why we released 0.20.1. 

The hour angle in astronomy is counted in hours. LHA is counted in degrees. Multiply the first by 15 to get the other. This is just a convention. 

The principle of cel.nav. as I know it is measuring star altitudes at a certain time. One measurement yields a "small circle" on Earth where you are located. A second measurement gives another circle. You must be located at one of their intersections. If one of those is not on water, your ship is on the other. A third measurement will yield another circle. In the perfect case, the three circles have one common intersection point. More often, there is a place where the circles "almost" intersect, caused by measurement errors. The aim is to make this triangle as small as possible. A measurement error of 1 arcminute will shift the corresponding circle by 1 nautical mile. Positioning with ~1NM accuracy allows then visible contact to land or other ships.

If you are measuring only a single star, you may also have to know your latitude and approximate position. Then intersection of your circle with the latitude circle will yield one of 2 possible positions. If you can rule out one, you have your position.

You can get a good feeling of sidereal time by e.g. observing the position of Cassiopeia and/or one of the Dippers in relation to the pole. (In the south, use other stars of course, e.g. Crux and &alpha;/&beta; Cen.) Together with date this yields local mean solar time. This is the principle of medieval nocturnals (star clocks), but with a little training you will not need such device. 
Polar altitude yields latitude of course. This method is far older than the idea of patents, and I fathom most experienced amateur astronomers (at least of the pre-GOTO generation) can do that. Difference to the UT clock then gives the longitude, this was the big issue from times of Gemma Frisius to Harrington. 

This may however hardly be enough for successful S&R missions. One NM per arcminute of error! A 7° squared field is quite some area to search for a tiny lifeboat. Your 0.1° seems already much better.

If you are making a "star angle measurement without horizon", does that imply comparison of altitudes of two stars (basically Nocturnal principle)? Or what angles do you measure?

**Comment by alex-w** [comment]
Hmm... LHA already showing in the data (as HA in HMS format and as LHA in DM/DD formats when NavStars plugin are enabled); the script to jump observer into random location is added also in the master (shortcut: Ctrl+D, L).

**Comment by alex-w** [comment]
Please check version 0.20.3-50e9bca0fd: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by alex-w** [comment]
@johnbellora did you tested the changes in Stellarium?

**Comment by johnbellora** [comment]
- Added script with shortcut, which add ability to jump to random location for celestial navigation game and practice (GH: #1345, #1058)
Can you send me some instructions on how to use this for dummies? ( Like me)
   
   - Added ability to toggle to using decimal degrees for various navigational data through follow the option "Use decimal degrees" in the main GUI (GH: #1344)
This is awesome.
John
Just contributed! Thank you for an amazing product as well as amazing support!
-----Original Message-----

**Comment by alex-w** [comment]
> Can you send me some instructions on how to use this for dummies? ( Like me)

Please try shortcut: Ctrl+D, L

You may change it or add new one in Shortcuts Editor (F7)

**Comment by johnbellora** [comment]
Please send me the link you before with the new changes you made for me. the decimal option for LHA and other navigational data as well as the random location option. I was not able to get that to work by the way. I am on a different computer not and that is why i am asking for the link. Having a hard time locating that link.
Best Regards
John Bellora
-----Original Message-----

**Comment by axd1967** [comment]
> Please send me the link you before with the new changes you made for me. the decimal option for LHA and other navigational data as well as the random location option. I was not able to get that to work by the way. 

@johnbellora 

to find the latest development executables go to https://github.com/Stellarium/stellarium-data/releases (it is a separate GitHub repository). under "Weekly snapshot", find "Assets", there you will find the executables.

to find the official releases (which don't contain your changes yet), go to https://github.com/Stellarium/stellarium and look for "Releases".
