### ISSUE TITLE
More ephemeris steps possibilities in AstroCalc

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1176]
I would like to have more steps in the ephemeris tool in AstroCalc. Currently, we are locked with 1, 5, 10, 15, 30, 60, 100 and 500 steps of each kind. I think this is too limiting, and would like to see two lists, one with numbers (1-100 or 1-500), and the other with minutes-years or something, so you can combine any number, so the user can show an ephemeris from date x-y using 6 days steps, 4 year intervals, 23 saros steps or whatever number he or she prefers.

The reason I ask for this is partly because most other planetariums have features such as this, and also that many ephemerides on the web have "odd" numbers in their presentation. NEOWISE presented using 3 day steps, Jupiter presented using 2 week intervals etc.

**Comment by alex-w** [comment]
Please check version 0.20.2.18093

**Comment by Hood-fr** [comment]
Thanks for this improvement. Would it be possible in future version to have either :
- decimals value instead of integer
- more than 4 digits
- a yy:dd:hh:mm:ss format

I am trying to plot moon analemma and I require to have a step value of 1490.5 minutes (a tidal day), or 43225min (29 tidal days) and I cannot enter such values. Having either of the 3 proposed formats would enable me to do so. Thanks in advance
