### ISSUE TITLE
Solar System Observer point not above the Sun?

### ISSUE THREAD

**Issue by pmccudden** [Stellarium/stellarium#1202]
In version 0.20.2 when I "go" to the Solar System Observer location (by pressing CTRL-G), and then center the Sun to look at it and show the orbits of the planets, the view appears to be from off to the side of the line going through the Sun and perpendicular to the ecliptic plane - in other words, the planets' orbits are skewed (see screenshot). This was not the case in previous versions, where the Solar System Observer location appeared to be directly above the Sun and showed the planets orbits' face on. Am I missing something, or has the Solar System Observer location changed? I use it to show my students what the Solar System and planet orbits look like "from above".  
![image](https://user-images.githubusercontent.com/41452799/89688413-597def00-d8bf-11ea-854a-c0795851d4e2.png)

**Comment by alex-w** [comment]
@gzotti please comment and check this report (I remember your changes for orbital elements of observers)

**Comment by gzotti** [comment]
Indeed this has changed. In previous versions, the SSO was placed on an orbit extremely far out, so that orbital motion was negligible. Now it is on a "gimbal", and with Alt+Cursor keys you can move in ecliptical longitude and latitude, and Alt+Home/End can change distance to the observed object, so you can set between Saturn and Uranus and observe the solar system from an oblique angle. The idea was to allow oblique views of observed planets with many moons, like Jupiter or Saturn. However, it is not yet perfect, and you cannot control rotation of the view.  This would require full implementation of the "ecliptical" mount mode, or really weird trickery with horizontal mount mode for which I don't find time until later this year, sorry. It is still possible to revert this with just one #define in Orbit.h.  Or we make another configurable value, until the issue is completely solved.

**Comment by alex-w** [comment]
I think adding another configurable value, until the issue is completely solved will be better solution here.

**Comment by pmccudden** [comment]
It looks like the default Ecliptic Latitude is -63 degrees for some reason, but ALT-UP ARROW sets it to -90.  And the default distance of the SSO is 1.00 AU, but as you point out, ALT-END increases it.  I will then just use these keyboard commands to go back to the old SSO point for now.  Thanks.
