### ISSUE TITLE
Simulating different types of equatorial mounts

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#1228]
See discussion: https://sourceforge.net/p/stellarium/discussion/278769/thread/7a097e6e12/

The OP want to see simulating different types of equatorial mounts in Oculars plugin - at least GEM mounts for Sensor view.

**Comment by gzotti** [comment]
I still don't get the point.

If you move from the pole along the meridian, why should the lens rotate? It is aligned with the centre line of its short side towards the pole. Your first image BTW shows the frame with a slight rotation caused by not being exactly over the pole. If you move slightly sideways, you easily see it turning.  

When you slew to the pole, you are most likely in gimbal lock. Try to center the pole just below center of the frame to see the frame going upside-down.  The inverted frame has its northern end pointing to the pole. 

Center the lens view to DE=+89.5° on RA=sidereal time+12h. The frame is upright (north=up). Now go "down".  The view still has "north=up". 

The frame orientation is IMHO correct, i.e., there is nothing to do. Stellarium does not lock itself into the mechanical limitations of a telescope mount, though.

**Comment by alex-w** [comment]
The OP want to simulate mechanical limitations of GEM

**Comment by gzotti** [comment]
Yes. There is nothing to do here. If I orient the sensor with "north=up", this orientation will be kept. All OK.

**Comment by Domer82** [comment]
I don't understand what you mean by, 'If I orient the sensor with "north=up", this orientation will be kept.'  I cannot find any setting in any of the menus that allow me to specify "north=up".

**Comment by gzotti** [comment]
The sensor is aligned with north=up when you set "equatorial mount" in the telescope tab. Unless you manually rotate the sensor.

**Comment by Domer82** [comment]
OK, but that's not the issue.  With a German Equatorial Mount, you cannot slew the camera directly downward from the celestial north pole, but Stellarium allows this motion.  With a GEM, you MUST rotate the camera 90 degrees in RA and slew it in Dec in order to point at that location.  Stellarium does not model this correctly.

**Comment by gzotti** [comment]
You should not start in the ill-defined point called pole (a kind of singularity). 
If you mount your camera so that celestial north=up near the celestial equator, celestial north will be up when pointing to +50°, +60°, +70°, or +80° of declination, regardless of RA. (Slew in RA and see the camera rotating with respect to azimuth to keep celestial north "up".) At some point the NCP will come into view, and when looking directly into the pole, south is on every edge. The bottom of the frame will still be centered on the RA you were originally pointing at. If this RA happens to be sidereal time+12h, and you move south, away from the pole, you slew "down from the north pole".

**Comment by gzotti** [comment]
Then it may be time to mount your camera 90° rotated.

**Comment by Domer82** [comment]
Why would I want to do that?  That would only move the center of gravity farther from the rotational axis of the mount, which increases instability and flexion.

Is there some reason Stellarium can't just model GEM behavior correctly?

**Comment by gzotti** [comment]
You may want to do that because the 90° rotation seems to confuse you. If the camera is 90° rotated compared to what you see on the screen, you can rotate the camera, or the display of the sensor box. These are the options. There is nothing that can be "fixed" in the program, because it just works correctly when you move the mount in RA/DEC. 
If the point is that you want to move the view parallel to RA/DEC when you press the cursor keys, you must change Stellarium itself into equatorial mode (Ctrl+M).

**Comment by Domer82** [comment]
I'm not confused.  For some reason, I just don't seem to be able to convey the issue to you, although Alex seems to understand.  So I took the time to set up my rig and shoot a video to show you what I'm talking about.  Please [download it](https://drive.google.com/file/d/1wvkU0tJPQXLORJ3Y7BcQj9mVebgeJnBE/view?usp=sharing) and watch.

I'm not the only person who has noticed this.  There are multiple threads in the Cloudy Nights forum in which this issue is discussed and acknowledged to be incorrect for GEMs.  I'm simply suggesting that the Oculars feature be enhanced to properly model GEM behavior to make a great tool even better.

**Comment by Domer82** [comment]
It might be as simple as adding a new setting that defines the initial camera orientation, with landscape being the default rather than portrait (90 degrees rotated).  

I agree with you that Stellarium models the EQ mount properly if the assumption is that the camera is in a portrait orientation to begin with.  But in most cases, that's not how people set up their equipment.  Does that make sense?

**Comment by gzotti** [comment]
Of course you need to rotate the sensor frame by 90° in this setup. Or rotate the camera along its optical axis (why should that change balance?). Go to the cel. equator to see that. 
Stellarium can align the screen either vertically or along declination lines. To move along declination means upward/downward on the screen. If you set Stellarium into equatorial mode, rotate the view 90° sideways and then move in declination. This is what your sideways declination motion does. But usually I star align my mount, so the angles along the axes make sense. Usually I would then set RA of my target, set DE of my target, and then the object is in view. And if done correctly, there is a motion that leads you from the NCP towards the north point. 
Your mount allows swinging through the pole, which Stellarium cannot provide. This may make some motions incompatible. That's life.

**Comment by Domer82** [comment]
Well, thanks for your understanding and support.

**Comment by Reihtul** [comment]
> It might be as simple as adding a new setting that defines the initial camera orientation, with landscape being the default rather than portrait (90 degrees rotated).

I think that would be the very best solution :-) 

I have the same issue. When my telescope is parked, my DSLR attached is in landscape orientation, not portrait. And I dont want to change that on my mount for the same reason as OP. But then, it is 90° angle compared to Stellarium camera orientation. To get this fixed I just revert X and Y number of pixels in the camera settings and its all ok after that! But a setting "default parked orientation = landscape or portrait" would be much better :-)

**Comment by gzotti** [comment]
No, this is just a useless button more. Just configure 90° sensor rotation (or define sensor YxY), and all is fine.
