### ISSUE TITLE
Dialogue sizes

### ISSUE THREAD

**Issue by Starryhuman** [Stellarium/stellarium#127]
Hello, I'm running Stellerium on a small 1024 x 600 laptop and the Configuration box size is off screen and the scroll bar does not allow access to items at the bottom of the Plug-ins list.

**Comment by gzotti** [comment]
You can reduce text label size requirements a bit by reducing [gui]/base_font_size in config.ini. But a 600 pixel screen is really very narrow, we need some space for the many options. More people complained about the tiny GUI on their 4k screens...

I once had such a netbook, and some software rejected to start with less than 768 lines of screen space. 
There was a hidden (? don't remember, please google around) screen driver setting that allowed setting 768 lines which are then downsampled somehow. Of course this distorts the view vertically. To compensate, you can use a startup.ssc script in your scripts folder:

 // Startup.ssc for netbook screen setup. 
 // Author: Georg Zotti
 // This is usable on a netbook with physical 1024x600 screen with a display driver set to 
 // 1024x768 resolution. GUI panels may be better accessible with such setting. 
 // The distortion caused by this setting will be compensated by this script.

 core.setViewportStretch(600/768);

Note that this only distorts the projected sky, not any GUI panels. These will still require their pixel sizes, which is often a bit more than 600 lines.

**Comment by Starryhuman** [comment]
Thank you for your detailed response.
A possible long term solution that occurred to me was to change the [DialogSizes] for the Configuration box to  = 815,600 (I believe it is currently 815,669 in version 0.18.0). Perhaps this solution won't work for some other reasons unknown to me?

(P.S. I use the small laptop for convenience to attach to my telescope mount and the setting I require is off-screen in the Plug-ins list)

**Comment by Starryhuman** [comment]
I tried editing the dialogue box size setting in config.ini but it reverts on startup to the larger size. I also found that the script stretches the sky view but not the dialogue box.

Update: I have now managed to enable the telescope mount and this seems to work well (tracking and slewing). Congratulation on producing an excellent system.

**Comment by gzotti** [comment]
The dialog boxes have their minimum size, editing config.ini does not help here.

I had written previously:
>Note that this only distorts the projected sky, not any GUI panels. These will still require their pixel sizes, which is often a bit more than 600 lines.

The purpose of this stretching would be to have an undistorted sky view if you manage to convince your graphics driver that you want 768 lines squeezed onto your 600 lines screen. Such squeezing will be required by other software which does not even start with less than 768 lines.

**Comment by Starryhuman** [comment]
Understood.
Thank you for your help.

**Comment by alex-w** [comment]
Please check version 0.90.0.15901

**Comment by Starryhuman** [comment]
I have run ver 0.90.0.15901 - this has corrected the above issue on my 1024 x 600 laptop. It has enabled me to scroll down to the 'Telescope Controls' under 'Plug-ins' and also allows the Options - 'Load at Startup' box to be checked. Great result!
Thank you for your support.

**Comment by alex-w** [comment]
Good news!

**Comment by gzotti** [comment]
Thanks @alex-w  for finalizing this now!

**Comment by chamilag** [comment]
Hi,

I'm using 800x480  LCD with my Beaglebone Black. I ran into the same issue with the "Telescope Control" configuration window with Stellarium 0.15.1.
Just want to make sure 0.18.1 solves the problem

Cheers

**Comment by gzotti** [comment]
Sorry but an 800x480 screen will easily be too small for anything useful. You can play with screen and font sizes a bit, but there are limits. https://github.com/Stellarium/stellarium/wiki/Common-Problems-for-the-current-version#netbook-with-only-1024x600-screen 
I think I remember xrandr has some options to scale windows.

**Comment by chamilag** [comment]
Hi,
In that case can where should I edit the code to set the parameters that I want to connect my telescope.
These are the requirements:
1) Load the "Telescope control"plugin in the start up
2) Configure the A telescope with these options
  - Telescope controlled by: 1) option
  - Name : MyTelescope
  - Connection delay : 0.50s
 - Coordinate systems: JNow
 - Start/connect at startup check box - checked
 - Serial port : COM1
 - Device model : Meade LX200
 - Use field of view indicators : check box checked
 - Circle size : 2

Cheers
