### ISSUE TITLE
Calendar options

### ISSUE THREAD

**Issue by goedible** [Stellarium/stellarium#1313]
Hi.  I can imagine calendar options that would allow people to try different types of calendars.  For example with lunar calendars like the Chinese, Vietnamese, Hindu, and Thai calendars.
I see this a powerful aid in teaching the importance of calendars and how they can help us relate to cosmic influences.
By the way... stellar work so far!

**Comment by gzotti** [comment]
Yes, I can also imagine that. Even without cosmic influences.
This is an obvious candidate for a plugin. Volunteers, go ahead.

**Comment by goedible** [comment]
Thanks for lettimg me know George.  I would like to volunteer however I
have very limited programing skills.  I dropped out after my first java
course in college.  Do you have any suggestions where I should be surfing
the Web to look for programers?

**Comment by gzotti** [comment]
I don't know if "surfing the web" will yield a result. I think most people here are obsessed developing things they urgently need themselves, but don't have the time doing it all. (We do have daytime occupations...) A calendar plugin has been on my long unwritten list of want-to-have-myselves for years. My first two algorithm books are about 2 armlengths away. Just that other things I need more urgently turned out to be trickier than expected.

Other programmers take money to implement what somebody else wants from them. Doing it takes some time to carefully study how the program works and how to best read and write dates. It should not be too difficult. But would you pay 2-3 months (estimated) for a professional "business" developer at full rate, with tax&insurance?

In principle you could also even just implement some date control as multi-calendar web interface, an extension of the RemoteControl plugin. My own Javascript is too limited for that path, though.

**Comment by goedible** [comment]
It would perhaps motivate me to make more money.  I would pay if I thought
that I could afford it.  I am unfamiliar with salaries and wages for
programers, however at this time I can not aford to pay someone minimum
wage for more than a week and a half so I think I'll need some time to save
up.
