### ISSUE TITLE
Support for macOS M1 (ARM) ?

### ISSUE THREAD

**Issue by freebrowser1** [Stellarium/stellarium#1417]
It would be nice that native mode on macOS 10.16 and higher on ARM CPUs would be supported.

Running Stellarium without the need of Rosetta.

**Comment by alex-w** [comment]
Important note: at the moment Qt is not support macOS for ARM64 arch.

**Comment by khain2007** [comment]
Maybe you can try following the guidelines published in https://bugreports.qt.io/browse/QTBUG-85279

**Comment by gzotti** [comment]
We are users, not developers, of Qt. If somebody needs something urgently in an open-source project, you know my position...

**Comment by alex-w** [comment]
I can try build Qt from source, but probably it will be not very fast

**Comment by alex-w** [comment]
No success.

**Comment by drwetter** [comment]
The QT port (link) above seems to be done ( not 100% sure though as some mention rosetta. 

Has anybody tried this?

**Comment by shuwn** [comment]
Hi, @alex-w 
Could you you help test the new version of QT? thank you!

**Comment by gzotti** [comment]
If with "new version of QT" you mean Qt6, no, Stellarium is not yet compatible.

**Comment by markus-k** [comment]
I just compiled Stellarium from source for arm64 and it runs very nicely so far. On M1 Max I'm getting about 80-90fps with the native build compared to 40fps (+ occasional stutters) with Rosetta.

Qt5 was installed from MacPorts, but I skipped QtWebEngine (couldn't be bothered to install tons of dependencies for it).

To make sure Stellarium is built for arm64 you have to adjust [this line in CMakeLists.txt](https://github.com/Stellarium/stellarium/blob/8e6104e9e0c7ea19ca4c55cb3625f1173a2ceed9/CMakeLists.txt#L304), otherwise you'll get linker errors for every single symbol.

Would be very nice to see official native Apple Silicon builds if there aren't any other major issues to be found. If building with QtWebEngine is a problem you could create two separate builds for x86_64 and ARM with it disabled on the ARM build instead of a Universal Binary, but from what I understand these issues have been resolved.

**Comment by markus-k** [comment]
@Atque From a quick test it seem like huge improvement. It's the difference between almost unusable with Rosetta vs still quite usable with occasional stutters (probably when downloading in the background?) on the native build.

**Comment by alex-w** [comment]
@Atque @markus-k please check the fresh binary package

**Comment by Atque** [comment]
@alex-w Great, I see a major improvement in performance (twice the FPS or more), especially when selecting objects. Finally the HiPS is usable.

**Comment by freebrowser1** [comment]
It works fine on an M1 Macbook Pro.

What about a Linux ARM version ? I installed it on Ubuntu 20.04LTS (ARM64) but it showed version 0.19.

**Comment by alex-w** [comment]
> What about a Linux ARM version ? I installed it on Ubuntu 20.04LTS (ARM64) but it showed version 0.19.

See our PPA: https://launchpad.net/~stellarium

**Comment by freebrowser1** [comment]
I already did it last week.
