### ISSUE TITLE
Another error in the S&T sky culture

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1438]
Comparing the S&T sky culture of Stellarium to the interactive star chart on S&T website (https://skyandtelescope.org/interactive-sky-chart/), I found that the Puppis constellation doesn't match. From the S&T star chart, we see that there is a line between nu Puppis and Canopus, but in Stellarium, the line goes from nu Puppis to a non-obvious star of magnitude 6 (HIP 30953). I find it unlikely that this star was intended. Compare these screenshots:

![s t_correct](https://user-images.githubusercontent.com/37028368/103181273-c0686880-489f-11eb-9e04-0c9009a363ed.PNG)

![stel_wrong2](https://user-images.githubusercontent.com/37028368/103181293-eee64380-489f-11eb-9fc5-e4953c44dfd3.PNG)

**Comment by alex-w** [comment]
See also: 

![](https://www.iau.org/static/public/constellations/gif/PUP.gif)

**Comment by skaven81** [comment]
Thanks for the heads-up, I'll get this fixed.

**Comment by skaven81** [comment]
Actually, this is correct.  If you look in the IAU chart noted above, the line is indeed broken between nu Pup and Canopus.  The reason for this is that Canopus is part of Carina, not Puppis.  Sky & Telescope has a convention where they do not fully connect constellation figure lines to stars that are not members of the constellation.  Another similar case of this in the S&T charts are the lines going between Algenib and Alpheratz, and Scheat and Alpheratz, in Pegasus.  Alpheratz is in Andromeda, not Pegasus, so on the S&T charts, there is a gap in the line.

The data that Sky & Telescope provided for their constellation figures, handles this by terminating line segments at specific RA/Dec coordinates rather than stars.  Stellarium, however, must terminate all constellation figure lines at stars, and so I wrote some code that queries VizieR for the brightest star near the RA/Dec location noted in the S&T data.  In the case of the line going from nu Pup to Canopus, here's what is in the S&T data:

```
 4.64  7.58967 118.3694 p   2Pup 
 2.70  7.28572 127.0975 pi  2Pup 
 3.20  6.62936 133.1961 nu  2Pup 
-0.72  6.4537  140.761  alfC2Pup
```

The last four characters of each line denote a contiguous line segment.  In this case, the line segment ends at (supposedly) alpha Pup with mag -0.72 (Canopus).  However, note the RA/Dec coordinates.  Canopus is at 6h23m57s/-52d41m43s (6.399/-52.695).  Look at the RA/Dec in the S&T data -- 6.4537/140.761 (they use north polar distance, not declination), which is 6.4537/-50.761.  Guess what's right near that coordinate?  HIP 30953 B, a mag6 star at 6.496/-50.239 -- right where the S&T data says the line is supposed to end.

Now...the question of course, is whether we should stick with this convention for Stellarium data.  It's not really right for the line to end at HIP 30953 B.  But it's also not really right for the line to end at Canopus.

**Comment by alex-w** [comment]
In other hand see lines for Carina, Vela and Pyxis. The main problem are Puppis and 3 other constellations was one big constellation is past time and obviously lines for all these constellations connection together by historical reasons.

**Comment by gzotti** [comment]
@skaven81 an observer can play connect-the-stars with stars only, not with invisible borders.  When a line so obviously intends to connect to a bright star in a neighboring constellation (which used to be one until destroyed by Lacaille, as Alex has pointed out), it is better to code this star, and not find a dim replacement next to it just because it is close to the border. The same goes for alpha And == delta Peg. The star simply belongs to both constellations. There may be further cases.

**Comment by skaven81** [comment]
@gzotti I agree, but note that my hesitation is due to the fact that the `western_SnT` skyculture is meant to match the Sky & Telescope atlases as much as possible.  If S&T doesn't complete the line, then in theory, we shouldn't complete the line either.  However, since Stellarium has no mechanism for drawing constellation lines that do not terminate at a star, the best option is to simply complete the lines all the way to the target star.

**Comment by gzotti** [comment]
See their own online map: star to star as well.

**Comment by skaven81** [comment]
@gzotti  no...the S&T (and IAU) charts do _not_ have star-to-star connections.

Canopus has a gap:
![image](https://user-images.githubusercontent.com/5861261/103243061-61413d00-490d-11eb-8dec-38ce1423808d.png)

More gaps here around Regor:
![image](https://user-images.githubusercontent.com/5861261/103243142-b5e4b800-490d-11eb-94d1-8069490c25cb.png)

And gaps around Alpheratz:
![image](https://user-images.githubusercontent.com/5861261/103243173-d14fc300-490d-11eb-827a-0e14b8bbd2f7.png)

So the question here isn't "are there gaps in the lines" --- there absolutely are gaps in the lines from S&T _and they are intended to be that way_.  The question is, for the Stellarium representation of the S&T data, how do we deal with the gaps?  Stellarium can't just end a line in the middle of space, it _must_ end a line at a star.  And so approximating the S&T truncated lines by terminating at a faint star near the location of the S&T-depicted end-of-line is one approach.  Another approach is to ignore the gaps and have each line end at the natural endpoint -- a bright constellation star.  This second approach is the one I think is best, and is why I coded the S&T data to stellarium constellation conversion tool to use a search mechanism when identifying the vertices of each figure.  For S&T-provided lines that terminate reasonably close (within 1.5 degrees) of a bright constellation star, it finds and uses that star as the vertex instead of something else.  Canopus was an aberration because the S&T-provided line termination coordinates are _very_ far away from the coordinates of Canopus, and so the script did not find it when searching.  The issue with Ursa Major seems to be a transcription error in the Hipparcos database or maybe VizieR.  And Mensa and Microscopium don't have constellation figures at all that S&T provides, so I approximate them by drawing a line between alpha and beta.

**Comment by gzotti** [comment]
I said ONLINE MAP (see first post in this thread). This is their own implementation in an interactive application.
If Men and Mic have no lines, also not in the S&T online map, there should not be lines in Stellarium's rendition of S&T's skyculture.
