### ISSUE TITLE
sun position in the window 'sky option and visualization'

### ISSUE THREAD

**Issue by LivioE** [Stellarium/stellarium#1455]
I is very useful for all astrophotographers follow the position or movement of planets and consterllation and stars and knowing in the same time the sun position height (h/az system) under or below the horizon line. I ask to add as additonal information in the windows of 'indicators' ' celestial sphere' the possibility to mark 'x' the information 'sun heigh value' (or similar expression).
So when you follow mercury / veus /.... at the horizon, you can also understand the height of the sun at hte same moment.
Thansk a lot

**Comment by alex-w** [comment]
Please see AstroCalc/Graphs tools

**Comment by axd1967** [comment]
@LivioE  Do you mean something like this? this is what @alex-w refers to:

![image](https://user-images.githubusercontent.com/3529789/103483519-10878380-4de8-11eb-9dbc-f864d1aabdbb.png)
![image](https://user-images.githubusercontent.com/3529789/103483525-1a10eb80-4de8-11eb-87a8-7e901d6c097e.png)

Or maybe you want an entry "sun altitude" in the info block (left side of the screen) of the object>

![image](https://user-images.githubusercontent.com/3529789/103483571-74aa4780-4de8-11eb-90dc-e530bb075ca1.png)


or maybe the so-called "solar presence" (whether the sun is above/below the horizon)?

(https://ssd.jpl.nasa.gov/horizons.cgi):
![image](https://user-images.githubusercontent.com/3529789/103483666-221d5b00-4de9-11eb-9491-3ee8fa4b96f8.png)


but where would you want to see the 'x' ? or maybe an 'x' somewhere in the visible viewport, in the direction of the Sun?
![image](https://user-images.githubusercontent.com/3529789/103483775-e5059880-4de9-11eb-8253-1607cfd63722.png)

**Comment by alex-w** [comment]
@LivioE any feedback please

**Comment by gzotti** [comment]
I think OP wants a 29th line of information :-)

**Comment by LivioE** [comment]
Thanks a lot, but your answer is for a different point. not related with my suggested idea. I am not interested in analemma, I know this option. I refer only to ADD the information on the sun height under(below horizon in a row (for example the last) together with other infos. Not graphically, only number. For example, today at 21.00  (Bologna area) the Moon is Alt/az 5°/282° (round for simplify), and what the height of the sun at same moment ? The height is (below horizon) - 9°  . The information we photographers need is : "Sun heigt (-) 9°17'
Not the analemma. Thanks a lot for your time

**Comment by axd1967** [comment]
Reminds me of a similar request for the Moon: what is the altitude of the Moon for the shown sky - in other words, how might Moonlight interfere in the current date/time/location setting. A workaround is to somehow keep an eye on the Moon (eg select it, and look at the altitude line), and/or use an Archaeoline as a quick means to tell where the Moon is, and/or magnify the Moon so that it is well visible.

**Comment by axd1967** [comment]
This is interesting information, but due to the fact that it is not related to the selected object, IMHO it should be shown somewhere else. There is already a lot of critique on the ever growing list of information that is slowly overflowing. This reduces the value of the information panel - it risks to become a bin of all sorts of information.

To test this, just select any visible object and notice that the information is the same. In other words, this is not a property of the selected object.

IMHO this belongs in a separate area on the screen, e.g. in the status area, next to the date/time information (I did not test whether there is enough space there, but at first sight there is). So this is a good improvement for a future iteration: move to the status area, or to a separate panel that floats or is elsewhere, similar to the Ocular control panel, mouse coordinates, angle plugin. Ideally, this could be represented in a graphical way too so that Sun and Moon presence can be judged much more quickly than only by numbers. Vectors similar to what can be found in military aircraft HUDs is one way of implementing this: short lines that emanate from some fixed point and point to Sun and Moon if visible.
