### ISSUE TITLE
Great Red Spot requires incorrect longitude

### ISSUE THREAD

**Issue by mcovington** [Stellarium/stellarium#147]
In order to get Jupiter's Great Red Spot to appear in the correct position, I have to input a custom longitude that is 80 degrees away from the longitude given by JUPOS.  Details here:

http://www.covingtoninnovations.com/michael/blog/1805/index.html#x180505A

I have verified this in 5 installations of 0.18.0, one of which was completely fresh (no files carried over from anything earlier).  It does not appear to be new in 0.18.0 although I did not put any effort into tracking it in earlier versions.

**Comment by alex-w** [comment]
Annual drift is about 20 degrees. 

Are you have a photos or you has just visual observations of GRS?

**Comment by gzotti** [comment]
It is quite possible that the GRS is off. I had intended to be working on improved solutions for planet rotations, but daytime work interfered. In any case, enable light time correction when comparing with earth-bound observations.

**Comment by alex-w** [comment]
Similar report: https://bugs.launchpad.net/stellarium/+bug/1657501

**Comment by fliker09** [comment]
It seems this issue is back... So, before re-opening this ticket / opening a new one, I would like to run it by you and check if I do something wrong or not
![Screenshot_20200628_025853](https://user-images.githubusercontent.com/18057950/85957949-66432500-b99a-11ea-88bd-c4061a53d4ba.png)
This is what was calculated by CalSky and it seems to perfectly match with:
http://jupos.privat.t-online.de/rGrs.htm
But I had to correct the value which I had to introduce into Stellarium:
![Screenshot_20200628_030014](https://user-images.githubusercontent.com/18057950/85957970-925ea600-b99a-11ea-8ba6-8ac92e1344be.png)
Difference is ~55 degrees. Could you please tell me if it's a bug or not?
