### ISSUE TITLE
script load button should remember its last folder location.

### ISSUE THREAD

**Issue by ssagerian** [Stellarium/stellarium#1500]
**Is your feature request related to a problem? Please describe.**
Loading scripts from file button, doesnt recall its last location. 
Every time I want to load a script that I keep in appData/roaming/Stellarium/scripts folder is a pain, because the app doesnt remember its last know folder location and goes back to searching in the programs/stellarium/scripts location 
(this is windoze, 0.2.4 is my current release )

**Describe the solution you'd like**
When I click on the load script button it remembers where (folder/directory) it last loaded a script.

**Describe alternatives you've considered**

**Additional context**

**Comment by axd1967** [comment]
(0.20.4)
A similar issue exists for saving/loading bookmarks - the software does not remember the last saved to directory.

**Comment by axd1967** [comment]
and see also #995

**Comment by alex-w** [comment]
> Every time I want to load a script that I keep in appData/roaming/Stellarium/scripts folder is a pain, because the app doesnt remember its last know folder location and goes back to searching in the programs/stellarium/scripts location

Did you have enabled option "Load scripts from the User Directory by default"?

**Comment by alex-w** [comment]
Any feedback please

**Comment by alex-w** [comment]
Did you checked settings?

**Comment by ssagerian** [comment]
I have not checked it, will check it this evening and return status.

**Comment by axd1967** [comment]
> The hardware info, steps of reproduction and log file are really important and help us resolve over 90% issues fast. Of course, in some specific cases we need more data, but we ask the required data separately...

With all respect, there is no need for this information.

The issue is clear: 

_As a user, when I want to load a script, I want the software to remember the directory path that contained the script I opened previously, **so that I don't always need to navigate to my script directory.**_

## Workaround
There are a few ways to work around this issue. First, you need write access to the directory (let's call it `SCRIPTDIR`) that Stellarium always wants to open.

I don't have **Windows**, but try this: store all your custom scripts in a subdirectory of the directory `SCRIPTDIR` above.

![image](https://user-images.githubusercontent.com/3529789/122032147-a7ad2a00-cdcf-11eb-8d16-c70c86b88b8c.png)

(But I'm not sure a user has the rights to create a directory there, as that location is supposed to belong to Stellarium)

Another workaround is to keep your scripts near your home directory, so that you don't need to navigate a lot. 

On **Linux**, you can create a directory of your liking anywhere and add a **symlink** to that directory in `SCRIPTDIR` or in your home directory.

At first sight, a solution could be to initialise the `dir` argument to `openDir` and subsequently remember the path of the returned file. If I'm not mistaken, that information can be stored in the QFileDialog object (unless it is completely destroyed, but sometimes this kind of object remains hidden but active).

https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileName

**Comment by gzotti** [comment]
FYI: Sometimes setting labels trigger github bots to automatically send standardized messages which sometimes not completely  fit. The "incomplete" is a result of the OP not answering for more than two months. But thanks for your extended thoughts.

**Comment by alex-w** [comment]
I'm very, very angry!!!

Let me show settings tab in Script Editor:
![stellarium-script-editor](https://user-images.githubusercontent.com/88731/122040853-874a9300-ce02-11eb-96d5-9c2cad5c5d79.jpg)

Now I want to see explanation what is wrong with you @axd1967

**Comment by axd1967** [comment]
to reply: there is nothing wrong with me :-)

the "Load scripts from User directory" is indeed an improvement, but always forces the user to start from there, so this is only a small relief. if the user has - for any reason - a deep script directory structure, this is still a PITA as (s)he always has to navigate from the user dir to the desired dir.
