### ISSUE TITLE
Non-altitude dependant twinkling of supernovae, novae etc.

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#1542]
There is a small error in some plugins, such as the supernova and nova plugins, where the objects are not affected by the altitude-dependant twinkle which applies to the stars.

I have tried to fix this myself, but alas, my abilities are too limited.

**Comment by alex-w** [comment]
I've checked twinkling a supernova SN1054A right now and it works as expected. Probably you will not see an obvious twinkle of supernova when it is very bright. Please try to increase a twinkle factor to check the feature.

**Comment by Atque** [comment]
@alex-w No, this is about the twinkling being dependant on altitude. That means, a supernova will twinkle just as much when at zenith, as it does when it is at the horizon. This is not the case in nature, nor for stars in Stellarium.

**Comment by alex-w** [comment]
Ah! You want to improve https://github.com/Stellarium/stellarium/blob/master/src/core/StelSkyDrawer.cpp#L430 for all star-like objects.

**Comment by Atque** [comment]
@alex-w Not sure, but this is what I ask for: https://github.com/Stellarium/stellarium/commit/b58c20ed5bbef7479ce81b7e56a1993852c4f167
This particular commit made stars' twinkle altitude dependant (a star close to the horizon will twinkle more than a star at zenith), but it does not apply to supernovae or novae.

**Comment by gzotti** [comment]
"Twinkling" is deliberate jitter in brightness. If drawing is done on single-precision float (Vec3f), the object may jitter in position. Please increase position to Vec3d. However, when atmosphere is on, some positional jitter will still occur, still probably due to rounding effects. There may be some float in the chain, but I have not found it. (TBH, positional jitter with atmosphere on looks better, so it did not hurt me...)

**Comment by Atque** [comment]
@alex-w Thank you, this solution works!

**Comment by axd1967** [comment]
I'd be tempted to think that twinkling is strongly related to the airmass value:

https://github.com/Stellarium/stellarium/blob/f5740f7944167b0bfbecde1c25b599908c77860a/src/core/StelObject.cpp#L242

## note
I didn't check if there is a DRY issue with this line:
https://github.com/Stellarium/stellarium/blob/f5740f7944167b0bfbecde1c25b599908c77860a/src/core/StelObject.cpp#L802

## tip
when referring to code in issues, it is a good idea to take the extra effort to refer to a SHA1, not to a branch, because the branch will evolve over time and make the comment in the issue difficult to understand.

avoid:
https://github.com/Stellarium/stellarium/blob/master/src/core/StelSkyDrawer.cpp#L430

prefer:  (which is currently identical to the line above)
https://github.com/Stellarium/stellarium/blob/37c7d0ae9082ab251e16bf942c161000bdb2c921/src/core/StelSkyDrawer.cpp#L430

**Comment by axd1967** [comment]
(and twinkling should be less apparent for non-point-like objects such as stars.)

**Comment by Atque** [comment]
> (and twinkling should be less apparent for non-point-like objects such as stars.)

What do you mean? Stars are point-like objects.

**Comment by axd1967** [comment]
sorry, my mistake - I mean of course point-like objects such as stars.

a realistic model could introduce changes in spectra as well as a _positional_ "jitter": eg stars low on the horizon will show more of a firework effect (some frequencies popping out occasionally) and _wiggle_ a bit more.

**Comment by gzotti** [comment]
Yes, feel free to add wiggles and color changes. The positional jitter is not intended, but I also don't fight it (yet). Without atmosphere, the stars should be stable, and there is some (originally unintended) didactic value to it... For IT people, there is the didactic value of rounding or data extinction effects.

**Comment by alex-w** [comment]
@axd1967 yes, but what about suggesting some research papers for obtaining the data for correlation between twinkling of the stars, air mass and atmospheric conditions?
