### ISSUE TITLE
Year 0 BC???

### ISSUE THREAD

**Issue by Psalm19Astronomy** [Stellarium/stellarium#1544]
Hello,
I am doing some research on the star of Bethlehem mentioned in the story of Jesus' birth in gospel of Matthew which mentions the visit by the Magi. I tried specifying dates in 2 - 4 BC for lunar eclipses and planet conjunctions and found that Stellarium was off by a year. That's when I discovered that Stellarium has an entire year 0 which doesn't exist in our modern calendars. The calendar should go from Dec. 31, 1 BC (or BCE) to Jan. 1, 1 AD (CE).

Any chance of slipping in a fix on an upcoming software version?

E-Ray

**Comment by gzotti** [comment]
Stellarium is NOT OFF, and there is NOTHING TO FIX! It is an astronomy program using astronomical conventions. This question has been discussed and answered on each and every support channel, the User Guide (Appendix F.8), and the FAQ https://github.com/Stellarium/stellarium/wiki/FAQ#There_is_no_year_0_or_BC_dates_are_a_year_out.

**Comment by Psalm19Astronomy** [comment]
Thanks for the quick response. I wasn't aware of the Astronomical numbering calendar. So maybe it would be good to add a setting for Julian and Common Era options with Astronomical as the default chronological setting.

Regards, E-Ray

**Comment by gzotti** [comment]
Are you running version 0.20.4? Have you activated the Calendars plugin which I have written for YOU personally? Please see the User Guide, section 13.10.

**Comment by Psalm19Astronomy** [comment]
Hi Georg,
I just checked and am using way old version 0.11.2. I will update and look at the user guide section 13.0.
Thanks! E-Ray

**Comment by axd1967** [comment]
It is easily predictable that this will remain a issue that will continue to pop up, and that is easily solved by letting software help the user rather than impose (artificial) limitations, as it will hurt some users anyway and the solution is relatively simple: add a few calendars: "common era" (using the CE/BCE notation) and a "historian" calendar that follows the "odd" rule (where year 0 is left out). It can make Stellarium only more attractive to a larger audience.

a setting is too specific and probably ugly to implement.

also, less easy to solve, AD should be a prefix, and BC a suffix. (see [NASA link ](https://web.archive.org/web/20130509055447/http://eclipse.gsfc.nasa.gov/SEhelp/dates.html) and [Espenak](http://astropixels.com/main/dates.html))

do note that NASA is also dropping the dots. (see also #1419); I'd be tempted to state that with all due respect, Jan Meeus is in a minority (I'd say old fashioned) position, and Stellarium really needs all possible pixel space.

maybe the FAQ could see [this link](https://web.archive.org/web/20130509055447/http://eclipse.gsfc.nasa.gov/SEhelp/dates.html) replaced with [this link](http://astropixels.com/main/dates.html)?

please let's stay positive.

**Comment by gzotti** [comment]
Version 0.11.2. Oh well... we expect reporters to discuss shortcomings in the latest version after reading the User Guide. 

As stated everywhere, Stellarium is an astronomy program which is using astronomical year counting. This will not change. Period.

Plugins extend its capabilities for particular usage domains. The Calendars plugin is now (due in 0.21) at 23 calendars. And yes, this has all the AD/BC thingies, sans prefix/postfix. But with documentation. With dots, as long as I prefer that. And some further polishing that does not require discussion now, later on.
