### ISSUE TITLE
Loosen the limits on constellation_line_thickness and line_thickness in viewDialog.ui

### ISSUE THREAD

**Issue by ArsenArsen** [Stellarium/stellarium#1618]
**Is your feature request related to a problem? Please describe.**
When using Stellarium to render to extreme resolutions (e.g. 12k - i.e. scaling 4k up three times) using the custom size option for screenshotting, line thickness of `5` is simply not enough to make reasonably thick lines.

**Describe the solution you'd like**
Up the max values of the two spinners, or entirely remove maximums.

**Describe alternatives you've considered**
Alternatively, and this is a more involved solution, these options could be switched off of pixels in favor for some resolution-independent measure (based on DPI), such as millimetres, although that is probably unnecessary.

**Additional context**
The two properties involved:  
https://github.com/Stellarium/stellarium/blob/master/src/gui/viewDialog.ui#L4747-L4749   
https://github.com/Stellarium/stellarium/blob/master/src/gui/viewDialog.ui#L3941-L3943

**Comment by gzotti** [comment]
Valid point. But we should not do that in the GUI, but simply multiply the line width by screen scale factor.

**Comment by gzotti** [comment]
Good first step. A full solution may in addition have to divide requested screenshot size by current viewport size, set all linewidths with this multiple before screenshooting to very large sizes, and revert the sizes after the screenshot.

It may also be possible to set the line widths via script, so that people who make 12k or 16k screenshots can override the range available in the GUI. I would still abstain from making 15px lines available in the GUI.

**Comment by ArsenArsen** [comment]
> I would still abstain from making 15px lines available in the GUI.
The limit seems kinda needless and arbitrary to me.

> A full solution may in addition have to divide requested screenshot size by current viewport size, set all linewidths with this multiple before screenshooting to very large sizes, and revert the sizes after the screenshot.
+1. This would make doing something like this a lot easier, since it's less guessing and math to see what the result will be finally.

**Comment by ArsenArsen** [comment]
I tried using `./Stellarium-0.21.0-df56370-x86_64.AppImage -u "$(mktemp)" --scale-gui 10` on the weekly build, but I couldn't get to the point where I could adjust screenshot size and then screenshot, due to the size of the GUI. I still think that adding the screenshot scaling factor described above would probably fix this issue.

**Comment by gzotti** [comment]
--scale-gui 10? What kind of screen are you using? 

You can always build Stellarium from sources within minutes and adjust the maximal line thickness. For 99.999% of users the current arbitrary max line width is enough. We had the same game for font sizes. Too large fontsize triggers a whole lot of aesthetic problems.

**Comment by axd1967** [comment]
The program won't break because of huge thick lines, but putting this into relation with screen resolution is not bad. 

But this is yet another example of [needless limits](https://github.com/Stellarium/stellarium/issues?q=is%3Aissue%20needless%20limit), especially when it is up to the user to choose the value. if a user wants a 1000-pixel thick line, let it be so... Protecting the user against their mistakes is important, but that doesn't mean the user must be incarcerated in strange limitations. Don't impose artificial limits, just ensure that the casual user receives realistic default values or is able to reset to realistic values. 

(Same goes for unreal font sizes - it's up to the user to accept the consequences of huge fonts.)

**Comment by gzotti** [comment]
The casual user does not make 16k screenshots.

**Comment by alex-w** [comment]
> The program won't break because of huge thick lines, but putting this into relation with screen resolution is not bad.

If you want to see lines only - yes, of course.

> But this is yet another example of needless limitations, especially when it is up to the user to choose the value. if a user wants a 1000-pixel thick line, let it be so... 

This is not our user.  

>Protecting the user against their mistakes is important, but that doesn't mean the user must be incarcerated in strange limitations. Don't impose artificial limits, just ensure that the casual user receives realistic default values or is able to reset to realistic values.

All limitations in the Stellarium follow physical limitations or common sense. Advanced users may set "advanced" values through edition config.ini file. And no, we'll not follow the flat earth, superlight speed or 1 1000000x zooming.

> (Same goes for unreal font sizes - it's up to the user to accept the consequences of huge fonts.)

...a few weeks ago I hear critics from you to bad support a huge fonts size by Stellarium...

**Comment by axd1967** [comment]
> The casual user does not make 16k screenshots.

sure, but that is not an argument to impose artificial limitations, right?
and second: in a few years time, we will all be toting screens with much higher resolutions.
(and third: yes, there will always be users with low resolution screens; they should not be impacted by removing such a limitation)

**Comment by gzotti** [comment]
Not so long ago, line width was 1 without anybody asking. Then somebody asked
* Please improve visibility by doubling line width. --> OK, we added another GUI element and allowed 2, 3, and soon  "why not upto 5"? We decided to set a limit of 5 because else the lines collide with the line labels. Most such decisions have a reason.
* Of course somebody always cannot get enough. 
* Investigate yourself. Line width is implementation dependent. My Geforce allows 10. We can increase to 10px or so, but likely not more for most users. We can make the universal solution, ask the GPU for the max value. Yes, for the benefit of one user plus always one particular further individual. If we just increase limit to 10, that individual will almost certainly complain that the line now disturbs the label. We know that, therefore we decided to limit this at 5.

We can use the same energy for other improvements we deem more important and maybe switch to wider lines at some point when we feel it is useful. We can also waste days discussing every comma. If somebody really needs ultrathick lines or aesthetically pleasing large fonts for his private wall-size poster prints, that somebody is invited to develop a solution that pleases the eye at all conceivable screen sizes, screen resolutions and screenshot sizes, with a 5-8 years perspective of the capabilities of future devices. It cannot be that hard, right?
