### ISSUE TITLE
ocular FOV masks angle measurement

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#1770]
### Expected Behaviour
Angle measurements should always be above other graphical layers

### Actual Behaviour

![image](https://user-images.githubusercontent.com/3529789/123789292-50ce4700-d8dd-11eb-83a7-a88b002a5a2c.png)

### Steps to reproduce

1. check that angle measure plugin is active
2. enable ocular view (ctl-O)
2. activate angle measurement (ctl-A)
3. drag a measuring line from just outside one border of the ocular view to another border

Bug: measurement is not visible
![image](https://user-images.githubusercontent.com/3529789/123789607-a4409500-d8dd-11eb-94d9-0fb70a76d67a.png)

### System
* Stellarium version: Stellarium 0.21.0-b0759ec [master]

* Operating system: 
* Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-74-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM

* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by alex-w** [comment]
I’m not sure that this is a bug.

@gzotti ?

**Comment by gzotti** [comment]
Not a bug, just probably never intended to be combined. The area outside the ocular mask is unreachable by the mouse *by intention*.  But if there is need for the Angle Measure tool while looking through an ocular, somebody could make them work together. Not sure what this would involve: adding some mask unlocking function to Oculars which could be called by the AngleMeasure tool, which gets called on entry and exit of AngleMeasure. What happens if user leaves ocular mode while measuring angles? Think about and solve all edge cases.

**Comment by alex-w** [comment]
I’m mark this issue as “won’t fix”, because this is not a bug. Plus for angular measurements through telescopic view we already added astrometric eyepiece.

**Comment by axd1967** [comment]
A solution I could see is to move the measurement data block from the extremities to the middle of the line while in ocular mode.

for_wishlist
