### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by shotokan3d** [Stellarium/stellarium#1792]
### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by shotokan3d** [comment]
Cannot start Stellarium 0.21.1 - it shows: LoadLibrary failed with error code 126: Module not found.
Windows7, Intel Core i3-2330M, AMD Radeon HD 7670M

**Comment by gzotti** [comment]
One of those unhelpful incomplete error messages... Now the question is: which module? 

Given a zillion of similar incidents caused by automatic updates of all other software components except for Stellarium: 
* Make sure you have updated your graphics drivers, and that OpenGL is working correctly.
* If your OpenGL is flaky, run Stellarium with ANGLE mode (use the link in the Start->All Programs->Stellarium group)
