### ISSUE TITLE
The OBSERVABILITY function doesn't work with the Moon

### ISSUE THREAD

**Issue by nicopop75** [Stellarium/stellarium#1929]
Good morning, I would like to report a bug.

In the new version 21.2 of the program If I select the Moon,  the OBSERVABILITY function does not work.

here attached an image: The OBSERVABILITY does not return any data.

My operating system is WINDOWS 8.1  

[config.odt](https://github.com/Stellarium/stellarium/files/7241072/config.odt)
 
![IMAGE](https://user-images.githubusercontent.com/79394885/135023999-03eb46ad-8475-4134-a0ce-a56b4921ffe4.png)
[log.txt](https://github.com/Stellarium/stellarium/files/7241075/log.txt)

**Comment by gzotti** [comment]
The Observability plugin provided rise/transit/setting times. These are now included in the main program. 

The current behaviour is therefore equal to having "Today's ephemeris" permanently switched off in previous versions.

**Comment by alex-w** [comment]
According to config.ini:
```
[Observability]
Horizon_Altitude                       = 0
Sun_Altitude                           = 12
font_color                             = 0.00,0.50,1.00
font_size                              = 15
show_AcroCos                           = true
show_Best_Night                        = true
show_FullMoon                          = true
show_Good_Nights                       = true
show_Today                             = true
```

only "Today" section shouldn't be visible. I cannot reroduce the issue on Windows.

**Comment by nicopop75** [comment]
I tried to reinstall the software, but I still have the same problem: the plug-in Observability does not show me the dates of the full Moon.     The plug-in settings are correct (see the attached image).
![Cattura di schermata (100)](https://user-images.githubusercontent.com/79394885/135327085-b0b46280-298c-44a6-8ffa-71af4c6a2c25.png)

**Comment by A-j-K** [comment]
I managed to reproduce this. I also fixed it. However, before I bring a PR forward I'd like to find out why @alex-w failed to reproduce it? Maybe I don't understand the expected behavior after the forced show_Today = false was implemented via #1852 

https://github.com/Stellarium/stellarium/blob/master/plugins/Observability/src/Observability.cpp#L1692

For reference, I am on Windows 10 and running a build from GH master branch.

Here's what my fix looks like and if @nicopop75 could confirm this is what they expect to see:-

![2021-11-10_18h58_38](https://user-images.githubusercontent.com/1134086/141176235-3717a408-08fd-4404-8f3b-af456493ef86.jpg)

**Comment by nicopop75** [comment]
Yes, I confirm. That’s exactly what I mean

**Comment by A-j-K** [comment]
> Yes, I confirm. That’s exactly what I mean

Thanks for the feedback. I will create a PR later today (I'm at work at the moment) to begin a discussion with the maintainers on the best way forward to make sure it meets everyone's requirements.
