### ISSUE TITLE
Astrocal ephemeris ignores Ceres, Vesta, ...

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium#2000]
Tested with 0.21.2 fc4c6bb

When computing the ephemeris of Ceres from 2021-10-28 to 2021-11-28, the dialog (F10) remains empty for Ceres.  this appears in b87b419af774a3cb8a2fa5b91bf2badcee0963c7.

![image](https://user-images.githubusercontent.com/3529789/139161105-49fd15d5-5204-4913-a449-df56e4decd80.png)

I tried to update Ceres via asteroid import data; not sure the import succeeded: was Ceres finally updated?

Assuming this is an issue of outdated orbital data (but ... Ceres?) https://github.com/Stellarium/stellarium/pull/1880#discussion_r713987279 might have helped here. 

- [ ]  selecting an object should show the validity date range of that object as a new info line (for_wishlist)

**Comment by gzotti** [comment]
Update the elements. This has been the accepted solution since before the first person has complained in software of the 1990s. We estimate orbit_good to avoid printing bad data. You may always propose your working better solution as PR.

**Comment by axd1967** [comment]
As far as I can see, all 0.21.2 users are affected, am I right?

Updating the elements will not solve this issue. I tried MPCAT 1..9999 (see https://github.com/Stellarium/stellarium/commit/23245d29ead66f03e10d40282ebcd455ec2b66e6#r59605156) to no avail.

**Comment by gzotti** [comment]
Use of outdated elements affects users of all planetarium programs (and has affected manual computers in the 19th century). How far this affects positions and how much wrong positions disturb users depends on their expectations.

**Comment by gzotti** [comment]
Now I see what's really happening. For asteroids with elements and epoch we compute last perihel date and compute orbit_good from that. For asteroids with a few years orbit this may lead to this behaviour that too much time has passed since that previous perihel. So. after all, we have to add epoch to the elements (was scheduled for "later"), and we could estimate a default orbit_good to be equal the orbit period (with all positional error dangers this implies), centered around epoch. For non-elliptic orbiters (comets), we still should keep that at ~1000 days.

For a temporary override of the fuse, set orbit_good to whichever value, about orbital period.

**Comment by axd1967** [comment]
I also tried to copy the elements from JPL as well as MPC but get strange results in both cases.

- https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=ceres
- https://minorplanetcenter.net/iau/MPCORB.html

I think this justifies releasing a hotfix.

**Comment by axd1967** [comment]
@gzotti consider starting a hotfix branch from `0.21.2` (eg `release/0.21.2/hotfixes`) and later merge to `master`.

**Comment by gzotti** [comment]
Six weeks to next release, and too little time to develop. Creating a hotfix release a week before next release for this small issue won't pay off.
