### ISSUE TITLE
Add markers for planet poles, east and west

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2092]
_From the email discussion:_

Would it be possible to add markers for the planet poles and east and west, e.g. as little strokes on the planets circumference?
The markers should be switchable and should only be shown while the planet is reasonably zoomed in.

**Comment by gzotti** [comment]
Poles could technically be added as NomenclatureItems. Else, we had a request for planet grid (#485), so this is almost a duplicate.

**Comment by alex-w** [comment]
> Poles could technically be added as NomenclatureItems. 

Yes, as special case. But (!) be should labels for poles translatable and be should these labels on all SSO or not?

**Comment by gzotti** [comment]
The labels should be translatable (but they should not be in the nomenclature file of transifex, because there most languages can just copy the strings 1:1 - this should be mitigated somehow, as a big fraction of the package meanwhile are strings! Or extended, by translating and displaying the added context info like "town in Mongolia", "Danish astronomer (1546-1601)", ...). 

Yes, all SSO with rotational elements have poles. It's just a question whether the quick fix via Nomenclature should be done, or the grid be implemented. (And then, grid for non-spherical bodies...)

**Comment by alex-w** [comment]
Hmm… maybe use longitudes +90 and -90 degrees on equator as West and East points? Plus displaying these points and color made as dependable from the cardinal points feature?
