### ISSUE TITLE
Display goes blank frequently in v0.21.3

### ISSUE THREAD

**Issue by spindizzy49** [Stellarium/stellarium#2166]
My display keeps going blank in v0.21.3.  Although the has been a known issue for several previous versions I have been using ANGLE mode to launch Stellarium with no problems.
Now, in this latest version, the screen blanking has returned even in ANGLE mode.  Same thing for MESA mode.  It does not happen when I mouse around on the regular star screen or move the sky view around.  It does seem to occur once I click on any of the options buttons on the left side of the window.  Trying to do some things in the windows that open seems to induce the blanking.

Running Windows 11 on an HP laptop with:
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 8 Gb RAM, Graphics: Intel(r) UHD Graphics 620, driver v27.20.100.8935
Log file is attached
[log.txt](https://github.com/Stellarium/stellarium/files/7856982/log.txt)
.

**Comment by alex-w** [comment]
Did you updated drivers for graphics card after upgrading the operating system?

**Comment by spindizzy49** [comment]
Yes, whatever updates I receive from Microsoft got installed after upgrade to Windows 11 and Stellarium v0.21.2 win64 worked just fine using ANGLE mode after the OS upgrade.

**Comment by alex-w** [comment]
Please try install official intel drivers from intel.com website

**Comment by spindizzy49** [comment]
I installed the latest Intel graphics driver from HP's website.  This did not correct the issue.  Installing the driver update using the Intel Driver & Support Assistant from their site disables some features that are needed on my HP laptop, so this solution is not a good one for my system.  Thanks for you help...

**Comment by sincorchetes** [comment]
Confirmed in Linux - Fedora 35 workstation Wayland and Xorg.
It does not work with Intel but yes with Nouveau using DRI_PRIME=1 stellarium.

**Comment by gzotti** [comment]
This issue describes the Intel issue on Windows. On Fedora we had #2127.

**Comment by spindizzy49** [comment]
For what it is worth I did a temporary installation of the graphics driver recommended by Intel's support assistant: Intel(R) UHD Graphics 620 v 30.0.101.1191 date Dec 3, 2021.  Stellarium continues to blank the screen whenever I access the option windows shown by the buttons on the left, particularly the Calculations window.

**Comment by CapitanCaliban** [comment]
This exact problem appears on my computer also. Everytime Stellarium tries to show a tooltip it goes black for a few seconds. An everytime it removes the tooltip the same thing happens. Stellarium 0.21.3. Have tried every mode, including angle, nothing solves the problem. I have the latest graphics drivers from Intel. Win10 64-bit. Intel UHD Graphics 620. Laptop with properties well exceeding the requirements.

2022-01-16T11:06:00
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 15.9 (Visual Studio 2017)
Qt runtime version: 5.12.6
Qt compilation version: 5.12.6
Addressing mode: 64-bit
Total physical memory: 7971 MB
Available physical memory: 2449 MB
Physical memory in use: 69%
Processor speed: 1800 MHz
Processor name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Processor speed: 1800 MHz
Processor name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Processor speed: 1800 MHz
Processor name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Processor speed: 1800 MHz
Processor name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Processor speed: 1800 MHz
Processor name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Processor speed: 1800 MHz
Processor name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Processor speed: 1800 MHz
Processor name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Processor speed: 1800 MHz
Processor name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
C:\Program Files\Stellarium\stellarium.exe --spout=sky 
 -----------------------------------------------------
[ This is Stellarium 0.21.3 - https://stellarium.org/ ]
[ Copyright (C) 2000-2021 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file is:  "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.6.0 - Build 30.0.101.1122"
Current Format:  QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::CompatibilityProfile)
StelMainView::init
Detected: OpenGL "4.6"
Driver version string: "4.6.0 - Build 30.0.101.1122"
GL vendor is "Intel"
GL renderer is "Intel(R) UHD Graphics 620"
GL Shading Language version is "4.60 - Build 30.0.101.1122"
GLSL Version Number detected:  4.6
GLSL version is fine, we should not see a graphics problem.
Detected a high resolution device! Device pixel ratio: 2
Sky language is  "sv_SE"
Planetary features language is  "sv_SE"
Application language is  "sv_SE"
Scripts language is  "sv_SE"
Cache directory is:  "C:\\Users\\onthe\\AppData\\Local\\stellarium\\stellarium\\cache"
Loaded 252 countries
Loaded 193 regions
StelLocationMgr::loadCitiesBin(): TimeZone for  "Nuuk"  not found:  "America/Nuuk"
StelLocationMgr::loadCitiesBin(): Summary of unknown TimeZones:
"America/Nuuk"
Please report these timezone names (this logfile) to the Stellarium developers.
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
SolarSystem has  83 entries.
Loaded 83 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium/data/ssystem_minor.ini"
SolarSystem has  190 entries.
Loaded 107 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15778 / 15780 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_8.cat: 0_0v0_8; 4979"
"Loading .\\stars\\default\\stars_1_0v0_8.cat: 1_0v0_8; 21806"
"Loading .\\stars\\default\\stars_2_0v0_8.cat: 2_0v0_8; 150826"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4941 / 4941 scientific star names
Loading scientific star extra names from ".\\stars\\default\\extra_name.fab"
Loaded 26200 / 26200 scientific star extra names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6862 / 6862 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 22992 / 22992 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108378 / 108378 cross-identification data records for stars
Loading parallax errors data from ".\\stars\\default\\hip_plx_err.dat"
Loaded 117703 / 117703 parallax error data records for stars
Loading proper motion data from ".\\stars\\default\\hip_pm.dat"
Loaded 117955 / 117955 proper motion data records for stars
StelCore: Invalid timezone name: ""  -- not setting timezone.
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.13 (standard edition)"
Loaded 94668 DSO records
Loading DSO outline data ...
Loaded 95 DSO outline records successfully
LandscapeMgr: initialized Cache for 100 MB.
Got location "Malmo, Skåne, Sweden (55.6078, 12.9981; Europe/Stockholm)" for IP "82.209.133.143"
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 1098 / 1098 common star names
Loading DSO name data ...
Loaded 1142 / 1169 DSO name records successfully
WARNING - No position data for 27 objects: "NGC 3184, NGC 5907, NGC 5907, NGC 5907, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 44750, PGC 54559, PGC 59117, PGC 59858, PGC 59953, PGC 69018, PGC 69877, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230, PGC 1000714, PGC 1694462, PGC 2822840, PGC 2826829, PGC 3098124"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
Loaded 81 / 82 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 71 / 72 asterism names
stel.spout: Sender name is: stellarium
stel.spout: Found 2 GPUs
stel.spout:        GPU 0 :  Intel(R) UHD Graphics 620
stel.spout:        GPU 1 :  Microsoft Basic Render Driver
stel.spout: Currently used: GPU 0
stel.spout: Sender has been created in OpenGL/DirectX interop mode
stel.spout: DX9 mode: false
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Oculars::validateAndLoadIniFile() ocular.ini exists at:  "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateAndLoadIniFile() found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalogue file: "C:\\Users\\onthe\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Loaded plugin "SolarSystemEditor"
Using the ssystem_minor.ini file that already exists in the user directory...
Dubious result: Landscape  "Guereins"  not calibrated. Opacity test represents mathematical horizon only.
stel.spout: Sender stellarium released
Unloaded plugin "SolarSystemEditor"
Unloaded plugin "Satellites"
Unloaded plugin "Oculars"
Unloaded plugin "Novae"
Unloaded plugin "MeteorShowers"
Unloaded plugin "Exoplanets"
Downloaded 1 files (0 kbytes) in a session of 41.655 sec (average of 0 kB/s + 0 files from cache (0 kB)).
LandscapeMgr: Clearing cache of 0 landscapes totalling about  0 MB.

**Comment by Greynomad99** [comment]
Same problem in otherwise great software. How do I download ver 20.4? Seems to just want to serve us current 21.3 and no separate download for old versions that I could find

**Comment by gzotti** [comment]
> Same problem in otherwise great software. How do I download ver 20.4? Seems to just want to serve us current 21.3 and no separate download for old versions that I could find

On stellarium.org, the link list on the right side features "all releases".

**Comment by CapitanCaliban** [comment]
Just google the version number and stellarium and you find several sites
you can download from.

Den ons 2 feb. 2022 kl 23:24 skrev Greynomad99 ***@***.***>:

**Comment by tomlut** [comment]
Opening any dialogue box (e.g. location) cause my screen to slowly strobe black. In any run mode. Graphics card drivers up to date.

**Comment by alex-w** [comment]
Would you record small video for demo the "blank screen effect"?

**Comment by tomlut** [comment]
Sorry I can't right now, as my old PC died and I'm waiting on parts to build a new one.

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by alex-w** [comment]
Please check the fresh version (development snapshot) of Stellarium:
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by spindizzy49** [comment]
I installed stellarium-1.22.2-38a869f-win64.exe per your recommendation.  Sorry to report that this test version still has the same issue – trying to do anything in the astronomical calculations windows causes the screen to go blank every few seconds.
Thanks for trying

**Comment by tomlut** [comment]
I'm running AMD on-board graphics on my new PC and it is no longer an issue for me,.

**Comment by spindizzy49** [comment]
For what it’s worth:
2018 HP laptop
Processor - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Graphics - Intel® UHD Graphics 620 (internal)
 
Same issue on a 2014 HP laptop.
3rd generation Intel® Core™ i3-3110M Processor
Intel® HD graphics 4000

**Comment by uwes-ufo** [comment]
please try stellarium-1.22.2-38a869f-win64.exe with --single-buffer

**Comment by spindizzy49** [comment]
How do I do that?  Thx…

**Comment by uwes-ufo** [comment]
> How do I do that?  Thx…

There should be this icon (link) in your start menu.

![Screenshot 2022-09-12 182851](https://user-images.githubusercontent.com/112473593/189709871-15f2af84-3834-44b0-bd2a-049c3e554a78.png)
