### ISSUE TITLE
Inaccuracies in the graphs tool

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#2194]
There appear to be inaccuracies in the graphs tool of the AstroCalc. For example, hovering the pointer above the magnitude graph, the magnitude value given is not the same if you move the cursor straight upward. I can get Mercury to show magnitudes from -1.70 to -2.21 for 2022-04-04, 04:35 UTC+2.

I can reproduce this on Windows 10 and MacOS 12.1 with 0.21.3.

Ideally, the user should be able to hover over any part of the whole graph, and get a value where the Y axis intersects the graph. Possibly, this could also be visually represented, by e.g. a dot moving over the graph.

**Comment by alex-w** [comment]
The AstroCalc/Graphs tools has been refactored, please check the tools again.

**Comment by Atque** [comment]
It works better now, but I still see some discrepancies, although much smaller than before (in the range of a few hundreds of a magnitude, which IMO is negligible). I see the values do not fully correspond to the actual magnitudes when selecting an object. Mercury at 2022-04-07, 19:12:11 (UTC+2) has a magnitude of -1.79 according the the main program, but the graph claims it is at -1.775. Not much of a difference, but I wonder why there is any difference at all?

**Comment by gzotti** [comment]
The mouse reading is not very accurate. But now you can click into any graph to set the time.

The graphs are computed not for each second, but in certain intervals, and connected with a Spline curve. Sometimes the actual value behaves somewhat differently. The graphs should illustrate the behaviour, but if you need accurate results, set time to the second and read the value from the info text. If you want to see the support points, compile yourself and uncomment AstroCalcChart.cpp line 44.

A curve which needs surprisingly many points is the azimuth curve. Here the discontinuity at azimuth=0 requires many points, and you see how slow it gets.

Another is the 2-curves page, here you can set range and intervals now. A magnitude curve is not plotted as Spline, because in case of eclipses of Jupiter's moons the sudden magnitude drop-off would cause Spline tremors. If you set too large intervals, you miss eclipses. Probably also the Malama magnitudes for Mars show interval dependent sampling artifacts.

**Comment by gzotti** [comment]
@Atque does this answer your question?

**Comment by Atque** [comment]
@gzotti Sorry. Yes, this answers the questions. I'm closing this as it has been solved.
