### ISSUE TITLE
Stellarium i heavy after solution "www" in config.ini

### ISSUE THREAD

**Issue by Anthrwpos** [Stellarium/stellarium#238]
Stellarium is heavy after solution (adding "www"in config.in). It takes almost 1 minutes to open after the start image, and when it opens, it moves frame by frame. This occured only after the solution.
[Stellarium crashing](https://github.com/Stellarium/stellarium/issues/224)

**Comment by gzotti** [comment]
@Anthrwpos feel free to read the messages in #224 again and understand that you can revert the URLs to stellarium.org. Without www. There was some temporary misconfiguration.

**Comment by Anthrwpos** [comment]
In config.ini is not with www. I don't know why is so heavy after the suggestion of adding www. or without. Is there a problem with the server?

**Comment by alex-w** [comment]
Could you check 0.18.2RC1 - https://github.com/Stellarium/stellarium-data/releases/tag/beta

**Comment by gzotti** [comment]
Rather something. 
Can you rename config.ini and start again? (To force creation of defaults)

**Comment by alex-w** [comment]
And, for clearance, check behavior after removing www from Stellarium.org urls in config.ini

**Comment by gzotti** [comment]
@Anthrwpos what do you mean? The file to be renamed is config.ini. The stupid and dangerous default settings of Windows may have hidden the .ini extension.  Rename or delete your current config.ini to force creation of a default config.ini. To rename, you can change either "config", or "ini", or both. The result after renaming should be different from "config.ini", a few valid examples for different names would be "config_old.ini", "config_017.ini", "config.ini.bad", "config.ini.bad.txt", or "e5zsbr6jtzhst".

**Comment by Anthrwpos** [comment]
@gzotti The .ini file, is visible, but nothing change by renaming it.

**Comment by gzotti** [comment]
Have you ever sent a logfile as we require in the issue template? If there was something typical with your problem, we should have a few thousand complaints by now.

**Comment by Anthrwpos** [comment]
Why need many complaints, if one has problem, isn't problem?
Problem: Suddenly crashes and after the solution, the program is heavy,  what could be wrong? 
Maybe with adding new graphic or something else, and the pc with low specs can't handle?

**Comment by gzotti** [comment]
This will not be solvable if you don't add the relevant information. You told us absolutely nothing about your computer. Send us your computer, or send a logfile.

**Comment by alex-w** [comment]
Please attach your log.txt and config.ini files (You may find both here: `C:/Users/YOURNAME/AppData/Roaming/Stellarium`)

**Comment by Anthrwpos** [comment]
I didn't install first time the stellarium on my pc. I have it for long time. My pc can hundle very good, but i don't know why this time is so heavy after that. Maybe you did a big change in graphics?
[log.txt](https://github.com/Stellarium/stellarium/files/2259649/log.txt)

**Comment by alex-w** [comment]
Just an for experiment - could you set some default location (F6) and check it again after restart?

**Comment by gzotti** [comment]
You can also disable all plugins. 
Or rename your Stellarium user data directory to act like a fresh installation?

**Comment by gzotti** [comment]
Please care to read chapter 5 of the User Guide.

**Comment by Anthrwpos** [comment]
@gzotti No change again. I'll wait something else..

**Comment by alex-w** [comment]
Please attach log.txt from Stellarium

**Comment by gzotti** [comment]
After doing recommended changes like disabling plugins, log will of course be different after running Stellarium. Also you never sent your config.ini.

**Comment by gzotti** [comment]
"config.ini didn't supported from this site" does not make any sense. The file is located where described in chapter 5 of the Guide.

Why do you think some Stellarium server has a problem? When you reset Stellarium by renaming config.ini, you go back to "standard" behaviour. Disabling plugins reduces the number of possible error sources, and several plugins have data which are updated by occasional downloads. No plugin - no connection attempt. 

A few purely speculative attempts:

* In case you have enabled too many minor solar system objects, e.g. after importing the 1000 comets file or downloading all NEOs from MPC, also *delete or rename* your ssystem_minor.ini in your C:\Users\anthrwpos\AppData\Roaming\Stellarium\data folder. 
* In case you have too many satellites, disable the satellite plugin. To revert to defaults, delete contents of C:\Users\anthrwpos\AppData\Roaming\Stellarium\modules\satellites folder. 

You can also temporarily disable your network connection (switch off WiFi, unplug LAN cable) to see if this is a connection error. Without connection, obviously all problems come from the computer alone. We cannot give further advice when you don't provide these files, because we don't have and cannot reproduce your problems.

**Comment by Anthrwpos** [comment]
About config.in from this website, can't upload:
![default](https://user-images.githubusercontent.com/20747347/44120169-27ba32ec-a024-11e8-93b5-7aa0f52bcb43.png)

"Disabling plugins reduces the number of possible error sources", I don't have add any plugin on my own.

About 1rst and 2nd dot, no change.

"You can also temporarily disable your network connection (switch off WiFi, unplug LAN cable) to see if this is a connection error." Again, no change.

"Why do you think some Stellarium server has a problem?". Because, i didn't open the stellarium for a long time, and the first time after that, it crashed, and i came here to solve it, and it works, but after the solution it's very heavy and slow.

**Comment by gzotti** [comment]
Hint from the 1980s: make file type "compatible" by changing extension to .txt. Or open in a text editor and copy&paste its contents. 

Stop all further trials, uninstall your version of Stellarium, delete your Stellarium user data directory or at least config.ini, and download&install today's version 0.18.2.

**Comment by gzotti** [comment]
I simply don't get what you are trying.

1) Alex wrote:
   ```Just an for experiment - could you set some default location (F6) and check it again after restart?```

I see in your config.ini:
```
   [init_location]
   landscape_name                         = guereins
   location                               = auto
```

You did not set a location but reported "no change".

2) I see various entries like 
```
url                                    = http://stellarium.org/json/novae.json
```
Did we not say weeks ago the final solution was to remove the www from the intermediate solution, producing the final URLs *https://stellarium.org/...* ?


3) This config.ini is from version 0.18.1. Did I recommend to delete everything, forget this misery and start new with 0.18.2? What is wrong or difficult to follow with deleting everything from 0.18.1 and starting with 0.18.2?

4) Of course GPU drivers play a role. Your Geforce 9600 is old but good enough, but the driver version string lacks a version or build number which has been common for quite some time now (years ?), so an update can be useful in many ways, but I don't know what this would have changed between 23 days and 18 days ago when your problems started. 

I will not respond for the next 3 weeks due to lack of time. Hopefully you can successfully delete previous versions, data and config.ini and install 0.18.2 for a real try.

**Comment by alex-w** [comment]
Please check version 0.18.2

**Comment by Anthrwpos** [comment]
@gzotti This .txt file i sent, is before i made the changes, that is why you see the same as you suggested. 
I deleted everything and install 0.18.2. 
But with clear install, i saw no change again. Maybe, it's the GPU driver, that i cannot update it anymore from NVIDIA. (no more support). I saw that 32 bit version of S, has no lag, delay or heavy (i don't know why). From now on this pc, i'll have 32 bit version of Stellarium. (but i have 64 bit OS)

I didn't remove the "www", it wasn't never there.
S, on the other pc (better pc), Stellarium has no problem. GPU maybe is the problem then.
I'll update if something change.

@alex-w As i wrote above 2 days ago (16 Aug. 2018 p.m. EEST), no change.
