### ISSUE TITLE
Up Arrows Increment Twice

### ISSUE THREAD

**Issue by JZepeda1000** [Stellarium/stellarium#2415]
In the Gregorian Date/Time tab, the up-arrows for the year, month and day increment two times when pressed.

**Comment by alex-w** [comment]
Did you used click or double click for change the date?

**Comment by gzotti** [comment]
Cannot confirm with 0.22.1 on Windows. However, there is no "Gregorian Date/Time tab" I am aware of. There is the date panel (F5) and the Calendars plugin with its "Lunisolar" tab which both have elements to increment. For me all work as intended.

**Comment by JZepeda1000** [comment]
Sorry if I wasn't clear. I meant the Gregorian section of the Date/Time window. This is on the Mac OS version. However, I checked this morning and the problem is gone. I will report back if it persists. Thank you.

**Comment by JZepeda1000** [comment]
Sorry if I wasn't clear. It's the Gregorian date section of the Date/Time window. This is on the Mac OS version.

**Comment by alex-w** [comment]
Cannot confirm with 0.22.1 on macOS Monterey.

**Comment by hschneck** [comment]
I have a similar issue with 22.1 and OS Monterey 12.3.1.  Sometimes but not always clicking the Gregorian date section of the Date/Time window will increment multiple hours instead of just 1 hour.  But also in my case Stellarium is just ridiculously slow to respond to any of my actions and before I upgraded to Monterey I did not have this problem.  I was also on a previous version earlier than 22.1.

**Comment by dhdeangelis** [comment]
Cannot confirm in Linux (openSUSE Tumbleweed). Works as intended.

**Comment by hschneck** [comment]
A friend suggested I clear out the files in the application support area and reinstall.  That did the trick!  I guess one of them got corrupted.  Back to being a super responsive application.  Stellarium is a super program!
