### ISSUE TITLE
PEAK DATE FOR TAU HURCULIDS METEOR SHOWER

### ISSUE THREAD

**Issue by chuckboren3** [Stellarium/stellarium#2449]
The peak date for the Tau Hurculids meteor shower seems to be wrong. When I search for it Stellarium (0.22.0) showes it to be 6/9/22 however IMO lists it as 5/30/22 see attached file.
![METEOR SHOWER CORRECTION](https://user-images.githubusercontent.com/42034993/169068854-866f7c6a-4245-4079-b5c7-5c262dda658a.jpg)

**Comment by alex-w** [comment]
@chuckboren3 please update catalog of showers within plugin

**Comment by alex-w** [comment]
Oops... our new source file for meteor showers has a "generic" date for peak of this shower at 3 June, but IMO.net has other date - 30 May. Who is wrong?

**Comment by alex-w** [comment]
@worachate001 could you re-check MeteorShowers.json file?

**Comment by worachate001** [comment]
I'm working on it. There is a predicted outburst of the shower this year with high-uncertainty of ZHR (mainly caused by the comet's fragmentation in 1995 that may create an outburst of 15 to 600+ meteor per hour, favoring North and Central America). For a quick update, I can add 2022 prediction from IMO calendar to the database. However, this is a special case that we have to change the main code to allow changing radiant from original position.

Stellarium 0.22.2 release may be too late for this event, but it's possible that there will be cases like this in the future so we can just update the database.
