### ISSUE TITLE
Stellarium ignore ANGLE mode

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#2471]
I'm using Windows 10, and up until now I had not updated from v0.21.1, but after updating to the last version I noticed that every time Stellarium opens in fullscreen or ALT+TAB out of or into it it now transitions with a black screen in between. Previously it was seamless like a borderless fullscreen window mode. I started rolling back the versions until I reached v0.21.2 where the seamless transition into fullscreen returns for the last time, on v0.21.3 it starts behaving as the latest versions.

Note: to achieve this seamless mode in v0.21.2 I have to be running ANGLE mode `--angle-d3d11`.

Is there a specific reason why this new behavior happens? 

Can I make it behave in a manner that resembles borderless window like before post 0.21.2 versions?

Thanks.

_Originally posted by @ner00 in https://github.com/Stellarium/stellarium/discussions/2469_

**Comment by alex-w** [comment]
See discussion for details

**Comment by alex-w** [comment]
The `spout` and `mesa` modes may be broken too…

**Comment by gzotti** [comment]
I expect the Mesa CL switch will be ignored for the very same reason, and should likewise start when the env var is set accordingly. Probably we just go to the unelegant way of setting the env var in the CLI parser, instead of forwarding some setting and then throw in the initialisation flag when we feel it's the right place. Not sure about Spout, this is handled differently (and I think only works with OpenGL to begin with, but have not checked recently). I hope I can find some time for testing, though.

**Comment by ner00** [comment]
Doesn't seem like it was fixed though. Still doesn't set ANGLE mode when using the default arguments.
[log_v0.22.1-02d6fc5.txt](https://github.com/Stellarium/stellarium/files/8840679/log_v0.22.1-02d6fc5.txt)

**Comment by gzotti** [comment]
Interesting. I guess "works for me" is not enough...

Can you manually set environment variables as described in section 6.5 of the User Guide?

**Comment by ner00** [comment]
There is no section 6.5 in v0.22.1 User Guide: https://github.com/Stellarium/stellarium/releases/download/v0.22.1/stellarium_user_guide-0.22.1-1.pdf

Anyway, as previously mentioned, setting the environmental variables prior to running Stellarium works fine, at least for me. Since upgrading to v0.21.3+, I've had to run Stellarium from a batch file in order to declare those variables to use ANGLE; the environmental variables specified in section 6.2.2 of the latest *User Guide*, as follows:

```batch
@set QT_OPENGL=angle
@set QT_ANGLE_PLATFORM=d3d11
@start stellarium.exe -platform windows:altgr
```

While the above works, this still does not (as of v0.22.1-02d6fc5):
`"C:\Program Files\Stellarium\stellarium.exe" --angle-d3d11`

**Comment by gzotti** [comment]
Sorry, 6.2.2, yes. The updated solution (now) is to set those variables early before starting the main application, instead of setting the corresponding application flag. However, while on my PC this works, on yours it does not. Now explain this to me. Anyway, setting those variables permanently spares you from calling the batch file.

**Comment by ner00** [comment]
I also tested it in a different computer, which also happens to have an Intel GPU ( older model) and there also ANGLE didn't work with the native arguments without manually defining the environmental values.

[log_0.22.1-02d6fc5_Intel_HDG_2500_.txt](https://github.com/Stellarium/stellarium/files/8843260/log_0.22.1-02d6fc5_Intel_HDG_2500_.txt)

Your guess is as good as mine as to why it would work in your system and not in mine. I prefer calling a batch file to restrict the scope of the variables to Stellarium. I'm not sure if I'm running other QT-based applications and/or if I'd want them to run in ANGLE mode, so for now the batch file is completely fine for me.

**Comment by gzotti** [comment]
I have an Intel-only system in my reach (4th gen Core-i5) which I could check. It has enough OpenGL to run well. However, I added a note in the FAQ that describes this weird case.

**Comment by gzotti** [comment]
My Intel reacts as intended to the --angle etc. switches. 

@ner00 has at least a workaround for his weird case, so I consider this solved.

**Comment by ner00** [comment]
Doesn't work for me, bu may be up to current system config or drivers, it's fine as far as I'm concerned.

Thanks.
