### ISSUE TITLE
Cannot Add New Telescope MacOS High Sierra

### ISSUE THREAD

**Issue by renaissancelawyer** [Stellarium/stellarium#254]
### Expected Behaviour
In the Add New Telescope dialog window, clicking OK should add a new telescope with the specified characteristics to the Telescopes Controlled list.

### Actual Behaviour
In the Add New Telescope dialog window, clicking OK to add a newly configured telescope causes a spinning beachball for several seconds and then no effect (a new telescope is not added). Hitting "Enter" closes the dialog window but again with no added telescope. This is the case for any combination of telescope configurations, including a virtual telescope.

### Steps to reproduce
Occurs every time on my system, both with version 0.18.1 and the current beta.

### System
* Stellarium version: 0.18.1, beta 0.90.0.16188
* Operating system: <MacOS High Sierra 10.13.6
* Graphics Card: <NVIDIA GeForce GT 750M 2048 MB
Intel Iris Pro 1536 MB
>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.[log.txt](https://github.com/Stellarium/stellarium/files/2283187/log.txt)

**Comment by alex-w** [comment]
Could you fill the input boxes and show screenshot of this?

**Comment by vincefn** [comment]
Hi, I just encountered an identical issue when trying to connect to a C8 using an USB-serial adapter on MacOS 10.13.6, and latest Stellarium (0.18.2 from GitHub). Solution (at least for me) at the end.

I first checked that I could dialog directly with the serial device using a console login:
`cu -l /dev/cu.USA19H142P1.1 -s9600`
This finally worked (I could send commands and get status from the scope), but required doing first a `sudo chmod 777 /var/spool/uucp/`. (I am not sure this is also needed for Stellarium, it was just for connecting with `cu`)

After that any creation of a new Telescope in Stellarium just got me a spinning wheel (for 20-30s?), independently of the type of telescope to be added, and after this spinning wheel no telescope is added.

I tried previous versions of Stellarium, 0.18.1, 0.17.0.1, 0.16.1.2, 0.14.2 - all with the same issue/symptoms. 

I then tried version 0.13.3, which worked like a charm, and sent successfully goto commands to the telescope.

After starting stellarium (0.18.2) from the terminal/command line, I saw the following lines:

> [..]
> Got location "Saint-Etienne-de-Saint-Geoirs, Auvergne-Rhone-Alpes, France (45.3393, 5.3449; Europe/Paris)" for IP "88.179.156.9"
> SlewDialog::loadPointsFromFile(): No pointss loaded. File is missing: "/Users/raymond/Library/Application Support/Stellarium/modules/TelescopeControl/points.json"
> QGestureManager::deliverEvent: could not find the target for gesture
> [TelescopeControl] port name: "cu.Bluetooth-Incoming-Port" ; vendor identifier: 0 ; product identifier: 0
> [TelescopeControl] port name: "tty.Bluetooth-Incoming-Port" ; vendor identifier: 0 ; product identifier: 0
> [TelescopeControl] port name: "cu.USA19H142P1.1" ; vendor identifier: 1741 ; product identifier: 289
> [TelescopeControl] port name: "tty.USA19H142P1.1" ; vendor identifier: 1741 ; product identifier: 289
> [TelescopeControl] port name: "cu.KeySerial1" ; vendor identifier: 1741 ; product identifier: 289
> [TelescopeControl] port name: "tty.KeySerial1" ; vendor identifier: 1741 ; product identifier: 289
> [TelescopeControl] port name: "cu.Bluetooth-Incoming-Port" ; vendor identifier: 0 ; product identifier: 0
> [TelescopeControl] port name: "tty.Bluetooth-Incoming-Port" ; vendor identifier: 0 ; product identifier: 0
> [TelescopeControl] port name: "cu.USA19H142P1.1" ; vendor identifier: 1741 ; product identifier: 289
> [TelescopeControl] port name: "tty.USA19H142P1.1" ; vendor identifier: 1741 ; product identifier: 289
> [TelescopeControl] port name: "cu.KeySerial1" ; vendor identifier: 1741 ; product identifier: 289
> [TelescopeControl] port name: "tty.KeySerial1" ; vendor identifier: 1741 ; product identifier: 289
> PING localhost (127.0.0.1): 56 data bytes
> 
> --- localhost ping statistics ---
> 1 packets transmitted, 0 packets received, 100.0% packet loss

The interesting part is the failed ping at the end (which is _not_ in the stellarium log so I missed it).

From what I understand Stellarium tries to ping localhost and when that fails it bails out.

**The solution**: go to the mac's firewall preferences, and make sure that the 'stealth' mode is not enabled so that the Mac answers to ping (ICMP) requests. Once you've done that and checked in a terminal that 'ping localhost' actually works, then adding a telescope in Stellarium 0.18.2 works.

So it's just a change in the default firewall/security policy of MacOS which lead to the issue. It would be worth adding a debug output or dialog when that ping fails (there's already the TODO at the end of `TelescopeConfigurationDialog.cpp`)

Cheers, and thanks again to all developers for that fantastic software !
