### ISSUE TITLE
Black window (shader error) V1.0/Intel

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#2711]
### Expected Behaviour
useable scene

### Actual Behaviour
Black window.

Shader errors in `log.txt`

```
...
[ This is Stellarium 1.0 (v1.22.3) - https://stellarium.org/ ]
...
initializeGL
OpenGL supported version:  "4.3.0 - Build 20.19.15.5171"
Current Format:  QSurfaceFormat(version 4.3, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::CompatibilityProfile)
StelMainView::init
Detected: OpenGL "4.3"
Driver version string: "4.3.0 - Build 20.19.15.5171"
GL vendor is "Intel"
GL renderer is "Intel(R) HD Graphics 4600"
GL Shading Language version is "4.30 - Build 20.19.15.5171"
GLSL Version Number detected:  4.3
GLSL version is fine, we should not see a graphics problem.

...

QOpenGLShader::compile(Fragment): ERROR: 4:1: 'textureSampler' : syntax error syntax error


*** Problematic Fragment shader source code ***
#version 110
#ifdef GL_KHR_blend_equation_advanced
#extension GL_ARB_fragment_coord_conventions : enable
#extension GL_KHR_blend_equation_advanced : enable
#endif
#define lowp
#define mediump
#define highp
#line 1
varying highp vec2 uv;uniform sampler2DRect textureSampler;uniform bool swizzle;uniform highp float opacity;void main() {   highp vec4 tmpFragColor = texture2DRect(textureSampler,uv);   tmpFragColor.a *= opacity;   gl_FragColor = swizzle ? tmpFragColor.bgra : tmpFragColor;}
***
Could not link shader program:
 "ERROR: 4:1: 'textureSampler' : syntax error syntax error\n\n"
```

### System
* Stellarium version: 1.0 (stellarium-1.22.3-win64.exe)
* Operating system: Windows 10 Home 21H2
* Graphics Card: Intel Core i5-4570 with Intel(R) HD Graphics 4600 

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

### Edit

It seems this is just visible in Qt6.3 which we unfortunately used for this release. No problem with Qt6.4.

**Comment by 10110111** [comment]
Looks like this shader originates from Qt, because Stellarium itself doesn't have any mention of `sampler2DRect` in its codebase. In particular, a very similar shader exists in `qopengltextureblitter.cpp` in Qt 6.3.1, while there's no mention of `sampler2DRect` in Qt 5.15.2.

The chunk of Qt code that uses this shader source looks like this:
```cpp
if (supportsRectangleTarget())
    if (!d->buildProgram(QOpenGLTextureBlitterPrivate::TEXTURE_RECTANGLE, vertex_shader, fragment_shader_rectangle))
        return false;
```
So, the system does seem to declare support `GL_ARB_texture_rectangle` (because `supportsRectangleTarget()` returns `true`), but fails to actually support it.

I suspect this to be a bug in Intel GPU drivers.

**Comment by gzotti** [comment]
Thanks for the diagnosis. I had suspected the new dithering, but am just upgrading my dev environment on this PC.
I will try to find Intel driver updates then.

**Comment by gzotti** [comment]
I still have the latest Intel drivers, according to Intel's update tools :-(
Just tried 0.22.3: works on this Intel (OpenGL 4.3). Also SMS works. OK. This goes to the wiki/Common Problems, I am sure I am not the only one. 

I can try whether this was introduced by Qt6.3. IIRC Qt6.2 worked before summer. 

Related observations:

1)  the --mesa-mode and --angle-mode switches just don't work. Setting environment variables is the only solution.
2) Attempts to run SMS on GLES systems should be avoided. The error handling is OK, but we could use the available test (or duplicate code) isGLES to already hide the switch.

**Comment by 10110111** [comment]
> This goes to the wiki/Common Problems

At this point the best you can do is report the problem to Intel (preferably, reducing this to a small test app). Then there's hope that they'll fix it. Otherwise it seems unlikely that they'll even notice.

A worse solution (because it's a workaround) might be to use a patched Qt6 for Windows releases, where the patch would force `supportsRectangleTarget()` to return `false`.

**Comment by gzotti** [comment]
I just compiled with Qt6.4. Works. Maybe it's in the Qtbug archives for Qt6.3 and we were just very unlucky?
