### ISSUE TITLE
No planet images in 0.18.1

### ISSUE THREAD

**Issue by Teamonger** [Stellarium/stellarium#273]
They looked just fine in 0.16 on my Windows 7 machine.

**Comment by gzotti** [comment]
Let me guess: You are running ANGLE mode, for reasons not visible without the logfile which should accompany every such bug report. Your logfile (which you did not send) includes an error from the shader compiler. 

We have found the issue in  https://bugs.launchpad.net/stellarium/+bug/1731788 but no solution yet. The cleanest solution for you is to find correct drivers for your graphics card so that you run native OpenGL, not ANGLE. If your PC is from 2011 or later, this should work.

**Comment by guillaumechereau** [comment]
As Ruslan pointed out on the launchpad issue, this is most likely a bug due to those two lines in the shader:

    int index = int(mod( 64.0*random(vec4(gl_FragCoord.xyy,i)), 64.0));
    sum += offset_lookup(sTex, coord, poissonDisk[index], zbias);

Why was it working before though?  A change in ANGLE implementation in Qt maybe?

A possible fix could be to use a texture for the poissonDisk values instead of a uniform.

**Comment by gzotti** [comment]
I reinstalled Ubuntu Mate 16.04 LTS on My Raspberry Pi 3B, (still no 18.04 available :-(, upgraded to 16.04.5, and tried 0.18.2 from our PPS. On its current Mesa 18.0.5, it has OpenGL 3.0 and runs slow (llvmpipe), but planets are visible.

**Comment by gzotti** [comment]
Workaround seems to work in 0.18.3.
