### ISSUE TITLE
Could not load scientific star extra names file: stars/default/extra_name.fab

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium#2797]
### Expected Behaviour
No warning message.

### Actual Behaviour
Warning message at log.txt file

### Steps to reproduce
1. Start Stellarium as AppImage
2. Look log.txt file

### System
* Stellarium version: <Stellarium-1.1-RC3-x86_64.AppImage?>
* Operating system: <Kubuntu, 22.04>

### Logfile 
Loading scientific star names from "/usr/share/stellarium/stars/default/name.fab"
Loaded 6489 / 6489 scientific star names
WARNING: could not load scientific star extra names file: stars/default/extra_name.fab

Also another warning:
WARNING: could not load proper motion data file: stars/default/hip_pm.dat

**Comment by alex-w** [comment]
@ilkant do you have installed stellarium from the repository (standard or PPA)?

**Comment by ilkant** [comment]
Yes. I have installed Stellarium 0.20.4 from Kubuntu repository. And then I
downloaded AppImage 1.1 RC3.

ma 31. lokak. 2022 klo 7.42 Alexander V. Wolf ***@***.***)
kirjoitti:

**Comment by alex-w** [comment]
> Yes. I have installed Stellarium 0.20.4 from Kubuntu repository. And then I downloaded AppImage 1.1 RC3. 

Mixing data from different versions is not very good idea. Version 0.20.4 is doesn't have some data files and AppImage is checked standard paths at startup and it tried load the external data if path founded.

So, the solution is simple - please use AppImage or deb package only, not both together.

P.S. I'll close the issue as "Won't fix" because we cannot change architecture of an AppImage packages
