### ISSUE TITLE
[macOS] version numbers in 1.1 / 1.1.1 release broken

### ISSUE THREAD

**Issue by core-code** [Stellarium/stellarium#2805]
if you select the 1.1 (or is it 1.1.1 ?) release in the Finder, it claims to be version: `0.22.4-8cc1565`

you did forget to update the `CFBundleVersion` and `CFBundleShortVersionString` entries.

also, the fact that the new release is labeled as 1.1 in GitHub but as 1.1.1 in the filenames, doesn't exactly make things easier for downstream.

thanks!

**Comment by alex-w** [comment]
> if you select the 1.1 (or is it 1.1.1 ?) release in the Finder, it claims to be version: `0.22.4-8cc1565`

Well, it should be `1.22.4` for universal package, so, the version `0.22.4-8cc1565` is definitely wrong here. Plus we have public and inner versions now. The inner version using for splitting Qt5-based and Qt6-based binaries and public version for source code, because 0.22.4 and 1.22.4 had identical code base.

> you did forget to update the `CFBundleVersion` and `CFBundleShortVersionString` entries.

A both values generated automatically, but OK, I'll switch to use public versions for macOS bundles.

> also, the fact that the new release is labeled as 1.1 in GitHub but as 1.1.1 in the filenames, doesn't exactly make things easier for downstream.

Immediately after releasing version 1.1 we found critical issue in Qt5-based binaries and after adding hotfix for it (one line fix!) we're re-generate all binaries. So, files reflect one hotfix for version 1.1 now.

**Comment by core-code** [comment]
thanks

**Comment by core-code** [comment]
thanks i can confirm this is resolved now. new version is called "1.2" and also has the embedded version number "1.2"
