### ISSUE TITLE
It is abnormal to generate large screenshots

### ISSUE THREAD

**Issue by CaptBenjamin** [Stellarium/stellarium#2926]
### Expected Behaviour
Generate screenshots correctly and quickly.

### Actual Behaviour
When generating 16K (15360 * 8640, 72 dpi) pictures or 8K (7680 * 4320, 72 dpi) pictures, the program will not respond, and the generated pictures will be black.

### Steps to reproduce
Adjust the screenshot size to 16K (15360 * 8640, 72 dpi) or 8K (7680 * 4320, 72 dpi) in the settings, and then exit the settings. Press Ctrl+S to screenshot.

### System
* Stellarium version: stellarium-1.1.1-qt6-win64.exe
* Operating system: Microsoft Windows 11 Pro for Workstations, version 22H2 (OS Build 22621.963)
* Graphics Card: NVIDIA GeForce RTX 2080 Super, Game Ready driver 522.25
* Screen type (if applicable): 1920*1080

**Comment by gzotti** [comment]
Just tried 16384^2 on Win11 home with V1.1 and master and Geforce 3070Ti. Works. Cannot confirm.

**Comment by 10110111** [comment]
Just tried on Ubuntu 20.04 with scaling coefficient of 1.5, and... the resolution of output appears to be scaled. I.e. instead of, say, 4096×4096px I get 6144×6144. I suppose the same would happen on Windows, so the requested 15360px width will result in 23040, which is most likely beyond the capabilities of the GPU (`GL_MAX_TEXTURE_SIZE`).

What is your scaling factor?

**Comment by gzotti** [comment]
@CaptBenjamin In V1.1, you must use image type JPG because of a new internal size limit in Qt which I have fixed in master only yesterday. 

@10110111 Ah, that's interesting. The custom size should not depend on any scaling! That would be a bug.

**Comment by gzotti** [comment]
@alex-w , @10110111 when scaling is active, the actual OpenGL resolution is smaller than the native screen resolution. The screenshot logic seems to "correct" this by making a larger screenshot that fits the actual monitor resolution. What for?

At least in case of custom size, the user wants an image in the specified pixel dimensions. Making it larger contradicts the user's wishes and settings. Even worse, creating large screenshots may then exceed graphic hardware's capabilities which were queried when setting e.g. imgWidth in StelMainView.cpp L1675. 

This should really be fixed in a comprehensible way. Why do we need the scale factor here in the first place?

**Comment by 10110111** [comment]
The logic just needs a fix. In my view, the screenshot size should match the physical size of the main framebuffer, or, if custom size is specified, it should be taken as the physical size of the screenshot. The GUI should be rendered with the same scale factor as for the main window, not as it's done now (looking pixelated).
