### ISSUE TITLE
Consistent Versioning and Release Tags

### ISSUE THREAD

**Issue by abenson** [Stellarium/stellarium#2981]
**Is your feature request related to a problem? Please describe.**
Maintaining distribution packages for Stellarium has become difficult since the version numbering scheme change.  The inconsistent versioning versus tags (v1.1 tag and 1.1.1 tarball, v1.2 tag and v1.2 tarball) makes it difficult to use the release assets.

**Describe the solution you'd like**
Consistent tagging for the release versions.

**Describe alternatives you've considered**
For now, we've fallen back to the generated tarballs from Github.

**Comment by alex-w** [comment]
> v1.2 tag and v1.2 tarball

Where you see v1.2 tarball?

**Comment by abenson** [comment]
Under Assets on the [release/v1.2](https://github.com/Stellarium/stellarium/releases/tag/v1.2) page.

![image](https://user-images.githubusercontent.com/227317/211167131-8248cc20-ad98-4f9a-a82a-eb040ce49944.png)

The issue is with inconsistent versions for other releases, like [release/v1.1](https://github.com/Stellarium/stellarium/releases/tag/v1.1)

![image](https://user-images.githubusercontent.com/227317/211167156-caac27b0-9a5c-40f6-953b-d31ca08929a9.png)

**Comment by classabbyamp** [comment]
[release/v1.0](https://github.com/Stellarium/stellarium/releases/tag/v1.0) also has a mix of assets for 0.22.3, 1.22.3, and 1.0

![image](https://user-images.githubusercontent.com/5366828/211168344-84c57434-1c8f-4dab-ab6e-beccd74ebf7d.png)

**Comment by gzotti** [comment]
1.0 is a symbolic name for {0|1}.22.3. The 1 main number means Qt6-based.
1.1(.1) is a symbolic name for {0|1}.22.4. The 1 main number means Qt6-based. The third 1 is a patch indicator. 
1.2 is a symbolic name for {0|1}.22.5. The 1 main number means Qt6-based.

This is all documented in Release Notes and User Guide.

**Comment by abenson** [comment]
So when I package Stellarium, what version should I should specify for the package?

**Comment by abenson** [comment]
Also, you don't seem to be following that documentation.

![image](https://user-images.githubusercontent.com/227317/211169105-567fc1d6-fcf5-42f9-a335-51fc400e750c.png)

**Comment by alex-w** [comment]
1. We never used prefix “v” for tarballs
2. If you’re see the tags and tarballs names for all releases, then you can see similar “problem” for versions 0.10.6 and 1.1
3. Since series 0.12 we use one scheme for naming tags and tarballs (tarball 1.1.tar.gz was removed though)
4. We described the new scheme of versioning (inner and public versions), but who read docs? We got few reports about “inconsistent versions” and now all binary packages use public version in their names.
5. Your report is very strange, because by the fact you want to see tarball 1.2.1 for tag v1.2 or something else to get the “consistency of names”

**Comment by alex-w** [comment]
> So when I package Stellarium, what version should I should specify for the package?

We provide identical source code for building Stellarium with Qt5 and Qt6 and maintainers can provide binary packages for both versions of Qt in same distro. You can use public version with suffixes or inner version without suffixes for these packages.

**Comment by 10110111** [comment]
> Your report is very strange

I'd say the versioning scheme is really confusing. The very fact that there are a public version and two internal versions for each release is a mess. And, as I see from the milestones, the next version is apparently going to switch from 1.x to 23.x, which adds to this confusion.

**Comment by alex-w** [comment]
Seriously, I don’t see inconsistency names and tags for release 1.2 and why using asserts are difficult for void linux.

**Comment by abenson** [comment]
> We never used prefix “v” for tarballs

It's in the path to download the tarball.

> Since series 0.12 we use one scheme for naming tags and tarballs (tarball 1.1.tar.gz was removed though)

Right, so release v1.1 pointed to both `1.1.tar.gz` and `1.1.1.tar.gz`?

> We described the new scheme of versioning (inner and public versions), but who read docs? We got few reports about “inconsistent versions” and now all binary packages use public version in their names.

I'm just trying to keep the fetch URL consistent.

> Your report is very strange, because by the fact you want to see tarball 1.2.1 for tag v1.2 or something else to get the “consistency of names”

No, v1.2 can point to v1.2.  v1.1 shouldn't point to v1.1.1.   I'm expecting now that you'll have a v1.2 that is replaced with v1.2.1, and that's not what I want.

I want either v1.1 tag to point to 1.1, or you have a 1.1.1 tag to point to 1.1.1.

I think the end result is we're just not going to bother with using your tarballs, just pull archives from github, and pray they don't diverge in contents any anypoint.

**Comment by gzotti** [comment]
You are cordially invited to propose a better naming scheme given 

- 0 series built with Qt5 (since 0.13)
- 1 series built with Qt6 since 1.0, or betas like 1.22.2+ last summer)
- Feature set defines "outer" version like 1.0, 1.1, 1,2
- 1.0 was a milestone planned since ~2010. It has merely symbolic value. 
- addition of qt5 and at6 to package names may help people who don't read documentation more than the inner version numbers. Some ideas, as consistent and clear they seemed to us, turned out to be confusing to others. 
- We will switch to year.release number like many others.
- in all cases, version numbers increase.

**Comment by classabbyamp** [comment]
The main issue i see is not using git tags for patch versions, and instead either re-tagging or just replacing the release assets. if 1.1 is not the same as 1.1.1 there should be a different git tag for it.

The multiple internal version names for qt versions or whatever is just confusing icing on the cake

switching to `year.release.patch` is a totally fine versioning scheme if it's consistent throughout :)

**Comment by gzotti** [comment]
And how would you deal with the Qt5/Qt6 problem?

**Comment by classabbyamp** [comment]
the -qt5/-qt6 suffixes on the windows builds seems fine, and is very clear

**Comment by alex-w** [comment]
> the -qt5/-qt6 suffixes on the windows builds seems fine, and is very clear. because those don't change the functionality of the program aside from the version of qt they use, there's no need to include that info in tags

But the functionality of the program is slightly different for various versions of Qt.

**Comment by alex-w** [comment]
> > We never used prefix “v” for tarballs
> It's in the path to download the tarball.

We always used prefix "v" for tags and never used prefixes for tarballs since version 0.12.7.

> > Since series 0.12 we use one scheme for naming tags and tarballs (tarball 1.1.tar.gz was removed though)
> Right, so release v1.1 pointed to both `1.1.tar.gz` and `1.1.1.tar.gz`?

Yes by the fact. The `1.1.1.tar.gz` is re-packed `1.1.tar.gz` with one-line patch (it was critical for linux distros)

> > We described the new scheme of versioning (inner and public versions), but who read docs? We got few reports about “inconsistent versions” and now all binary packages use public version in their names. 
> I'm just trying to keep the fetch URL consistent.

In version 1.2 the fetch URL is follow the standard naming scheme - as many years before. 

> > Your report is very strange, because by the fact you want to see tarball 1.2.1 for tag v1.2 or something else to get the “consistency of names”
> 
> No, v1.2 can point to v1.2. v1.1 shouldn't point to v1.1.1. I'm expecting now that you'll have a v1.2 that is replaced with v1.2.1, and that's not what I want.
> 
> I want either v1.1 tag to point to 1.1, or you have a 1.1.1 tag to point to 1.1.1.

Nice! If this is critical for you as for maintainer then why you didn't open the bug report immediately after 1.1 release? 

> I think the end result is we're just not going to bother with using your tarballs, just pull archives from github, and pray they don't diverge in contents any anypoint.

Version 1.2 is follow our standard scheme for naming tags and tarballs, which were followed at least last 5 years. In few last years we have the once exception from this scheme - release 1.1. Why that scheme is difficult now - I don't know and I don't understand it. We provide the standard tarballs of source code for each releases and how maintainers using or not using these tarballs is not our problem.

> > Seriously, I don’t see inconsistency names and tags for release 1.2 and why using asserts are difficult for void linux. 
> I don't know what that means. You mean just use conditional URLs for fetching depending on if the tag matches the actual version?

Sorry, no comments.
