### ISSUE TITLE
CMake Error in src/CMakeLists.txt:   Imported target "QXlsx::QXlsx" includes non-existent path

### ISSUE THREAD

**Issue by carlosal1015** [Stellarium/stellarium#3132]
### Expected Behaviour

cmake configure and create a build directory for compile stellarium.

### Actual Behaviour

When [`qxlsx-qt6`](https://archlinux.org/packages/community/x86_64/qxlsx-qt6/files) is installed on the system, we can not configure the build directory because is not found `/usr/include/QXlsx`, but exists `/usr/include/QXlsxQt6`.

### Steps to reproduce

```
$ curl -LO https://github.com/Stellarium/stellarium/releases/download/v23.1/stellarium-23.1.tar.gz
$ tar -xvf stellarium-23.1.tar.gz
$ cmake -S stellarium-23.1 -B build -DENABLE_XLSX=1
```

### System
* Stellarium version: 23.1
* Operating system: Arch Linux Rolling Release
* Graphics Card: No apply
* Screen type (if applicable): No apply

### Logfile 

[log.txt](https://github.com/Stellarium/stellarium/files/11079848/log.txt)

**Comment by alex-w** [comment]
Headers in the original library is expected in directory `/usr/include/QXlsx` (https://github.com/QtExcel/QXlsx/blob/master/HowToSetProject-cmake.md)

If you want to use source dir as it In the Arch Linux, then you can re-define `SOURCE_SUBDIR` parameter for `CPMAddPackage` command (see https://github.com/Stellarium/stellarium/blob/71fbf1f3168eb2ba01ac95f12b9c7bcf7dded0aa/CMakeLists.txt#LL820C19-L820C19): `SOURCE_SUBDIR QXlsx` -> `SOURCE_SUBDIR QXlsxQt${QT_VERSION_MAJOR}`

**Comment by alex-w** [comment]
According to [pkgs.org](https://pkgs.org/search/?q=Qxlsx) website only Arch Linux uses _non-standard_ path for `include` directory of Qxlsx

**Comment by carlosal1015** [comment]
> Headers in the original library is expected in directory `/usr/include/QXlsx` ([see](https://github.com/QtExcel/QXlsx/blob/master/HowToSetProject-cmake.md?rgh-link-date=2023-03-27T15%3A12%3A06Z))
> 
> If you want to use source directory as it in the Arch Linux, then you can re-define `SOURCE_SUBDIR` parameter for `CPMAddPackage` command ([see](https://github.com/Stellarium/stellarium/blob/71fbf1f3168eb2ba01ac95f12b9c7bcf7dded0aa/CMakeLists.txt#LL820C19-L820C19)): `SOURCE_SUBDIR QXlsx` -> `SOURCE_SUBDIR QXlsxQt${QT_VERSION_MAJOR}`

Thanks for the hint.
I will take a look later for make a patch like [this](https://github.com/archlinux/svntogit-community/blob/packages/labplot/trunk/find-qxlsx.patch) used for labplot. In the future, maybe having something like FindQXlsx.cmake will be a nice workaround for detect qt5 or qt6.

**Comment by DarthGandalf** [comment]
> In the future, maybe having something like [FindQXlsx.cmake](https://github.com/KDE/labplot/blob/master/cmake/FindQXlsx.cmake) will be a nice workaround for detect qt5 or qt6.

No, the latest QXlsx versions install separate cmake files for qt5 and qt6: e.g. /usr/lib64/cmake/QXlsxQt5/QXlsxQt5Config.cmake which makes it work for `find_package(QXlsxQt5)`, similar for Qt6

> According to [pkgs.org](https://pkgs.org/search/?q=Qxlsx) website only Arch Linux uses non-standard path for include directory of Qxlsx

The Arch package patches the install dir to install 2 copies of the same headers: https://github.com/archlinux/svntogit-community/blob/463e8ac91659f7b332c00e81e27e189528650ab7/trunk/coinstallability.patch#L10

In that setup, the target `QXlsx::QXlsx` is supposed to refer to `/usr/include/QXlsxQt5`, not `/usr/include/QXlsxQt`. But the Arch package didn't update the target. They either should install headers once instead of twice, or to also update the target.

**Comment by axd1967** [comment]
(related to [vendor_branching](https://github.com/Stellarium/stellarium/issues?q=vendor_branching))

**Comment by carlosal1015** [comment]
> Hello @carlosal1015!
> 
> Please check the latest stable version of Stellarium: [Stellarium/stellarium/releases/latest](https://github.com/Stellarium/stellarium/releases/latest)

Not working yet.

**Comment by DarthGandalf** [comment]
@alex-w 01786247149f1e2166c18ce1237ee88a1815195c actually doesn't affect this issue. You updated the version which Stellarium build system installs automatically, but the issue here is caused by the system package on Arch, which is inconsistent, not the one downloaded by stellarium itself when the system package is not found. Note that upstream 1.4.6 is also inconsistent itself (fixed by https://github.com/QtExcel/QXlsx/commit/8c3e6633e3c901bc5a5cd477383421b0980dcd26 which will probably be in 1.4.7) but it's broken only when used as system package - your update of QXlsx version gladly didn't break anything in Stellarium.

@carlosal1015 Stellarium upstream cannot fix the issue with bad QXlsx package in Arch. Please complain to Arch package maintainers instead.

**Comment by DarthGandalf** [comment]
@carlosal1015 what you can do is to force Stellarium's cmake to ignore your broken Arch package, e.g. by setting [CPM_DOWNLOAD_ALL cmake option](https://github.com/cpm-cmake/CPM.cmake#cpm_download_all). Then it will download the working version of QXlsx.

But you still should complain to Arch maintainers about the broken package.

**Comment by carlosal1015** [comment]
Now qxlsx-qt6 works out of the box with stellarium 23.4😄
