### ISSUE TITLE
Mis-information (Database Error): Abell 39

### ISSUE THREAD

**Issue by rlong44** [Stellarium/stellarium#3330]
When searching Deep Sky Object Abell 39, Stellarium 23.2 (Windows) yields a galaxy cluster in constellation Cetus.  

But Abell 39 is a planetary nebula in constellation Hercules.  (Database error).

(Abell 39 is also cataloged as ACO 39 or ARO 180, but these are most often cross-referenced).

**Comment by alex-w** [comment]
@rlong44 please check the full name of used Abell catalog

**Comment by rlong44** [comment]
"@rlong44 please check the full name of used Abell catalog"
Abell 39 is the 39th entry in a catalog of large nebulae discovered by George Abell in 1966.  'Abell 39' is cited widely for identifying this nebula.  


"This is not a bug! This is a feature..."
Any error, typo or what-have-you, requires attention (same as any code-error).  Erroneous information can be very confusing.

**Comment by alex-w** [comment]
> Abell 39 is the 39th entry in a catalog of large nebulae discovered by George Abell in 1966. 'Abell 39' is cited widely for identifying this nebula.

We use "A Catalog of Rich Clusters of Galaxies" by Abell et.al. and this catalog has designation "Abell" (and "ACO" for compatibility to the SIMBAD). Please explain why you expected to see planetary nebulae in catalog of rich galaxies. 

>  Any error, typo or what-have-you, requires attention (same as any code-error). Erroneous information can be very confusing.

This is correct sentence, but not correct application.

**Comment by alex-w** [comment]
> Abell 39 is also cataloged as ACO 39 or ARO 180, but these are most often cross-referenced

This is partially wrong.

Abell 39 = ACO 39 != ARO 180, see: http://simbad.u-strasbg.fr/simbad/sim-id?Ident=abell+39&submit=submit+id

But PN ARO 180 = PN A66 39, see: http://simbad.u-strasbg.fr/simbad/sim-id?Ident=PN+ARO+180&submit=submit+id

George Abell are father of many catalogs and all of them has original designation "Abell". Yes, amateurs known only one Abell's catalog - catalog of planetary nebulae from 1966 (why not other Abell's catalogues of planetary nebulae?), but "expected catalog" is not same as "used catalog."

**Comment by gzotti** [comment]
This and at least one previous similar issue, and indeed frequent reproduction of images of "PN Abell XY" in popular media indicate that we probably need to include yet another catalog: "Abell (A66)".

**Comment by rlong44** [comment]
> > Abell 39 is also cataloged as ACO 39 or ARO 180, but these are most often cross-referenced
> 
> This is partially wrong.
> 
> Abell 39 = ACO 39 != ARO 180, see: http://simbad.u-strasbg.fr/simbad/sim-id?Ident=abell+39&submit=submit+id
> 
> But PN ARO 180 = PN A66 39, see: http://simbad.u-strasbg.fr/simbad/sim-id?Ident=PN+ARO+180&submit=submit+id
> 
> George Abell are father of many catalogs and all of them has original designation "Abell". Yes, amateurs known only one Abell's catalog - catalog of planetary nebulae from 1966 (why not other Abell's catalogues of planetary nebulae?), but "expected catalog" is not same as "used catalog."



It appears you are quite involved and occupied with object catalogs, including things that have not been settled yet.  

I am coming from a BROADER perspective dealing mostly with Messier, NGC, and IC objects.  Something identified by 'Abell' may incur cross-references to other catalogs, but in this instance, Abell 39 is too-widely cited for a planetary nebula.

The use of Abell 39 for a planetary nebula is in hard-copy books (e.g., Stars and Planets, DK Publishing, 2019), the well-known app 'SkySafari', and online Wikipedia.  If you keep pursuing online resources, it will continue to identify Abell 39 as a planetary nebula.

Abell 39 is too-widely cited as a planetary nebula (16h 28m 30s, +27 51' 24").

**Comment by alex-w** [comment]
> I am coming from a BROADER perspective dealing mostly with Messier, NGC, and IC objects. Something identified by 'Abell' may incur cross-references to other catalogs, but in this instance, Abell 39 is too-widely cited for a planetary nebula.
>
> The use of Abell 39 for a planetary nebula is in hard-copy books (e.g., Stars and Planets, DK Publishing, 2019), the well-known app 'SkySafari', and online Wikipedia. If you keep pursuing online resources, it will continue to identify Abell 39 as a planetary nebula.

Well, from your first message I see that these resources has had bad cross identification for that planetary nebula. The 'Abell 39' is too-widely cited for a planetary nebula in books and media for amateur astronomers, but if you will use books and online resources for professional astronomers then you will see that 'Abell 39' is too-widely cited for a cluster of galaxies.

> Abell 39 is too-widely cited as a planetary nebula (16h 28m 30s, +27 51' 24").

We did wrote in the User Guide and and the planetarium, that we use Abell's catalog of rich clusters of galaxies and this report of course is not a bug by this reason.  The really sad news here that designation 'Abell 39' by the fact is used for 6 different objects and in common case we really can't guess which object user exactly want to see when he typing word 'Abell' in Search Tool. Currently we using designation 'Abell' for same objects as in SIMBAD.

> This and at least one previous similar issue, and indeed frequent reproduction of images of "PN Abell XY" in popular media indicate that we probably need to include yet another catalog: "Abell (A66)".

Yes, we can (I hope users will never ask for other 4 Abell's catalogs :) ), but in any way we'll get reports about "wrong data" for 'Abell XX' because users will, of course, no read about standard designations 'PN A66 XX' for planetary nebulae in planetarium/SUG.  The changing 'Abell' to using for planetary nebulae by default  - well, we'll got complains for "same issues" from professionals.

**Comment by gzotti** [comment]
Question of context, indeed. I can assume that also those professionals who regularly deal with PNs would colloquially use "Abell 39" instead of "Abell A66 39". However, being a generally useful tool, the full name in Stellarium would always have to include the actual catalog. A search for "Abell 39" would have to find and list both, "Abell ACO 39" and "Abell A66 39". (And if his other catalogs are in wide use, add those as well...)
