### ISSUE TITLE
 frames

### ISSUE THREAD

**Issue by HIP37279** [Stellarium/stellarium#3561]
Firstly, my monitor supports 90 frames per second. After I installed the latest version of stellarium 23.3, the software opened at 90 frames per second. However, as soon as the "load TLE file" operation started, the frame rate dropped below 60 frames per second. My CPU is AMD Ryzen 7 6800H, and my GPU is integrated. According to the task manager, the stellarium software is not using a high percentage of GPU or CPU power, not even half. Therefore, I believe it may be an optimization issue with stellarium on AMD Ryzen chips.

**Comment by gzotti** [comment]
As with many other interactive graphics software titles, there is one main thread and several subthreads. Unfortunately, identifying tasks that could be performed in other threads instead of the main thread is not too easy. In this respect, a 46-core machine will currently not be faster than e.g. a 4-core at the same clock rate. Frame rate depends mostly on number of loaded solar system objects, satellites, lines (grids, orbits/trails, constellations/asterisms/borders) and screen size (better: pixel resolution).

**Comment by HIP37279** [comment]
> 与许多其他交互式图形软件标题一样，有一个主线程和几个子线程。不幸的是，识别可以在其他线程而不是主线程中执行的任务并不太容易。在这方面，在相同的时钟频率下，46 核机器目前不会比 4 核机器更快。帧速率主要取决于加载的太阳系天体、卫星、线（网格、轨道/轨迹、星座/星群/边界）的数量和屏幕尺寸（更好：像素分辨率）。

**Comment by HIP37279** [comment]
> 与许多其他交互式图形软件标题一样，有一个主线程和几个子线程。不幸的是，识别可以在其他线程而不是主线程中执行的任务并不太容易。在这方面，在相同的时钟频率下，46 核机器目前不会比 4 核机器更快。帧速率主要取决于加载的太阳系天体、卫星、线（网格、轨道/轨迹、星座/星群/边界）的数量和屏幕尺寸（更好：像素分辨率）。

So how can I make the Stellarium software run at a higher frame rate on my computer

**Comment by gzotti** [comment]
Use less Solar System objects, no grids, lines, orbits, trails, satellites, add-on plugins, and a very small screen (1280x800?). If you can assign a few overclocked Ryzen core to one process, it could speed up the program. But I don't know how to selectively overclock single CPU cores. If you are into programming, study the code, identify subtasks to run in other threads, and send us a pull request.

**Comment by HIP37279** [comment]
> 使用更少的太阳系对象，没有网格、线条、轨道、轨迹、卫星、附加插件和非常小的屏幕（1280x800？如果您可以将一些超频的 Ryzen 核心分配给一个进程，则可以加快程序速度。但是我不知道如何有选择地超频单个CPU内核。如果您喜欢编程，请研究代码，确定要在其他线程中运行的子任务，然后向我们发送拉取请求。

thanks so much!I will try it
