### ISSUE TITLE
Lines on screen after enabling Telescope control

### ISSUE THREAD

**Issue by bottletopburly** [Stellarium/stellarium#3579]
< stellarium v 23.4 , nvidea gtx 1060 graphics card , driver 546.33, core i5 processor 
updated stellarium to v 23.4 all working fine until i went to plugins >telescope control>enabled load on startup , closed stellarium and restarted stellarium ,upon starting lines across screen , tried uninstalling stellarium and re installed , updated gtx 1060 6gb graphic card to latest driver ,problem still persists ,noting that after re installing everything fine until i go to plugins>telescope control>load on startup enabled and close stellarium ,lines on screen after restarting stellarium 
![STELLARIUM (1)](https://github.com/Stellarium/stellarium/assets/37311398/574994f3-7cf8-4f63-bc32-eee267b6dd72)
[log.txt](https://github.com/Stellarium/stellarium/files/13805675/log.txt)

regards Dave 

If the bug still persists, give your issue a clear, short title, delete text above down to and including this line and fill in:
-->

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
Are you sure you need Mesa mode?

**Comment by bottletopburly** [comment]
Hi i wasn't aware i was in mesa mode ? just checked as i was using a task bar icon shortcut and yes it seems to only show lines using  mesa mode deleted icon and rebooted using non mesa mode and all works as should i have no idea how i used the mesa mode shortcut originallly ,sorry for wasting your time but that did seem to be the culprit .

Regards Dave

**Comment by 10110111** [comment]
@gzotti The problem of using the wrong shortcut did appear before. I guess it's because of text elision when the shortcut is not selected. Maybe the shortcut should only be present in the Start Menu but not on the desktop (and same for all the other kludgy shortcuts)?

**Comment by gzotti** [comment]
I never place icons onto the desktop, so I don't even know how they look like. Is the "(Mesa Mode)" trimmed away?  :-o. 

Do we need to show, mandatorily, a few lines of "what to do after installation":

1. Test OpenGL mode. If it works, remove MESA (Qt5: and ANGLE) shortcuts.
2. (Qt5: Test ANGLE mode: If it works, delete OpenGL and MESA mode shortcuts)
3. Test MESA mode. If it works, and OpenGL did not work, remove OpenGL shortcut. 
4. If nothing works, uninstall. (Qt6: Try a Qt5-based build)
5. Qt6: If telescope plugin has issues with your telescope, run Qt5-based build.

This in addition to the User Guide, Release Notes and Wiki/FAQ. Do we really need to do that? And: Who would read and follow such instructions, ever? If we write too much, nobody reads it, and users complain. If we don't write enough, users complain. You never satisfy all...

**Comment by 10110111** [comment]
> I never place icons onto the desktop, so I don't even know how they look like. Is the "(Mesa Mode)" trimmed away?

I don't have Windows, so can't check. But I seem to have seen such a behavior in some desktop, not sure on which OS.

> Do we need to show, mandatorily, a few lines of "what to do after installation"

Nobody would read this. You want the app to follow the principle of least astonishment, and multiple shortcuts have long made me feel uncomfortable whenever I had to use Stellarium on Windows. There should be only one shortcut on the desktop, all the others being available, but with a small additional effort (namely, navigation/search in the Start Menu, with maybe Send to→Destkop when needed).

**Comment by alex-w** [comment]
> I never place icons onto the desktop, so I don't even know how they look like. Is the "(Mesa Mode)" trimmed away? :-o.

He shouldn't be trimmed!

> Do we need to show, mandatorily, a few lines of "what to do after installation":
> 
> 1. Test OpenGL mode. If it works, remove MESA (Qt5: and ANGLE) shortcuts.
> 2. (Qt5: Test ANGLE mode: If it works, delete OpenGL and MESA mode shortcuts)
> 3. Test MESA mode. If it works, and OpenGL did not work, remove OpenGL shortcut.
> 4. If nothing works, uninstall. (Qt6: Try a Qt5-based build)
> 5. Qt6: If telescope plugin has issues with your telescope, run Qt5-based build.

This scenario is not applicable by technical reasons - we cannot propose Qt5- and Qt6-based package in same installation package + you want to see a `launcher.exe` by the fact.

A many shortcuts comed in Qt5-based age because users can't be editing a shortcuts (a low quality knowledge in IT). Same problem for shortcuts in (common|user) desktop. According to changes in Qt6 I propose remove all extra shortcuts from desktop (done!) and from Programs section.


> This in addition to the User Guide, Release Notes and Wiki/FAQ. Do we really need to do that? And: Who would read and follow such instructions, ever? If we write too much, nobody reads it, and users complain. If we don't write enough, users complain. You never satisfy all...

I think the SUG/FAQ should contains notification how run Stellarium in specific modes in Windows (single buffer, spout, MESA, debug) via editing of shortcuts or CLI.

**Comment by gzotti** [comment]
> > I never place icons onto the desktop, so I don't even know how they look like. Is the "(Mesa Mode)" trimmed away? :-o.
> 
> He shouldn't be trimmed!
> 
> > Do we need to show, mandatorily, a few lines of "what to do after installation":
> > 
> > 1. Test OpenGL mode. If it works, remove MESA (Qt5: and ANGLE) shortcuts.
> > 2. (Qt5: Test ANGLE mode: If it works, delete OpenGL and MESA mode shortcuts)
> > 3. Test MESA mode. If it works, and OpenGL did not work, remove OpenGL shortcut.
> > 4. If nothing works, uninstall. (Qt6: Try a Qt5-based build)
> > 5. Qt6: If telescope plugin has issues with your telescope, run Qt5-based build.
> 
> This scenario is not applicable by technical reasons - we cannot propose Qt5- and Qt6-based package in same installation package + you want to see a `launcher.exe` by the fact.

No, it would just mean different instructions per Qt version. However, the Qt blacklisting should fall back to ANGLE/Mesa in most cases of bad hardware, so the extra buttons were indeed questionable. 


> A many shortcuts comed in Qt5-based age because users can't be editing a shortcuts (a low quality knowledge in IT). Same problem for shortcuts in (common|user) desktop. According to changes in Qt6 I propose remove all extra shortcuts from desktop (done!) and from Programs section.

The links in the Program section (menu) are important, in case the blacklisting mechanism failed and users see black screens etc. What I am less sure about is the single-buffer requirement. This should probably be recommended as environment variable, because as German-keyboard user with Geforce I meanwhile need envvar `STEL_OPTS=--single-buffer -platform windows:altgr,fontengine=freetype`, so, actually 3 independent extra options (2 of which must be combined for giving Qt platform options).
The problem is that most users know nothing about environment variables, and instructing them to set these may overwhelm them with "too much programming". Not sure whether we should add these options into the main config dialog with "requires restarting" note, and parse them in the earliest initialisation phase which calls Stellarium after setting envvars. 

> > This in addition to the User Guide, Release Notes and Wiki/FAQ. Do we really need to do that? And: Who would read and follow such instructions, ever? If we write too much, nobody reads it, and users complain. If we don't write enough, users complain. You never satisfy all...
> 
> I think the SUG/FAQ should contains notification how run Stellarium in specific modes in Windows (single buffer, spout, MESA, debug) via editing of shortcuts or CLI.

Under which circumstances do we need the single-buffer setting? It is required to see the tooltips in full-screen operation on my Geforce Windows PC.  AFAIK the double buffering avoids screen tearing, so should be preferred. Is this a Geforce-specific requirement? Or only for some of them? Or even only some driver versions? I have no recent Intel or AMD to check.

CLI options are uncommon for Windows where users click on icons to launch programs. And editing program shortcuts is made more difficult from version to version, so again "too complicated" for less technically inclined users. 

If some things need permanent description, it should go into the SUG. The FAQ are temporary answers until the relevant info is placed in the SUG for use in the next release, or describe temporary workarounds for issues in specific versions.

**Comment by gzotti** [comment]
OK, also Intel. Does double-buffering work flawlessly on AMD? Else we should just make single-buffer the default on Windows, and add double-buffering as extra option (to allow trying when drivers get fixed by manufacturers). Or find out why it is flawed. (Some OpenGL command missing somewhere?) Does double buffering work flawlessly on Linux/Mac?

Yes, we have config.ini for such extras. A text file besides the EXE would require enhanced privileges, no-go for many installations.  But it may be useful to add those options (omitting of which doesn't have immediately visible effects) in the GUI settings dialog. Those settings should be stored immediately. On init, the CLI parser sets according Envvars. And again, STEL_OPTS could override them.

**Comment by 10110111** [comment]
> OK, also Intel

I've never seen any problem with this on NVidia, only on Intel.

> Does double buffering work flawlessly on Linux/Mac?

No problems on Linux.

> (Some OpenGL command missing somewhere?)

No, just some broken drivers I think. Actually, it may be related to what Windows' fullscreen mode is: it's likely some kind of a game mode where you're not supposed to pop any windows. Have you seen how fullscreen games get immediately minimized when you press WinLogo key (that opens Start Menu)?

> But it may be useful to add those options (omitting of which doesn't have immediately visible effects) in the GUI settings dialog.

The problem with this is that the GUI may be invisible due to graphics issues we're trying to fix with this GUI.

**Comment by gzotti** [comment]
> No, just some broken drivers I think. Actually, it may be related to what Windows' fullscreen mode is: it's likely some kind of a game mode where you're not supposed to pop any windows. Have you seen how fullscreen games get immediately minimized when you press WinLogo key (that opens Start Menu)?

Are the tooltips "windows" in the strict API sense as "window"?  On starting Stellarium, the Geforce driver shows its own info popup about using AltZ for its own game overlay for 2 seconds. Hmm, only in Double-buffer mode! Also for other GPU-heavy programs. I must admit, I have no recreational game on board to try. Pressing the Windows key while running Stellarium shows task bar and start menu popup on top of Stellarium's fullscreen view (does not minimize for me!).

The "no tooltip on Geforce in full-screen mode" annoyed me since my W7/M580GTX. In those years, also the modal system dialogs (colors, file paths) were hidden behind the main window which was more than annoying. At least single-buffering was a partial improvement. Or running in windowed mode.

> The problem with this is that the GUI may be invisible due to the graphics issues we're trying to fix with this GUI.

I am specifically discussing double buffering (for pop-up tooltips), AltGr key (for using `{[]}|~\` keys on international keyboards) and the better font engine. None are crucial in many cases, but some like the missing keys are silly "doesn't work for me" issues. Of course, mitigations for complete failure (black screen, invisible display, ...) must be documented/fixed elsewhere.

**Comment by 10110111** [comment]
> Are the tooltips "windows" in the strict API sense as "window"?

Yes. Just as any other window, be it toplevel or child, a tooltip is created using the `CreateWindowEx` function.

> In those years, also the modal system dialogs (colors, file paths) were hidden behind the main window which was more than annoying.

This should now be fixed by 2d680dec4f9784ba216160c9acd9f161d2108e7a.

> I am specifically discussing double buffering (for pop-up tooltips), AltGr key (for using {[]}|~\ keys on international keyboards) and the better font engine.

OK, this does make sense. These options could be placed in `config.ini` under a section like `[Tweaks]` with defaults depending on platform. In fact, the same section could be used for OpenGL kludges, these just would normally be edited manually (though a GUI option for them could also be useful). Then the actual command-line options would override these settings.
