### ISSUE TITLE
Meteor shower issue

### ISSUE THREAD

**Issue by TheSuggestionGuy** [Stellarium/stellarium#3616]
So, go to, somewhere in Africa, like Nouakchott (it's in UTC time so you can understand, this applies to every location) and remove the ground, and click on the Quadrantids, then go to the second before new year's 2025, then, you can see the meteor showers color is orange, and it has info saying: ZHRmax, Current ZHR, and Local Hourly Rate. Then on midnight of 2025, the meteor shower color becomes white, then Current ZHR, and Local Hourly Rate disappears, and ZHRmax becomes ZHRmax variable, and it's instead in a range. and it applies to all meteor showers, in all locations. so please fix this.

_Originally posted by @TheSuggestionGuy in https://github.com/Stellarium/stellarium/discussions/3615_

**Comment by worachate001** [comment]
Recently, we just made a modification to this plugin that changes behavior (see #3549). However, there is a remaining bug explained in this issue. It happens for meteor showers that start in December and end in January/February. In this example, near the end of 2024, the shower shouldn't use 2024 data and must switch to 'generic' one (because we don't have 2025 prediction yet for Quadrantids).

I will take a closer look to find a way to fix.
