### ISSUE TITLE
Extreme slowdown on Linux with Nouveau since v23.1

### ISSUE THREAD

**Issue by tanelihuuskonen** [Stellarium/stellarium#3642]
### Expected Behaviour
Reasonable framerate (double digits)

### Actual Behaviour
Less than one frame per MINUTE on a fairly new and efficient machine

### Steps to reproduce
Start Stellarium on a Linux machine with the Nouveau graphics driver (tested on two different machines), and wait

### System
* Stellarium version: 23.1 through 24.1
* Operating system: Gentoo Linux
* Graphics Card: Nvidia GeForce RTX 3080 Ti; driver Nouveau 1.4.0 20120801

[log.txt](https://github.com/Stellarium/stellarium/files/14397591/log.txt)

I ran a git bisect to locate the commit that caused the issue. It was commit 7fa8015902 on 2023-02-07, switching to fragment-shader-based direction computation. I understand this may well be a bug in Nouveau, but still, I'd like to have a setting to work around it. A commented-out entry in the LaTeX source of the User's Guide suggests there has been something similar in the past, with the ability to set flag_use_ext_framebuffer_object to false to mitigate a bug in a graphics driver.

**Comment by gzotti** [comment]
The nouveau driver has never worked for me. Maybe you can force it somehow to play OpenGL3.0, not 3.3, so it does not activate this code?

**Comment by 10110111** [comment]
In the recent weekly build there should be an option `--low-graphics`, which should help. Note though that Nouveau driver has been broken for all its life and will likely continue being broken if NVidia doesn't start supporting it as Intel supports their GPU drivers (which are also far from ideal, but still orders of magnitude better than Nouveau).

Moreover, you're using one of the (relatively) recent NVidia GPUs, so not only will it have more problems than older ones with Nouveau (because reverse engineering takes years), but generally it makes no sense to use such a bad driver with such a high-end GPU (and even less sense to use low graphics mode in OpenGL software).

So, if you are not too heavily into FOSS purity, you should use `nvidia` proprietary driver whenever it's compatible with your platform.

**Comment by tanelihuuskonen** [comment]
Thanks for the suggestions. I like to use FOSS whenever it works OK, and nouveau was usually more than sufficient for my needs; I don't do anything graphics-intensive. (I got my current machine as a gift.) I installed the proprietary driver, and now Stellarium works fine.

**Comment by gzotti** [comment]
I have added this to the FAQ.
