### ISSUE TITLE
Some sky cultures don't install reference.fab

### ISSUE THREAD

**Issue by 10110111** [Stellarium/stellarium#3680]
I find the following list of reference files in the sky cultures source directory:
```
$ find skycultures/ -name reference.fab | sed 's@.*/skycultures/@@' | sort
anutan/reference.fab
arabic_arabian_peninsula/reference.fab
arabic_indigenous/reference.fab
arabic_lunar_mansions/reference.fab
chinese/reference.fab
egyptian_dendera/reference.fab
greek_almagest/reference.fab
greek_farnese/reference.fab
modern_chinese/reference.fab
modern_iau/reference.fab
modern/reference.fab
modern_rey/reference.fab
modern_sternenkarten/reference.fab
seri/reference.fab
tibetan/reference.fab
tikuna/reference.fab
```
And here's the list of the installed ones:
```
$ find ~/opt/stellarium/share/stellarium/skycultures/ -name reference.fab | sed 's@.*/skycultures/@@' | sort
arabic_arabian_peninsula/reference.fab
arabic_indigenous/reference.fab
arabic_lunar_mansions/reference.fab
egyptian_dendera/reference.fab
greek_almagest/reference.fab
greek_farnese/reference.fab
modern_chinese/reference.fab
modern_iau/reference.fab
modern/reference.fab
modern_rey/reference.fab
seri/reference.fab
tibetan/reference.fab
```
As you can see, `anutan`, `chinese`, `tikuna` don't have the file installed while having it in the source. (I'm ignoring `modern_sternkarten` which is excluded from installation completely.)

I don't know if this was on purpose, but it must be noted that these files do have a user-visible effect: the references are listed in the sky culture description.

Interestingly, `anutan` and `chinese` incorporate the references in their descriptions, but apparently these references diverged a bit from the `reference.fab` files. And `tikuna` doesn't have them visible at all.

**Comment by gzotti** [comment]
reference.fab is a rather new file and is optional. At some point, with star names from tens of books and centuries collected, we saw it as requirement to provide source info for the (then) "western" (now "modern") skyculture, to be placed next to the actual star names, so that maybe later we can even provide such data in the InfoString, or at least for readers of the source files. Another long-lasting idea of mine is allowing selection of references as user preference, which would allow suppressing obscure sources for star or too fancy DSO names. For SCs with just 1-2 references, the file may not be needed, and refs can be given in the description. Of course, if there is a reference.fab, it should be shown in the description and taken away from that file.

**Comment by alex-w** [comment]
I’ll re-check cmake scripts - probably it’s my fault

**Comment by 10110111** [comment]
@alex-w I've already started this. This needs some tweaks to descriptions too, which I've already partially done.
