### ISSUE TITLE
Heliacal

### ISSUE THREAD

**Issue by Mithras27** [Stellarium/stellarium#3724]

**Comment by gzotti** [comment]
Please carefully read Appendix F and install JPL DE441 before proceeding. Your sun is off.
Then use the Observability plugin (section 16.3) and cross-check its results with your other methods of deriving Heliacal dates.

**Comment by gzotti** [comment]
A simulation is at best as good as the models it is based upon. "Sun is off" because you are using VSOP87 in 10.000BC. It is recommended down to 4000BC. Switch on ecliptic display to see what's happening then. (Where the Sun is, and where the ecliptic is.) I don't want to repeat myself, Appendix F.3 tells you what to do. Some more insight is in our JSA 6.2 paper.

While the Observability plugin may work also in that remote past, I cannot give any guarantee. Therefore I recommend checking ours with other results.
