### ISSUE TITLE
Hiding buttons

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#3830]
By the way, 
I want hide buttons that are not normally used, but this is not possible.

"Switch between equatorial and azimuthal mount": I have only alt-azimuthal mount.
"Constellation art": It is not included in the sky culture I always use.
"Equatorial grid": I usually use J2000.

Of course, some will need it.

thank you.

_Originally posted by @3domennotry in https://github.com/Stellarium/stellarium/issues/3827#issuecomment-2257242054_

**Comment by 3domennotry** [comment]
Thanks for taking up my opinion.

**Comment by gzotti** [comment]
We have made a few buttons optional to better allow configuring the GUI for small screens often found on laptops used outside. 

> "Switch between equatorial and azimuthal mount": I have only alt-azimuthal mount.

If you ever want to simulate the motion of planets over weeks and months (which is a basic application of a desktop planetarium), you will find this button crucially important. I would not make that optional. 

> "Constellation art": It is not included in the sky culture I always use.

We can probably make this key configurable.

> "Equatorial grid": I usually use J2000.

J2000 is important for printed star maps and referencing positions therein. It becomes increasingly inaccurate when it comes to observable celestial positions that you set with a polar-aligned mount, or objects shown rotating around the celestial pole. In a few years we will likely see the first J2050.0 maps. A desktop planetarium shows conditions for observers, less for atlas creators. The equatorial grid "of date" is therefore mandatory. I would even add an optional "fixed equatorial grid" button that shows hour angles.  The button for the J2000 grid is therefore optional because actually far less people really need it. (The ICRS label may be not fully accurate, though.) And you have the freedom of choice when it comes to assigning hotkeys.

**Comment by 3domennotry** [comment]
Thank you for reply.
and always, thank you.

About J2000:

You are right.
"current" is important.

In my case, I use J2000 more often than "current".
Of course, some will not it.


For reference.

The J2000 is used not only in paper map books but also on websites.
(ex. SIMBAD)

Moreover, When a new nova is reported to have been discovered, its location is indicated by J2000.
http://www.cbat.eps.harvard.edu/iau/cbet/005300/CBET005346.txt

If I want search it, I must use J2000.

Of course, I know that nova(V1723 Sco) was added with the Nova plugin.

thank you.

**Comment by freebrowser1** [comment]
Why J2000 ?
At least an option for J<current date> should be available.
Both J2000 and J2050 are 25 years off epoch. 
Fixed epochs are for printed maps so for a dynamic star map like Stellarium or any other dynamic star map app are obsolete.

**Comment by gzotti** [comment]
Yes, J2000 coordinates are used for reference coordinates in the currently used IAU standard framework, this is why it is available. (The previous was B1950, but we don't show it.) We can expect J2050 introduction in the 2030s. Still, in a planetarium, coordinates "of date" are the better default.

**Comment by freebrowser1** [comment]
Yes, but it is not an exact value of the *current* coordinates, particularly for a very accurate app as Stellarium.

So at least the user has to be able to select the *current* epoch.

**Comment by gzotti** [comment]
The current epoch is default.

**Comment by 3domennotry** [comment]
I have confirmed that it is possible to show/hide the constellation art button.
Thank you very much.
