### ISSUE TITLE
how come useTopocentricCoordinates becomes false when calculating eclipses?

### ISSUE THREAD

**Issue by testori1972** [Stellarium/stellarium#3861]
and if setUseTopocentricCoordinates becomes false in the script: /src/core/SolarEclipseComputer.cpp in column: 535, will ra/dec be reversed or will it still be the same?

**Comment by alex-w** [comment]
Where you see inverting of coordinates?

**Comment by gzotti** [comment]
Please stop raising issues when you have mere questions about your code understanding. 'Issues' are for bugs or feature requests. We may discuss code in 'Discussions'.

setUseTopocentricCoordinates becomes false in this very line. No 'if'. On purpose because it has to become false here. 
The next line then updates all positions. This is the purpose of this next line.
