### ISSUE TITLE
(modern ST) Constellation line different IAU web site's one.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3865]
Please look at:
https://github.com/Stellarium/stellarium/issues/3806

Sorry, I did not notice that.

/Stellarium/skycultures/modern_iau/constellationship.fab
/Stellarium/skycultures/modern_st/constellationship.fab

These files are identical.
When one file is modified, the other file should also be modified.

### System
* Stellarium version: stellarium-24.2-qt5-win32.exe
  + stellarium-24.2-98544be-patch-qt5-win32.exe
  + stellarium-24.2-623f996-patch-qt5-win32.exe
  + stellarium-24.2-19f4d98-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by gzotti** [comment]
IAU does not prescribe constellation stick figures, only borders and (lately) star names. S&T proposes stick figures which are used in common IAU/S&T PR material.  If there is a difference between S&T's lines and our attempt to reproduce them, it needs first and foremost to be fixed in modern_st. 
Maybe we should in addition find a way to cross-reference items, like: constellationship_from = modern_st in info.ini.  This could reduce such duplication and avoid errors. A sky culture that does not care about star names could refer to modern_iau or the default modern. Similarly, artwork could have a reference entry to modern (but explicit entry - without entry it's "no artwork"). It may even be possible to e.g. "inherit most from Skyculture A's artwork, and overwrite/extend a few own entries".  A problem may then be the references. 
OTOH, a completely new format has been defined already which we must review in the coming weeks.

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed in stellarium-24.2-2c2b03d-qt5-win64.exe (full package).

(I have both environments win7 32bit and win7 64bit.
32bit win7 packages is not release.)

Thank you very much.
