### ISSUE TITLE
Release Android version on F-Droid

### ISSUE THREAD

**Issue by rugk** [Stellarium/stellarium#3888]
**Is your feature request related to a problem? Please describe.**
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there)
.
**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
Stay depending on google😜

**Additional context**
https://www.stellarium-labs.com/stellarium-mobile-plus/

**Comment by gzotti** [comment]
"This Android App" WHICH ONE? This repository has nothing to do with an Android app. Please stop barking up this wrong tree.

**Comment by 10110111** [comment]
Note that Stellarium Mobile as it's currently available on Google Play Store is not opensource. Its last opensource version is quite old and available [here](https://github.com/Stellarium/stellarium-web-engine) without any maintenance.

**Comment by axd1967** [comment]
Nevertheless, Android has crept up **in the master branch**  (??) in 9a6d321569a074868cb699834b05138298c2b799 , this is most probably a mistake.

As a result, it is also appearing in totally unrelated work from @Atque  (#4924) as a result of a merge from master.

Android should be a major subproject of Stellarium (I assume this commit is not related to the current Stellarium Mobile version...) As long as this Android version is not even in alpha or beta mode, it should remain in a separate branch, far away from master.

**Comment by 10110111** [comment]
> Nevertheless, Android has crept up in the master branch

Right, it's part of the ongoing process of merging #194.

> As long as this Android version is not even in alpha or beta mode, it should remain in a separate branch, far away from master.

Why? It doesn't hurt anyone. As long as we don't declare official support for Android, it's totally OK to happen to build on this platform without any guarantees of functionality.

**Comment by axd1967** [comment]
> > Nevertheless, Android has crept up in the master branch
> 
> Right, it's part of the ongoing process of merging [#194](https://github.com/Stellarium/stellarium/pull/194).
> 

ok...

> > As long as this Android version is not even in alpha or beta mode, it should remain in a separate branch, far away from master.
> 
> Why? 

Because this is a sound SE practice.

> It doesn't hurt anyone. As long as we don't declare official support for Android, it's totally OK to happen to build on this platform without any guarantees of functionality.

Sure. Adding random files will (very most probably) not hurt anyone. It's a lame argument.

Why don't you add those two other alpha plugins to `master` then? (https://github.com/Stellarium/stellarium/pull/194#issuecomment-720061671)
It adds noise to sourcecode. 
Its presence is just confusing.
This is what topic branches are made for.

https://en.wikipedia.org/wiki/Continuous_integration#Risks

I don't believe in continuous integration. It is not made for the average contributor. (Especially when an almost trivial [vendor branching strategy](https://github.com/Stellarium/stellarium/issues?q=vendor%20branching) is already labeled as _ugly_...)
If Stellarium wants to go the CI path, read this: https://graphite.com/guides/common-ci-failures-technical-guide.

Please note: @DreamNik contribution looks awesome, but I wonder how mobile phone displays will deal with the amount of information that Stellarium presents.

Just admit that this commit was a minor mistake.

**Comment by gzotti** [comment]
What we decide is not your business. Unless you contribute more than verbose comments to long-dead threads.

**Comment by 10110111** [comment]
> Because this is a sound SE practice.

What is SE? StackExchange?

> Sure. Adding random files will (very most probably) not hurt anyone. It's a lame argument.

These are no better:

> It adds noise to sourcecode.
> Its presence is just confusing.

---

> I don't believe in continuous integration.

We don't have to follow your beliefs.

>  I wonder how mobile phone displays will deal with the amount of information that Stellarium presents.

This is a topic for a separate PR. It's impractical to review so many changes at once (notice how #194 has grown conflicts because of the need to amend the changes while pushing them).

> Just admit that this commit was a minor mistake.

From everything you've complained about in this thread, nothing was a mistake, even minor.

---

AFAICT, what has been pushed to `master` from #194 has only improved Stellarium, it didn't break it in any way. Particularly, it's now buildable for Android, which is a step towards full support.

If you find a regression, of course it should be reported, but whatever simply looks like noise to you but not to us or misses some practices that we don't accept is irrelevant.
