### ISSUE TITLE
Position problems on the Poles

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#391]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1723896

Anonymous from SF forum:
===8<===
Hi, I have discovered an anomaly with the poles of earth. From the poles, at 90 degrees of latitude either north or south, there should be no difference in longitude, i.e. you are free to choose any longitude without messing up posistions of celestial bodies. However, if we travel there using Stellarium we see that lognitude indeed does make a difference. These two screen shots show the differences in the position of the moon from different longitudes at 90 S (South Pole telescope).

https://imgur.com/a/euz7i

This seems highly unlikely, as 89 S does not generate a large difference between longitudes (however, a small one, which is plausible).

The difference is just as large as if we stood at the equator!

This affects all bodies, not only earth.

I am using the latest dev beta (stellarium-0.90.0.9873-win64), if this is a new issue.
===8<===

Could still be a problem with earth figure corrections.

**Comment by 10110111** [comment]
OK, thanks to my analysis in #675, we can easily find the culprit now. Namely, since the transition  89°53'59.99"→89°54' corresponds to 89.899997222222222222°→89.9°, something must be fishy with this 89.9° figure, most likely some "manual intervention" in the calculations. Thus, we can grep for this value, which reveals:
```
$ grep '\<89\.9\>' . -rI | fgrep '.cpp:'
./src/core/StelObserver.cpp:    if (fabs(currentLocation.latitude)>=89.9) // avoid tan(90) issues.
./src/core/StelObserver.cpp:    if (fabs(currentLocation.latitude)>=89.9) // avoid tan(90) issues.
```
The actual one leading to the problems I reported is the second, in `StelObserver::getTopographicOffsetFromCenter`. It's funny that the very code supposed to prevent some (impossible¹!) issues introduced new issues instead.

Anyway, if we _really_ want to do this unneeded hack, we should at least do Taylor expansion near `latRad=90°` correctly. What is returned currently (i.e. `a*bByA` constructing a `Vec3d`) doesn't make any sense. Doing Taylor expansion is not too easy for `phiPrime` though, so I suggest removing this "issue avoidance" altogether.

BTW, the same code in `StelObserver::getDistanceFromCenter` doesn't appear correct either: it should return `a*fabs(altFix)` instead of `a*bByA`. I don't know where it's used and how to check this though. In any case, my recommendation is to remove both hacks.

The only thing we might (not really) want to do is to check whether the result is a NaN or Inf, in which case just return something finite. But I don't think it's fair, since the user would then get a wrong value without even knowing it. So even this is something I'd recommend against. It's better to present a NaN or Inf when we truly don't have a valid result.

---
<sup>¹ The issues are impossible on a decent implementation of `tan` due to impossibility to represent π/2 exactly. Nearest representation results in tangent value on the order of 10¹⁶, while `double` can hold values up to about 10³⁰⁸, so even squaring this won't lead to any trouble. See [this example](http://coliru.stacked-crooked.com/a/e9b3882653cd0af4) for what we'd get with input near π/2.

</sup>

**Comment by gzotti** [comment]
Thanks a lot for your thorough analysis. There was something around tan(90) that could happen, and the old solution prevented bad issues, at cost of bad results for places where (almost) nobody is observing. Setting lat=90.0 likely needs a few other fixes here and there (there are no cardinals, only south; no azimuths (?; I am not aware of any convention to use for azimuth on the pole. Direction of Prime Meridian?))

I am away from my sources until June to follow your steps. But is seems we can solve this for 0.19.1.

**Comment by alex-w** [comment]
I've tried disable the "unwanted code" and I see not problem after it.

**Comment by alex-w** [comment]
Georg, please check the master

**Comment by gzotti** [comment]
Yes, there were a few issues. BTW `a*fabs(altFix)` instead of `a*bByA` would also have been wrong. Rather `a*bByA+altfix` or so. The major culprit was copy/paste and return of a double instead of a correctly created Vec3d (which just contains the double somewhere). Currently I cannot detect a problem with the proposed solution of leaving away the safety test.  I have simplified that now, avoiding some code duplication and returning a Vec4d. Now I hope this works on all platforms.

On returning NaN instead of a usable result: I object that. If there now appears a NaN or Inf somewhere in between, we must fix that of course.
