### ISSUE TITLE
skyculture arabic_arabian_peninsula : There are tiny errors in the file.

### ISSUE THREAD

**Issue by 3domennotry** [Stellarium/stellarium#3944]
### Steps to reproduce

(install_dir)/skycultures/arabic_arabian_peninsula/

description.en.utf8

Line114
Line115
Line116
Aldebran

I think that not "Aldebran" but "Aldebaran".

Line51
Mesarthim and Sheratan

I do not know that Mesarthim and Sheratan.
According to https://www.pas.rochester.edu/~emamajek/WGSN/IAU-CSN.txt , 
Mesarthim is &gamma;2 Ari, Sheratan is &beta; Ari.

I look at this skyculture's constellation_names.eng.fab and constellationship.fab
"The Two Marks"(Somehow it is not "The Two Signs") are &alpha; Ari and &beta; Ari.

For reference.
I look at similar skyculture's (arabic_lunar_mansions and arabic_indigenous) constellation_names.eng.fab and constellationship.fab.
In these skycultures, "The Two Signs" are &alpha; Ari and &beta; Ari.

### System
* Stellarium version: stellarium-24.3-qt5-win32.exe
* stellarium-24.3-600edc8-patch-qt5-win32.exe

* Operating system: Win7 32bit

(Sorry, I can not speak English very well.)

thank you.

**Comment by gzotti** [comment]
Traditional "Arab" star names may unfortunately differ from those adopted by IAU WGSN. (E.g. Algomeisa used to be &alpha; UMi=Procyon. WGSN unfortunately perpetuates Piazzi's relabeling.)

Aldebaran may be correct, but   @kajaji should clarify this.

**Comment by kajaji** [comment]
> Line114, Line115,  Line116: Aldebran. I think that not "Aldebran" but "Aldebaran".
Yes.

> I look at this skyculture's constellation_names.eng.fab and constellationship.fab. "The Two Marks"(Somehow it is not "The Two Signs") are α Ari and β Ari.

Al-Sufi reported that the narration of the Arabs states that the  two stars of al-šaraṭayn are (Mesarthim and Sheratan)  and some other narrations has the two stars of al-šaraṭayn as the 2nd star of the Aries figure and the 1st star out of the figure, (β_Ari, α_Ari). 
 But I agree, the stronger opinion is that it is the two brighter stars: α Ari and β Ari. Any how to add to this, a poem of ~ 1850 which is a source of the star names in this sky culture, states that this asterism is the three stars of   α, β and γ Ari.

> "The Two Marks"(Somehow it is not "The Two Signs")
I used different wordings here to get the right  name in native Arabic when translating back into Arabic. We need a feature to display the native names of stars, asterisms, constellations in the original language rather than translating the English names.

**Comment by kajaji** [comment]
Line114, Line115, Line116: Aldebran. I think that not "Aldebran" but "Aldebaran".

Yes.

I look at this skyculture's constellation_names.eng.fab and constellationship.fab. "The Two Marks"(Somehow it is not "The Two Signs") are α Ari and β Ari.

Al-Sufi reported that the narration of the Arabs states that the two stars of al-šaraṭayn are (Mesarthim and Sheratan) and some other narrations has the two stars of al-šaraṭayn as the 2nd star of the Aries figure and the 1st star out of the figure, (β_Ari, α_Ari).
But I agree, the stronger opinion is that it is the two brighter stars: α Ari and β Ari. Any how to add to this, a poem of ~ 1850 which is a source of the star names in this sky culture, states that this asterism is the three stars of α, β and γ Ari.

"The Two Marks"(Somehow it is not "The Two Signs")

I used different wordings here to get the right name in native Arabic when translating back into Arabic. We need a feature to display the native names of stars, asterisms, constellations in the original language rather than translating the English names.

**Comment by kajaji** [comment]
> Line114, Line115, Line116: Aldebran. I think that not "Aldebran" but "Aldebaran".

Yes.

> I look at this skyculture's constellation_names.eng.fab and constellationship.fab. "The Two Marks"(Somehow it is not "The Two Signs") are α Ari and β Ari.

Al-Sufi reported that the narration of the Arabs states that the two stars of al-šaraṭayn are (Mesarthim and Sheratan) and some other narrations has the two stars of al-šaraṭayn as the 2nd star of the Aries figure and the 1st star out of the figure, (β_Ari, α_Ari).
But I agree, the stronger opinion is that it is the two brighter stars: α Ari and β Ari. Any how to add to this, a poem of ~ 1850 which is a source of the star names in this sky culture, states that this asterism is the three stars of α, β and γ Ari.

> "The Two Marks"(Somehow it is not "The Two Signs")

I used different wordings here to get the right name in native Arabic when translating back into Arabic. We need a feature to display the native names of stars, asterisms, constellations in the original language rather than translating the English names.

**Comment by 3domennotry** [comment]
Dear kajaji.
Thank you for reply.

I respect your opinion as to which star you are referring to.
And of course, the names of the constellations.

My only concern is that it doesn't match in arabic_arabian_peninsula.

description.en.utf8
&gamma; Ari, &beta; Ari, The Two Signs

constellation_names.eng.fab and constellationship.fab
&alpha; Ari, &beta; Ari, The Two Marks

**Comment by kajaji** [comment]
Thanks
As you pointed out. description.en.utf8 should be consistent with onstellation_names.eng.fab and constellationship.fab

**Comment by alex-w** [comment]
@kajaji in the `description.en.utf8` should be _Aldebaran_ and `The Two Marks` - is it correct?

**Comment by kajaji** [comment]
@alex-w  I attach here the updated description.en.utf8 (please change .txt to .utf8 , uploading a .utf8 is not supported.
I also included update for the issue here: https://github.com/Stellarium/stellarium/issues/3938#issuecomment-2402357739

[description.en.txt](https://github.com/user-attachments/files/17349789/description.en.txt)

**Comment by alex-w** [comment]
@kajaji thanks!

**Comment by 3domennotry** [comment]
I have confirmed that this bug has been fixed in stellarium-24.3-44fb485-qt5-win64.exe (full package).

Thank you very much.
