### ISSUE TITLE
Controllo montatura Ascom

### ISSUE THREAD

**Issue by libero6** [Stellarium/stellarium#3997]
Buongiorno
Chiedevo se è possibile che aggiornando Stellarium dalla v. non mi ricordo.... alla v. 24.3 non funzioni più la spunta Ascom per impostare il controllo del telescopio....?  Fatto su due pc uno fisso e uno portatile stesso risultato.......
Grazie
Saluti
                                                             Paolo Cattabriga

### Actual Behaviour
Describe or maybe attach a screenshot?

### System
* Stellarium version: <Name of downloaded installable file?>
* Operating system: <Name, version number>
* Graphics Card: <Manufacturer (likely Intel, NVidia, AMD?), Model (HD, Geforce, Radeon..., with model number), driver version?>
* Screen type (if applicable): Resolution, HighDPI, scaling

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.

**Comment by gzotti** [comment]
As can be read in the User Guide and GUI tooltips, ASCOM seems to be incompatible to Qt6 which is why we had to disable support. You can install a Qt5-based build.

**Comment by libero6** [comment]
Risolto problema....,  disinstallato V. 4.3 e reinstallato V4.1 
Però non ho capito la faccenda Alpaca..........
Grazie
Saluti
                                                                                   paolo

**Comment by 10110111** [comment]
Looks like our tooltip is not discoverable enough for the users. Maybe the radio button should instead provide an obvious hyperlink to a help (Wiki?) page about this.

**Comment by gzotti** [comment]
Maybe it's just me, but I'd gnawed my arm off (or at least searched for a solution in the manual) before asking what's in the FAQ. The customer support department is understaffed as well... 

It seems to have been the first user to ever report back between the lines that ASCOM worked in a Qt6 build. (Presumably he means he reinstalled V24.1/Qt6 instead of V24.3/Qt5, ignoring the advice given.)

We can change the button label as well before disabling the button, or add a hyperlink in a label, or whatever. Feel free!
Qt5.15 will be obsolete next May. By then "somebody" should solve the Alpaca switchover.
