### ISSUE TITLE
Geostationary objects are moving

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#405]
_Original report by Detlev Hoffmann:_ https://bugs.launchpad.net/stellarium/+bug/951045

I'm using stellarium since some days and it is really a good tool. I was using my home position looking to "Sirius" and wanted to fast forward the view to the next day "=".
The star it self moves (I assume) well over the sky.

But as I inkluded a view to the satelites, looking to the geostationary satelite "ASTRA 1E" i was wondering, why this object moves...

If you use "=" to fast forward the satelite escapes within some "days".
If you use the fast forward function it might take some "days" more but the satelitte moves also to the eastern border.

My logfile:
```
2012-03-09T19:41:35
Windows 7
Compiled with GCC 4.4.0
Qt runtime version: 4.7.4
Qt compilation version: 4.7.4
Addressing mode: 32-bit
Total memory: 3877 MB (unreliable)
Total virtual memory: 2047 MB (unreliable)
Physical memory in use: 45%
Processor speed: 2634 MHz
Processor name: Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz
Processor speed: 2634 MHz
Processor name: Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz
Processor speed: 2634 MHz
Processor name: Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz
Processor speed: 2634 MHz
Processor name: Intel(R) Core(TM) i5 CPU M 460 @ 2.53GHz
C:\Program Files (x86)\Stellarium\stellarium.exe
 -------------------------------------------------------
[ This is Stellarium 0.11.1 - http://www.stellarium.org ]
[ Copyright (C) 2000-2011 Fabien Chereau et al ]
 -------------------------------------------------------
Writing log file to: "C:/Users/Detlev/AppData/Roaming/Stellarium/log.txt"
File search paths:
  0 . "C:\Users\Detlev\AppData\Roaming\Stellarium"
  1 . "."
Config file is: "C:\Users\Detlev\AppData\Roaming\Stellarium/config.ini"
OpenGL supported version: "2.1.2"
Qt GL paint engine is: "OpenGL2"
Cache directory is: "C:\Users\Detlev\AppData\Local\stellarium\stellarium\cache"
Sky language is "de"
Application language is "de"
Loading Solar System data ...
Loaded 65 / 65 planet orbits from "C:\Users\Detlev\AppData\Roaming\Stellarium/data/ssystem.ini"
Loading star data ...
"Loading "./stars/default/stars_0_0v0_1.cat": 0_0v0_1; 5013"
"Loading "./stars/default/stars_1_0v0_1.cat": 1_0v0_1; 21999"
"Loading "./stars/default/stars_2_0v0_1.cat": 2_0v0_1; 151416"
"Loading "./stars/default/stars_3_1v0_0.cat": 3_1v0_0; 434064"
"Loading "C:\Users\Detlev\AppData\Roaming\Stellarium/stars/default/stars_4_1v0_0.cat": 4_1v0_0; 1725497"
"Loading "C:\Users\Detlev\AppData\Roaming\Stellarium/stars/default/stars_5_2v0_0.cat": 5_2v0_0; 7669011"
"Loading "C:\Users\Detlev\AppData\Roaming\Stellarium/stars/default/stars_6_2v0_0.cat": 6_2v0_0; 26615233"
"Loading "C:\Users\Detlev\AppData\Roaming\Stellarium/stars/default/stars_7_2v0_0.cat": 7_2v0_0; 57826266"
"Loading "C:\Users\Detlev\AppData\Roaming\Stellarium/stars/default/stars_8_2v0_0.cat": 8_2v0_0; 116923084"
Finished loading star catalogue data, max_geodesic_level: 8
navigation/preset_sky_time is a double - treating as jday: 2.45151e+06
Loaded 10051 NGC records
Loading NGC name data ...
Loaded 222 / 222 NGC name records successfully
Loading star names from "./skycultures/western/star_names.fab"
Loaded 230 / 230 common star names
Loading star names from "./stars/default/name.fab"
Loaded 3215 / 4359 scientific star names
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 89 / 89 constellation names
Loading constellation boundary data ...
Loaded 782 constellation boundary segments
Creating GUI ...
Loaded plugin "Oculars" .
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at: "C:\Users\Detlev\AppData\Roaming\Stellarium/modules/Oculars/ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version 2
Loaded plugin "Satellites" .
Satellites::getJsonFileVersion() version from file: "0.6.4"
Satellites::init using satellite.json file: "C:\Users\Detlev\AppData\Roaming\Stellarium/modules/Satellites/satellites.json"
Loaded plugin "SolarSystemEditor" .
Using the ssystem.ini file that already exists in the user directory...
Loaded plugin "Supernovae" .
Supernovae::getJsonFileVersion() version from file: "0.2.7"
Supernovae::init using supernovae.json file: "C:\Users\Detlev\AppData\Roaming\Stellarium/modules/Supernovae/supernovae.json"
Loaded plugin "TimeZoneConfiguration" .
```

**Comment by CF20852** [comment]
Actively-managed geostationary satellites operate within a "stationkeeping box," typically about +/- 0.05 degrees longitude and some amount of latitude for U.S.-licensed satellites and perhaps +/- 0.1 degrees longitude and some amount of latitude for non-U.S.-licensed satellites.  The satellite orbits are influenced by the gravity of the sun and the moon, and by solar winds, and are not passively stable in the Equatorial Plane at the assigned orbital longitude.  About every two weeks, on average, the satellite operator performs a stationkeeping maneuver to keep the satellite in the box.  Thus, it is necessary to periodically update the ephemeris data (TLE files) for Stellarium or any other orbital simulation program to accurately depict the locations of the satellites over time.  A snapshot of the ephemeris data for one time sample won't work--the simulated satellite will eventually drift away from its assigned orbital location.  Compare, for example, with the results of the STK program from Analytical Graphics.  You can also compare the subsatellite longitude in Stellarium with what you can find on the N2YO website, which uses up-to-date ephemeris data.  The ephemeris data for GSO satellites is usually updated two or more times per week, and more often if the satellite is maneuvering.

**Comment by gzotti** [comment]
Thank you. This is an issue with a looong history and likely no solution just because there is none that does not involve updating TLEs every few days, so you cannot follow a gs. satellite for a year or so. My own observations of ISS and Iridium mostly work. It would be interesting to know if geostationary satellites currently have a "real" problem or not (see original reports), and close this if they are OK.

**Comment by CF20852** [comment]
I think you can only accurately depict the location of satellites retrospectively, by using a TLE file containing past data.  However, for GSO satellites in particular, even this won't be completely accurate all of the time unless JSpOC happens to observe a satellite during and immediately after a stationkeeping maneuver.  You cannot predict the location of most actively-managed satellites far (i.e. weeks or months) into the future using a current snapshot of the ephemeris data, because the TLE data available from Celestrak or Space-Track.org do not contain data regarding future (and unknown) stationkeeping maneuvers.  LEO satellites will be influenced by solar activity that affects the upper atmosphere, which is predictable to a certain degree, but not with complete accuracy and precision.  For example, I recall a conversation with a Planet Labs employee in which I was told that a particular solar event caused some of their Dove satellites (which do not have propulsion systems) to lose at least a few kilometers of altitude over a period of a day or so.

**Comment by gzotti** [comment]
I am aware of these issues. The original discussion included reports that some geostationary satellites were not where they should have been, even with good TLEs. I don't have a satellite dish to try this, but if somebody who regularly tunes in to whatever geostationaries they want to would take the hour and help this project by reporting "good" or "bad" position (with up-to-date TLE of course), we could decide what to do with this issue: close it, or look for an implementation bug.

**Comment by CF20852** [comment]
I suggest comparing the Stellarium satellite locations (sub-satellite longitudes in particular) with what N2YO.com or LyngSat.com say they are.  If I can get Stellarium working with a current set of ephemeris data, I'll make some spot-checks.

**Comment by CF20852** [comment]
I took a photo of the GSO arc in the range of 115-119 degrees West Longitude from Prescott, Arizona, USA on 6 October 2018 at about 04:49:17 UTC.  This was one of a sequence of 30 time-lapse photos of that portion of the sky, and because the satellites I see in the photo show very little movement over the course of the sequence, I conclude that they are GSO satellites.  The exposures were 20 seconds each, spaced 45 seconds apart.  Using Cursa and HIP 22336 as reference stars, I see eleven GSO satellites at approximately the locations Stellarium predicts.  I do not currently have the necessary receiving equipment to positively identify those satellites based on their transmissions.  The satellites that I think I see, and which Stellarium predicts, are MEXSAT-3, EUTELSAT 115 WEST B, VIASAT-1, XM-4, SIRIUS FM-6, EUTELSAT 117 WEST B, EUTELSAT 117 WEST A, ANIK-F3, ECHOSTAR 7, ECHOSTAR 14, and DIRECTV 7S.  I posted a time-lapse video at https://www.youtube.com/watch?v=O7UC4UkLaks.  It's best played at 0.25 speed and the highest attainable resolution, and looped.

**Comment by gzotti** [comment]
Nice sequence, thanks! Although this must have been 4:49 local time (UT-7). This I think shows that whatever caused issues in 2012 has been solved. Given that long-time orbit predictions (the actual wishlist entry) are not possible, I close this issue.

**Comment by CF20852** [comment]
Yes, 04:49 local time, UTC-7, or 11:49 UTC.  Sorry, was getting ready to run out the door for my flu shot when I wrote my last posting and had a senior moment.
