### ISSUE TITLE
Scripting Engine Graphics Tools

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#459]
_Original report by Steve T.:_ https://bugs.launchpad.net/stellarium/+bug/1106739

This feature request from old bug tracker.

The scripting is very nice. I am looking at it to suppliment the astronomy course I teach. I would love to make some scripts where I could draw a trail of the path an object takes, like an analema or a planets retrograde motion. It would probably be a call to draw or plot at the current object's location, but not travel with the object. Another way to state it is to be able to draw/plot at a given RA/Dec.

Thanks, Steve T.

**Comment by gzotti** [comment]
This has been fulfilled with AstroCalc, Planet Trails, and Markers. Or is "scriptability" the point here?

**Comment by beltoforion** [comment]
I'm not the original author but a simple drawing feature similar to the label feature would be helpfull in creating educational videos. For instance tracking a planets motion day by day. It is more instructive if the planet trail appears dot by dot over the course of a month rather than showing the complete trail at once. 

Another application is drawing analemmas. One could draw one for a region on the northeren hemisphere and then compars the drawing with one created for an equatorial region. 

However there is a workaround: One can use the label manager to output dots as shown in this slightly modified analemma example (based on the on by @alex-w):

//
// Author: Alexander Wolf
// Version: 1.0
// License: Public Domain
// Name: Analemma
// Description: A demonstration of the analemma - the path of the Sun across the sky during the year.
//
core.goHome();
label = LabelMgr.labelScreen("Analemma", 20, 20, false, 30, "#aa0000");
LabelMgr.setLabelShow(label, true);
core.wait(1);
GridLinesMgr.setFlagAzimuthalGrid(true);
GridLinesMgr.setFlagMeridianLine(true);
core.setObserverLocation(0, 30, 1, 1, "", "Earth");
core.setDate("2012-06-22T12:00:00", "utc");
StelMovementMgr.zoomTo(160, 5);
core.wait(5);

for (i=0; i<356/4; i++)
{
    core.setDate("+4 day");
    var info = core.getObjectInfo("Sun");
    var az = info.azimuth;
    var alt = info.altitude;

    labelDot = LabelMgr.labelHorizon(".", az, alt, "true", 14, "#000000", false);
    LabelMgr.setLabelShow(labelDot, true);

    LabelMgr.setLabelShow(label, false);
    j = i + 1;
    label = LabelMgr.labelScreen("Week " + j, 20, 20, false, 30, "#aa0000");
    LabelMgr.setLabelShow(label, true);
    core.wait(.1);
}
