### ISSUE TITLE
Visual artifacts on the sky (new Milky Way texture contains halos for brightest stars)

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#475]
_Original report:_ https://bugs.launchpad.net/stellarium/+bug/1408373

Current trunk (rev. 7276) has visual artifacts for bright objects like Moon or Sirius - a faked light spots below horizon when atmosphere is enabled. Those light spots has structure and position similar Moon and Sirius, but with negative value of the height.

Seems this artifacts related to refraction/extinction effects, but it required more investigation.

**Comment by gzotti** [comment]
(from orig. discussion)
The new milky way texture has diffused spots at the locations of the brightest stars and clusters. Of course, Sirius and Arcturus will move away from their spots due to proper motion.

A "fix" is tedious but obvious: edit the image and paint away the bright spots caused by the brightest stars. But do that for all, not just Sirius.
