### ISSUE TITLE
Missing letter in object description

### ISSUE THREAD

**Issue by alex-w** [Stellarium/stellarium#478]
_Original report by GunChleoc:_ https://bugs.launchpad.net/stellarium/+bug/1638975

In the Scottish Gaelic (gd) translation, there is a letter that won't display.

Example string:

Ecliptic Longitude/Latitude (J2000.0)
Domhan-fhad/domhan-leud èiclipteach (J2000.0)

The f in "Domhan-fhad" is missing in all occurrences of "Domhan-fhad".

Stellarium 0.15.0-win64 on Windows 7

**Comment by gzotti** [comment]
After reading the original discussion (it works in ANGLE mode): There is likely nothing we can do about it when this is an OpenGL driver or system font problem.  If the translation in Transifex is complete and correct, incorrect font display is out of our hands.

BTW it seems the UI strings have changed since this report, I cannot find the examples.
