### ISSUE TITLE
Constellations Hercules and Gemini are mixed up

### ISSUE THREAD

**Issue by beltoforion** [Stellarium/stellarium#490]
### Expected Behaviour
When i run the script listed below i would expect the constellation "Hercules" to be shown. 

### Actual Behaviour
Constellation Gemini is shown instead. The info in the upper left corner says "Pollux (Hercules)". The same happens when you use the search box and type "Hercules"

### Steps to reproduce
Execute the following script:
core.setDate("2018-10-25T02:00:00", "utc");
ConstellationMgr.setFlagIsolateSelected(true);  
ConstellationMgr.setFlagLabels(true);
ConstellationMgr.setFlagBoundaries(true);
core.selectObjectByName("Hercules");
StelMovementMgr.autoZoomIn(1);
StelMovementMgr.zoomTo(120,1);

### System
* Stellarium version: 0.18.2
* Operating system: Linux Mint (Kernel 4.15)

I downloaded the appimage via this link today (2018-10-03): 
https://github.com/Stellarium/stellarium/releases/download/v0.18.2/Stellarium-0.18.2-x86_64.AppImage

[log.txt](https://github.com/Stellarium/stellarium/files/2443263/log.txt)

**Comment by alex-w** [comment]
The behaviour of script is correct, because two objects has same name and stars has priority over constellations. For example you typed "Hydra" - are you meaning constellation or the moon?

**Comment by gzotti** [comment]
Nomenclature clash, again :-( 

The reason is a totally obscure source for the star name "Hercules" in place of Pollux. We know this comes from our sourcing the Yale BSC (among many other sources) for alternative names. But really nobody on this globe in the 21st century apart from 65 historians (?) knows and cares about this use of the name. We have discussed this elsewhere, we should have categories of star names (at least IAU, GOTO, common, rare).

Maybe context information should really be added like 

core.selectObjectByName("Hercules", "constellation");
core.selectObjectByName("Hercules", "star");

and a fallback solution behaves like now?

Searching for Hydra should naturally bring the constellation. Until few years ago, that other Hydra was not causing trouble ...

**Comment by alex-w** [comment]
> Searching for Hydra should naturally bring the constellation. Until few years ago, that other Hydra was not causing trouble ...

Nope, it will be the moon of Pluto

**Comment by gzotti** [comment]
Yes, it brings Pluto's moon which almost nobody can observe. Is that useful? It *should* bring the well-known observable constellation if the currently active skyculture contains it.

**Comment by sunshuwei** [comment]
I think the star name“ Hercules” should be removed.
When almost everyone searches for Hercules, it refers to the constellation, not the star.

It has the same name as the constellation. Translation conflicts in other languages can lead to translation conflicts.
The translations of the constellations and stars may be different, but there is confusion here. The ICU constellation must be translated, and the star shows the constellation's name.
It is rare, but it brings inconvenience and conflict.

**Comment by alex-w** [comment]
> Yes, it brings Pluto's moon which almost nobody can observe. Is that useful? It _should_ bring the well-known observable constellation if the currently active skyculture contains it.

Really?! :) I have few requests for Hydra as moon and 1 or 2 request for Hydra as constellation. Plus many moons and asteroids has same names ;)

**Comment by gzotti** [comment]
You had requests to add Hydra (the Moon) because it was not there, like Nix, because they became popular with their discovery and the New Horizons mission. There were no further requests for Hydra (the constellation) because every astronomy program (including Stellarium) already showed it. 

The fact that some asteroids and moons of the outer planets have equal names does not make it easier for us, agreed. But it should be possible in a script to say what I am looking for. The script can search for "Hydra (PIII)", but when I search for "Hydra" in a script, the only useful answer is the constellation  (i.e. auto-matching in the script should be avoided, or should find an object only if no object with a direct match can be found.), or we should add an optional argument which should indicate what we are looking for. 

Likewise, for the outer moons or asteroids, we can search for "Europa (JII)" or "(52) Europa" to be correct. Searching for "Europa" may turn up either one, where I would favour the moon. Again, an optional argument like "moon" or "asteroid" could help clarify the intent of the search, or lead to an empty result (if e.g. elements for (52) Europa are not installed.).

Fortunately asteroid (5143) is spelled "Heracles"...
