### ISSUE TITLE
Setup Travis-CI for autobuild AppImage (portable package for Linux)

### ISSUE THREAD

**Issue by Symbian9** [Stellarium/stellarium#50]
Providing an <a href="https://appimage.org">AppImage</a> would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, <a href="http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80">make it executable</a>, and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with appimaged
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the <a href="https://appimage.github.io/apps">AppImageHub</a> central directory of available AppImages

<a href="https://github.com/AppImage/AppImageKit/wiki/AppImages">Here is an overview</a> of some projects that are already distributing upstream-provided, official AppImages.

https://github.com/probonopd/linuxdeployqt has lots of real-world examples on how to do this. Let @probonopd know if something is not clear or you need some help.

https://github.com/probonopd/uploadtool script will help you setup Travis-CI for uploading built AppImage's automatically back to Github repo in "Releases" section.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net

Ask @probonopd for help you on Github ;-)

**Comment by probonopd** [comment]
Please start from copying 1:1 the Travis CI example given at https://github.com/probonopd/linuxdeployqt. Should you run into issues, I'm happy to help. Also, AppImage developers are on #AppImage on irc.freenode.net.

Actually, some time ago, I've made an AppImage for test purposes:
https://bintray.com/probono/AppImages/Stellarium/0.14.3.glibc2.15#files

This is outdated by now, and it is too large (because at the time, linuxdeploy didn't even exist). So expect much better results if "done properly" today.

**Comment by Symbian9** [comment]
@alex-w, @probonopd, I currently test this AppImage...

- https://github.com/Stellarium/stellarium/releases/download/v0.17.0/Stellarium-0.17.0-x86_64.AppImage

... and can't run it according this (output from terminal)
```
$ ./Stellarium-0.17.0-x86_64.AppImage
User config directory does not exist: "home/username/.stellarium"
Creating directory "home/username/.stellarium"
WARNING StelFileMgr::StelFileMgr: could not find install location: "/usr/share/stellarium" (we checked for "/usr/share/stellarium/data/ssystem_major.ini")
Couldn't find install directory location.
Aborted

**Comment by probonopd** [comment]
It is trying to load files from `/usr/share/stellarium` which clearly is not going to work since in an AppImage, the files are not at that location.

The Stellarium source code needs to be changed so that it is looking for the files at a location relative to the main executable, rather than at a hardcoded absolute path compiled in at compile time.

__DO NOT USE__ [`QStringList QStandardPaths::standardLocations(QStandardPaths::AppDataLocation);`](http://doc.qt.io/qt-5/qstandardpaths.html)

According to the [Qt documentation](http://doc.qt.io/qt-5/qstandardpaths.html), this resolves to `"~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"` but clearly `/usr` is not where these things are located in an AppImage.

You could use[ `QString QCoreApplication::applicationFilePath()`](http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath) instead and construct a _relative_ path to `../share/kaidan/images/` from there.

For an example, see:
https://github.com/KaidanIM/Kaidan/commit/da38011b55a1aa5d17764647ecd699deb4be437f

As a result, it should work both in normal installations and in relocatable installations such as AppImages.

**Comment by alex-w** [comment]
Please check https://launchpad.net/stellarium/trunk/0.90.0/+download/Stellarium-0.90.0.15661-x86_64.AppImage

**Comment by probonopd** [comment]
Thanks @alex-w - may I ask how you got an AppImage on launchpad.net?

Unfortunately it is still not working correctly yet:

```
me@host:~$ Downloads/Stellarium-0.90.0.15661-x86_64.AppImage 
User config directory does not exist:  "/home/me/.stellarium"
Creating directory  "/home/me/.stellarium"
WARNING StelFileMgr::StelFileMgr: could not find install location: "/usr/share/stellarium"  (we checked for  "/usr/share/stellarium/data/ssystem_major.ini" ).
Maybe this is AppImage or something similar? Let's check relative path...
WARNING StelFileMgr::StelFileMgr: could not find install location: "../share/stellarium"  (we checked for  "../share/stellarium/data/ssystem_major.ini" ).
Couldn't find install directory location.
Aborted
```

**Comment by alex-w** [comment]
Please check https://launchpad.net/stellarium/trunk/0.90.0/+download/Stellarium-0.90.0.15663-x86_64.AppImage

**Comment by probonopd** [comment]
@alex-w great, runs very nicely on Xubuntu 14.04 with no Qt or KDE installed. :+1: 
Thank you very much.

**Comment by probonopd** [comment]
However, it does not run on 14.04 (the oldest still-supported LTS release):

/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-6907/AppRun)
/run/firejail/appimage/.appimage-6907/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-6907/AppRun)

Would you be able to produce the AppImage on Ubuntu 14.04 (trusty)? Then it would be compatible with many more Linux distributions (versions from 2014 onwards) and not just the latest ones. Also, it could be included in the AppImageHub central directory of available AppImages then.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/323195130#L553-L555

**Comment by alex-w** [comment]
Please check https://github.com/Stellarium/stellarium/releases/download/v0.17.0/Stellarium-0.17.0.1-x86_64.AppImage

**Comment by probonopd** [comment]
Thank you very much @alex-w, this one works on Ubuntu 14.04. It also passed the [AppImageHub automated tests](https://travis-ci.org/AppImage/appimage.github.io/builds/323611001) :+1: 

Adding it to [AppImageHub](https://appimage.github.io/apps/).

**Comment by probonopd** [comment]
...and with that it would be nice to see an AppImage link here:

![stellarium](https://user-images.githubusercontent.com/2480569/34462866-48857cb8-ee4d-11e7-94c6-ba2932f99101.png)
