### ISSUE TITLE
Where is XP's stellarium 0.19.0?

### ISSUE THREAD

**Issue by bestive** [Stellarium/stellarium#659]
Strongly requested to provide the XP version.
thank you very much.
I love you, the masters of the stellarium project team!

**Comment by alex-w** [comment]
We dropping the building packages for Windows XP because this OS is not supported already a long time and the last of subscription for support will be finished in next month (for banking terminals).

I've maked one and maybe he will works - https://github.com/Stellarium/stellarium/releases/download/v0.19.0/stellarium-0.19.0-classic-win32.exe

The classic packages for Stellarium has EOL (end-of-life) status and will not be published anymore.

**Comment by gzotti** [comment]
Windows XP was put to the grave 5 years ago. Alex did a wonderful job building packages for XP, but it became increasingly difficult because some of the software infrastructure used to build Stellarium also has stopped support for XP. Please understand that there we had to drop support now, given a user base of about 0.1 percent for the XP version. Version 0.18.3 and earlier will continue to work.

**Comment by bestive** [comment]
Thank you very much for  your hard work! 
I have an old laptop and use it when I go out, only using XP.
This version has been downloaded today (in China; large file downloads on github are difficult)
Perfect running, great!
I have already shared with my friends, the same is an astronomy enthusiast.
Thanks again, I wish you a happy work.
(My English is not good, sorry)

**Comment by bestive** [comment]
I have already feedbackd you, thank you.@alex-w @gzotti
