### ISSUE TITLE
Celestial bodies not completely dark at night side

### ISSUE THREAD

**Issue by Atque** [Stellarium/stellarium#669]
Celestial bodies are not completely dark at their night sides. I understand such things as the earthshine on the moon, which is a very nice feature for sure, but e.g. Saturn should not be illuminated by its tiny moons. I have not found any celestial body that is completely dark at the night side. Jupiter, Uranus, Saturn etc are all illuminated on their night sides. This is especially obvious on Jupiter, with its bands and belts in its atmosphere.

Is there a thought behind this or simply a bug? Saturn has such things as ringshine, but I most highly doubt Stellarium takes that into account. ;)

See this screenshot of Saturn seen from Iapetus:
![stellarium-158](https://user-images.githubusercontent.com/37028368/56442520-66a15400-62f1-11e9-844e-ff7b4aef53d6.png)
Please enlarge the screenshot to see the illumination more clearly.

**Comment by gzotti** [comment]
Walk out at night under good skies (no light pollution, no clouds, no moonlight). You will be able to see your environment just from the illumination by starlight. With the Milky Way high above me on a pristine site I have seen the dark shadow under a tree. I would therefore consider that level of non-black planet disk (ambient configured to 0.02)  "illumination by galactic background".

**Comment by Atque** [comment]
@gzotti I really don't think that galactic illumination would be visible from space though.

**Comment by alex-w** [comment]
Hmm... I think this is question of gamma settings for monitor, because on different systems with different gamma I see and don't see described issue.

**Comment by gzotti** [comment]
2% ambient brightness is really a non-issue IMHO. This is just "off-black" that simply indicates "there is something". This most likely has been set on purpose eons ago (current is my code from 2015, but I think something similar had been there previously, e.g. V0.10.6.1 also is definitely non-black), so that also the dark border is visible on the screen. You also can see the Moon's dark limb in our simulated daylight sky for the same reason, so that you can better expect/estimate planet/satellite occultations or such things. Of course the Moon's dark limb cannot be observed in blue daylight sky with a telescope.

We cannot simulate bright light like from the Solar or even Lunar disk, or ultra-bright pinpoint stars and the faintest wisp of non-black next to the darkness of space on any current screen. There is always a visual compromise to be found. This solution here has been done *on purpose*.

It may be a gamma thing, I don't see a problem on any monitor in my area. Calibrate your monitor then.

**Comment by Atque** [comment]
I hadn't even thought of the problem with the daylight moon, that is even more ugly and cannot be solved by adjusting the gamma of your screen. Maybe there could be an option in the config/GUI to adjust ambient brightness on bodies. That way we could satisfy those who ask for realism, as well as those who want to time their occultations.

**Comment by gzotti** [comment]
We are open for working patches. Especially a solution that also hides a star's disk immediately when its center is covered, this is currently much more unrealistic.

**Comment by Atque** [comment]
> Especially a solution that also hides a star's disk immediately when its center is covered, this is currently much more unrealistic.

Not only unrealistic, but also makes it a lot harder to determine when the occultation takes place. But I think we should have a separate bug report for that, as this is an unrelated issue.
