### ISSUE TITLE
Telescope control Issue

### ISSUE THREAD

**Issue by CACOUK** [Stellarium/stellarium#687]
Hello, I have a problem with the  'Telescope Control functionality', if I select a star or an object either near or close to the eastern horizon (as an example) the telescope may or may not go to that object, but if it does move to the initial selection in the east, and then I select an object or star to  the west nothing happens. If I select a star close to the original selection in the east the control works but only for short distances before it stop moving again! Why and what can I do to fix this annoying and frustrating issue. This issue can also be the same for North to South directions. 

I am using a LX200 Meade 10" on a plinth and a desktop windows 10 computer.

I have uninstalled and reinstalled Stellarium several times now, I have also rebooted my computer too many times to  mention and still no luck.
Kind regards Tony and Micheal of CACO UK! 

PS: Both Michael and I are extremely limited with technical jargon so please keep it simple ! 

has been allocated and I then press Ctrl and number 1 the telescope does not move at all, and sometimes will move but will not move

**Comment by alex-w** [comment]
Any errors or warnings in the log.txt (Start -> Programs -> Stellarium -> Latest run log)?

**Comment by gzotti** [comment]
"Start" has been the canonical name of the START button (since Win95?) which is in the lower left corner of your screen and bears the Windows 10 logo as icon. 

"Programs" used to be the name of the fold-out list of programs. Most users remember this from their previous operating systems. On Windows 10, the left side of the panel which appears after pressing the Start (or Windows) button is a long alphabetized list of all installed programs. Under "S" you will find a "Stellarium" program group, and inside, ...

umm,... 8-o

@alex-w , the "last run log" entry is not present here! Is it possible that on Win10 the link will only be created by the installer if the file is actually here? Then the installer should install an empty or dummy file to create a valid link.

@CACOUK , the current log is also accessible in Stellarium's user interface: press F1 and select tab "log file". Or see the User Guide, section 5.1.1 which explains how to access your Stellarium user data directory. The log is inside.

**Comment by gzotti** [comment]
@CACOUK please locate the logfile and show it. Else the bug report will be closed.
