### ISSUE TITLE
Orbits error

### ISSUE THREAD

**Issue by sunshuwei** [Stellarium/stellarium#749]
Please look at this.
![stellarium问题](https://user-images.githubusercontent.com/34102610/64065690-ff05f880-cc42-11e9-89eb-3ca8a7b3f54d.png)

**Comment by gzotti** [comment]
This is an artifact of light time correction.

**Comment by alex-w** [comment]
@gzotti could you fix it?

**Comment by gzotti** [comment]
This really seems to have been introduced with #736. But I don't see how and where the problem is. Any ideas?

**Comment by alex-w** [comment]
Distance from Solar System Observer to any planet is very big and we just did not saw artifacts. After introducing a few more Observers distances gone short and now we can see artifacts. This issue really was introducing a long time ago (I remember similar problems in series 0.10 and 0.11) and she is related to light speed correction.

**Comment by guillaumechereau** [comment]
The problem seems to come from difference between the planet and the moon computation time (lastJDE).   It seems that the orbit computation uses the apparent time of the moon for both bodies, while the rendering uses apparent time of the moon for the moon->planet position and the apparent time of the planet for the planet->sun position.

If I add those lines:

   	if (parent)
		parent->computePositionWithoutOrbits(lastJDE);

A the top of the 'drawOrbit' method, it seems to fix the problem.  Not sure if that is the correct solution though.

**Comment by gzotti** [comment]
Wow, that seemed to look spot-on, thank you! Yes, getHeliocentricEclipticPos() is called again, and the parent planet may have "forgotten" its position...  At least that looked like the solution. 

But now the next oddity: Select Jupiter while observing from the Solar System Observer. Enable light time correction. Enlarge the moons a bit to see that they are now "ahead of their halos" on the orbit line, or rather they are carried with Jupiter to be ahead of their location on their orbit line.

**Comment by gzotti** [comment]
This is so crazy. It seems the pure existence of the new ..._observers in the ssystem_major causes the issue. Manually editing the solar_system_observer to the new values (resp. omissions of new defaults) works, but as soon as I activate the new file from that commit for #736 (which adds the new observers, but uses the same values for the SSO) shows the spikes again, when using the solar_system_observer as observer location. I am totally puzzled now.

**Comment by guillaumechereau** [comment]
Yes, I think the problem is that with the previous fix, we are now changing the 'lastJDE' of the parent planet when we draw the orbits.

I think a proper solution would be to refactor the code so that the position getters of planet accept a time argument, instead of having to call computePosition that has the side effect of changing the drawing time of the planet.  This would probably be slow, but we could maybe add a global position cache for the planets: (planet, time) -> position.

I will try this in a local branch to see if that could work.

**Comment by guillaumechereau** [comment]
I made a branch with an attempt of implementation of the solution I explained in the last message:
https://github.com/Stellarium/stellarium/tree/fix-planets-orbits

Not tested much, but it seems to fix at least the biggest issues.  It might be slower than the current code since the orbit caching is done using a hash table now instead of the previous way, that was clever but hard to debug.

**Comment by gzotti** [comment]
Good, this keeps the 3D moons on their orbits. Observing Jupiter from the Solar System Observer with a moderate time lapse speed has still issues though. The orbit vertices seem to be computed/drawn for fixed times, and occasionally updated (depending on orbit duration?). Every moon therefore still shows a growing spike, esp. the outer moons of Jupiter. Every few moments the orbits are then recomputed and jump so that the spike is removed for one frame. Probably the orbit has to be pushed in place around the planet for every orbit redraw to fix that. 

BTW my observed framerate drops 70->60 when orbits are shown, but remains above 80fps when orbits not shown. (Geforce 960M)

**Comment by guillaumechereau** [comment]
This can be fixed simply by removing the 'fabs(lastOrbitJDE-dateJDE)>deltaOrbitJDE' condition in computePosition, but then the orbit computation really gets slow!  I will try to change the caching in this branch to see if I can improve the speed.

**Comment by caioaugusto1998** [comment]
HELLO RUSLAN

**Comment by caioaugusto1998** [comment]
@gzotti WE REPORT THE GUY

**Comment by caioaugusto1998** [comment]
I CAN ASK

**Comment by caioaugusto1998** [comment]
@gzotti WE BLOCKED THE USER FERREIRADANTAS10
