### ISSUE TITLE
Zenith scripting issue

### ISSUE THREAD

**Issue by NotSoRandomOne** [Stellarium/stellarium#754]
With following simple script:
<pre>core.moveToAltAzi(90, 180, 1);</pre>

### Expected Behaviour

* Stellarium should center on zenith

* Even if Stellarium isn't in azimuthal mode, I'd still expect it to center on the zenith?

### Actual Behaviour

* Stellarium centers on zenith, then screen goes black. Mouse moving screen brings back view.

* The script only centers on zenith when in azimuthal mode.

### Steps to reproduce

Just run the script?  I don't know if more is involved as it seems to do it every time. I thought it might have something to do with the landscape selected, but I tried both the zero landscape and Guereins. Same issue.

**Comment by gzotti** [comment]
For moving into the zenith via scripting, you must use a more complicated version with an "up vector" that tells you in which direction the upper border of the screen is. 
https://stellarium.org/doc/0.19/classStelMovementMgr.html#a8b563f2f225c8cbf139546b4aea4f825

Or just jump into this direction:
https://stellarium.org/doc/0.19/classStelMovementMgr.html#a8b563f2f225c8cbf139546b4aea4f825

**Comment by NotSoRandomOne** [comment]
So what would be a valid script to do so?  I tried core.moveToAltAzi(90, Math.Vec3d(0.,0., 1.), 1);, (with and without the 'Math', but ecmascript gives an error with the Vec3d, like it doesn't know anything about it.

**Comment by alex-w** [comment]
The script shoudn't be make a screen in garbage!

**Comment by NotSoRandomOne** [comment]
Alex,

If I understand the bug correctly, it means there is a very very very small chance when the user is navigating the screen via mouse in azimuth mode that they could somehow point straight up and have the screen turn to garbage because of the same calculations that are occurring in this circumstance. (Due to the nature of floating point math, the chance may be nonexistent for mouse navigation.) Maybe the easiest fix is to check for this condition (and probably the nadir as well), and add the up vector for those conditions inside Stellarium's core code.

Best wishes,
David

**Comment by alex-w** [comment]
I cannot reproduce "black screen" effect in version 0.19.1, so, this is regress and probably it's result of code refactoring :-/ Well, now I need to search a commit, who introduce this bad behaviour. :(

**Comment by NotSoRandomOne** [comment]
Good luck with it. Have a great day!

**Comment by gzotti** [comment]
Cannot reproduce on Win10 with V0.19.1. 
In Azimuthal mode, it works. 
In equatorial mode, call is ignored, though. 
Message in Logfile:

> StelMovementMgr: called moveToAltAzi, but not in AltAz mount frame. Ignoring.

I never see a black screen.

**Comment by NotSoRandomOne** [comment]
I'm running the current build, that's why Alex reproduced it and said it was introduced after 19.1 release.

**Comment by gzotti** [comment]
OK, I see it now. This is why we ask to specify such unimportant things like program version and operating system in the issue questionnaire.

**Comment by gzotti** [comment]
I added the Vec3d(x, y, z) type which was indeed missing to the scripting, so the StelMovementMgr.moveToAltAzi(Vec3d(x_aim, y_aim, z_aim), Vec3d(up_x, up_y, up_z)) can now be called. However, it seems even with the up vector specified, when reaching the zenith target something is breaking the up vector again. 

@NotSoRandomOne , the mouse/keyboard movement is restricted programmatically to never reach the true zenith, for these obvious reasons. And yes, there is code to produce a meaningful up vector. Just this gets apparently reset by some update.

**Comment by alex-w** [comment]
Georg, I don't understand this code:
```
// make up vector more stable:
StelMovementMgr::MountMode mountMode=mvmgr->getMountMode();
Vec3d aimUp;
if ( (mountMode==StelMovementMgr::MountAltAzimuthal) && (fabs(dAlt)> (0.9*M_PI/2.0)) )
	aimUp=Vec3d(-cos(dAzi), -sin(dAzi), 0.) * (dAlt>0. ? 1. : -1.);
else
	aimUp=Vec3d(0., 0., 1.);
```

Maybe just add special case for altitude 90 degrees to make up vector really stable (for example just set altitude 89.999999 degrees)?

**Comment by gzotti** [comment]
Sorry, but no. The "up vector" for OpenGL describes the direction towards the upper edge of the screen. When looking towards the horizon, (0/0/1) is the trivial solution. It is allowed to use a projected vector (one that is not parallel to the screen glass) as long as the direction forms an angle <90° with the view direction.  For almost all circumstances this works. Only when looking into zenith or nadir, this condition breaks. In these cases, we must form an "up" vector that is formed based on azimuth, with a possible sign change when viewing downward. I set a limit of 0.9*90°, it does not matter to change this to 0.99*90°, just "as we approach 90°".  We could also form this vector always parallel to the screen glass, always depending on azimuth&altitude, but it's not necessary. 

When used manually, 89.999° can hardly be discerned from 90°. But not using 90° causes bad skyboxes. Admittedly, there are probably some rare cases currently where scripting may lead to black zenith. I wanted to solve this months ago, but time is a problem.  The real problem is the StelMovementMgr class monster with all its hidden and interlinked updates here and there. This heap of patches needs a well-documented and better-structured rewrite which then should also include all other possible mount modes.

**Comment by axd1967** [comment]
IMHO this is not related to scripting.

tested in Stellarium 0.21.1-2039037 [master]:

1. select eq mode (ctrl-m)
2. select FOV 180 (ctl-alt-1)
2. look south (shft-s)
3. nudge south (arrow down) to 45-60 degrees above horizon
4. look to NCP (alt-shft-n)
image starts to nudge around screen center

workaround: nudge a little bit away from

**Comment by alex-w** [comment]
I catch Q_ASSERT(length>0.0) on the macOS after run the script from the report. O_o

**Comment by gzotti** [comment]
Yes there is some problem. Rarely triggered, though. Sorry, still no time before 0.21.3.
