### ISSUE TITLE
Possible bugs in LX200 protocol implementation

### ISSUE THREAD

**Issue by gzotti** [Stellarium/stellarium#818]
It seems there should be a few problems in the LX200 commands: 
* Degree sign should be '*' (according to protocol specs), not char(223) which gets truncated (compiler warning).
* There should be no spaces in the :Sd and :Sr commands

However, I cannot test this as I have no compatible instrument. I will push a tentative fix for the next beta, and we should ask users for response.

**Comment by alex-w** [comment]
Feedback: https://astronomy.ru/forum/index.php?topic=21983.msg4908237#msg4908237 

Not working the RA axis

**Comment by toweosp** [comment]
It seems to me that a bug has been introduced with this issue.

When I try to control my MEADE LX200GPS with Stellarium, I get the following error message

Connection::performWriting: writeNonblocking(5) returned 5; #:GD#
Connection::performReading: readNonblocking returned 10; +51ß14:14#
Lx200CommandGetDec::readAnswerFromBuffer: error: degree sign (*) expected

If #:GD# is sent directly to the telescope via the serial interface, it responds with 0xDF (DEC 223) for the degree sign, e.g.:

ASCII: +51ß14:20#
HEX: 0x2b 0x35 0x31 0xdf 0x31 0x34 0x3a 0x32 0x30 0x23

This also seems to be the expected behavior, see

https://www.skymtn.com/mapug-astronomy/ragreiner/LX200Commands.html
and
https://www.astro.louisville.edu/software/xmtel/archive/xmtel-indi-6.0/xmtel-6.0l/support/lx200/CommandSet.html

Therefore, from my point of view, the character DEC 223 / HEX 0xDF must be checked for, not '*'.

**Comment by gzotti** [comment]
@toweosp Whoa, finally somebody competent to test this with a real instrument, many thanks. 

That means the asterisk published everywhere in the protocol specs is really just a print replacement because they cannot print 0xDF themselves? I just wonder why this is the only character in the protocol that is invalid according to the compiler. Maybe we can change the data type to unsigned char to avoid compiler warnings.

**Comment by toweosp** [comment]
I also wonder why Meade removed the grammar info when they revised their website for the LX200 protocol (see archive on https://www.astro.louisville.edu/software/xmtel/archive/xmtel-indi-6.0/xmtel-6.0l/support/lx200/CommandSet.html#LX200CmdSetGrammar), since there is no information on this in the PDF that you can download from the Meade website today.

**Comment by gzotti** [comment]
This change also removed one of two spaces. @toweosp  Do you have insight whether these spaces are indeed correct, i.e. should I revert this as well?

**Comment by gzotti** [comment]
I re-open just to let @toweosp check this fix.

**Comment by gzotti** [comment]
@toweosp please can you compile and test this fix?

**Comment by toweosp** [comment]
@gzotti
Thank you for your fast correction! The control of the telescope - especially detection of the DEC position - is working now: 

Connection::performWriting: writeNonblocking(5) returned 5; #:GD#
Connection::performReading: readNonblocking returned 10; +29ß12:42#
Lx200CommandGetDec::readAnswerFromBuffer: Dec = +29:12:42

Regarding the `:Sr` command, I have observed the following with direct serial communication:

#:Sr23:00:00#
Returns: 1
#:Gr#
Returns: 23:00:00#

#:Sr 23:00:00#
Returns: 1
#:Gr#
Returns: 23:00:00#

#:Sr-----23:00:00#
Returns: 1
#:Gr#
Returns: 100:00:00#

#:Srasdfasf#	
Returns: 1
#:Gr#
Returns: 100:00:00#

#:Sr#	
Returns: 1
#:Gr#
Returns: 100:00:00#

I was not able to provoke the return value 0 (invalid).

I have not checked the :Sd command yet.

p.s.: By chance I had found this: 
https://bugs.launchpad.net/stellarium/+bug/1272960

**Comment by gzotti** [comment]
You mean these lower test were with some serial terminal (putty?), without Stellarium? Interesting. I'd just have needed an LX200. Thank you for sharing this protocol. It seems even bogus values do "something", successfully, and only not setting anything (electrical problem, or failure in reading back any value?) would return 0? Then we should also test for result 100, and do something with it. (Ignore&retry?)

It seems this documentation bug (* vs. °) on Meade's side has confused several people... If one space more or less is harmless, we shall keep one space. But please test whether anything is still broken. We should finally have a fix for this family.

**Comment by alex-w** [comment]
@toweosp any news?

**Comment by toweosp** [comment]
@alex-w @gzotti  As written in my last post the control of the telescope - especially detection of the DEC position - is working now. This was tested by controlling my telescope with stellarium in a "dry run" in my cellar doing a blind initial alignment of the telescope.

The additional checks regarding the `:Sr` command where done using a serial terminal program. I wasn't able to do more real life testing so far due to bad weather - this is a sure sign that everything is working now ;-)

**Comment by gzotti** [comment]
Thank you for testing these things. We hope this is finally done and circumstances documented now.

**Comment by giuse320** [comment]
'*'  = char ASCII 42

**Comment by gzotti** [comment]
@giuse320 what do you want to say with this comment?
