### ISSUE TITLE
Error downloading stars4: SSL handshake failed

### ISSUE THREAD

**Issue by Waldo79** [Stellarium/stellarium#868]
### Expected Behaviour
Download stars4 catalogue
### Actual Behaviour
Got the subject Error (verbatim), didn't download
### Steps to reproduce
repeated with same result
### System
* Stellarium version: <0.19.2>
* Operating system: <windows 7 Ultimate - all current updates>
* Graphics Card: <Nvidia), Model (GTX670), driver version 390.65>

### Logfile 
If possible, attach the logfile `log.txt` from your user data directory. Look into the Guide for its location.
[log.txt](https://github.com/Stellarium/stellarium/files/3907750/log.txt)

**Comment by alex-w** [comment]
Fixed in beta

**Comment by Waldo79** [comment]
Is there someway I can fix it without reinstalling the whole Stellarium package?
Maybe just swap the 0.19.2 stellarium.exe file for the beta file? - or some other file swap?
Thanks

**Comment by gzotti** [comment]
It is far easier to click on "uninstall" and "install" than to mess around with single files.

**Comment by Waldo79** [comment]
Not if you have to reconfigure everything – especially the satellite plug in.

**Comment by gzotti** [comment]
Just don't tick the box to delete your user data, don't write default config.ini. If unsure, back them up.

**Comment by Waldo79** [comment]
Yeah, but backing up then restoring is a lot more trouble than just replacing a file or 2.

…but thanks for the encouragement.

**Comment by gzotti** [comment]
You would have to download the beta package in any case, unpack it with some 3rd-party tool other than the installer, and then fiddle around. I don't see how this is easier than to avoid ticking "use default config.ini" and "delete user data" (or checkboxes similarly labeled) during installation of a beta installer.

**Comment by Waldo79** [comment]
Good point.

**Comment by MitchKob** [comment]
Hello, I am having a similar problem. I use Stellarium on my desktop running win10 with no issues, I installed it on my laptop today, and attempted to download the catalogs. Gave the following error Error downloading stars 4
Error creating SSL context ()

Here is the contents of the log file:

2019-12-08T19:01:44
Operating System: Windows 10 (10.0)
Compiled using MSVC++ 14.0 (Visual Studio 2015)
Qt runtime version: 5.9.8
Qt compilation version: 5.9.8
Addressing mode: 64-bit
Total physical memory: 16260 MB
Available physical memory: 12186 MB
Physical memory in use: 25%
Processor speed: 1992 MHz
Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Processor speed: 1992 MHz
Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Processor speed: 1992 MHz
Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Processor speed: 1992 MHz
Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Processor speed: 1992 MHz
Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Processor speed: 1992 MHz
Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Processor speed: 1992 MHz
Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Processor speed: 1992 MHz
Processor name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
C:\Program Files\Stellarium\stellarium.exe 
 -----------------------------------------------------
[ This is Stellarium 0.19.2 - https://stellarium.org/ ]
[ Copyright (C) 2000-2019 Fabien Chereau et al.       ]
 -----------------------------------------------------
Writing log file to: "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\log.txt"
File search paths:
  0 .  "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium"
  1 .  "."
Config file  "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\config.ini"  does not exist. Copying the default file.
Config file is:  "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\config.ini"
Default surface format:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Desired surface format:  QSurfaceFormat(version 2.1, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
StelGLWidget constructor
StelGraphicsScene constructor
initializeGL
OpenGL supported version:  "4.5.0 - Build 25.20.100.6577"
Current Format:  QSurfaceFormat(version 4.5, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 24, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
StelMainView::init
Detected: OpenGL "4.5"
Driver version string: "4.5.0 - Build 25.20.100.6577"
GL vendor is "Intel"
GL renderer is "Intel(R) UHD Graphics 620"
GL Shading Language version is "4.50 - Build 25.20.100.6577"
GLSL Version Number detected:  4.5
GLSL version is fine, we should not see a graphics problem.
Cache directory is:  "C:\\Users\\mskob\\AppData\\Local\\stellarium\\stellarium\\cache"
Sky language is  "en_US"
Planetary features language is  "en_US"
Application language is  "en_US"
Couldn't load translations for language  "en_US" in section "stellarium-scripts"
Empty translation file for language  "en_US" in section "stellarium-scripts"
Scripts language is  "en_US"
Loading Solar System data (1: planets and moons) ...
Loading from : "./data/ssystem_major.ini"
Loaded 82 Solar System bodies
Loading Solar System data (2: minor bodies)...
Loading from : "./data/ssystem_minor.ini"
Loaded 104 Solar System bodies
File ssystem_minor.ini is loaded successfully...
Loading nomenclature for Solar system bodies ...
Loaded 15578 / 15591 items of planetary surface nomenclature
WARNING - The next planets to assign nomenclature items is not found: "Dactyl, Puck, Ryugu"
Loading star data ...
"Loading .\\stars\\default\\stars_0_0v0_7.cat: 0_0v0_7; 4979"
"Loading .\\stars\\default\\stars_1_0v0_7.cat: 1_0v0_7; 21806"
"Loading .\\stars\\default\\stars_2_0v0_7.cat: 2_0v0_7; 150850"
"Loading .\\stars\\default\\stars_3_1v0_4.cat: 3_1v0_4; 425807"
Finished loading star catalogue data, max_geodesic_level:  3
Loading scientific star names from ".\\stars\\default\\name.fab"
Loaded 4507 / 4507 scientific star names
Loading variable stars from ".\\stars\\default\\gcvs_hip_part.dat"
Loaded 6916 / 6916 variable stars
Loading double stars from ".\\stars\\default\\wds_hip_part.dat"
Loaded 16412 / 16412 double stars
Loading cross-identification data from ".\\stars\\default\\cross-id.dat"
Loaded 108338 / 108338 cross-identification data records for stars
navigation/preset_sky_time is a double - treating as jday: "2451514.25001"
Loading DSO data ...
[...] "Stellarium DSO Catalog, version 3.7 (standard edition)"
Loaded 94393 DSO records
Loading DSO outline data ...
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
Loaded 63 DSO outline records successfully
Failure getting IP-based location: 
	 "Error creating SSL context ()"
LandscapeMgr: initialized Cache for 100 MB.
Loading star names from ".\\skycultures\\western\\star_names.fab"
Loaded 930 / 930 common star names
Loading DSO name data ...
Loaded 1084 / 1099 DSO name records successfully
WARNING - No position data for 15 objects: "NGC 7088, PGC 2906, PGC 2907, PGC 23521, PGC 28759, PGC 29167, PGC 34658, PGC 42102, PGC 54559, PGC 59117, PGC 73957, PGC 95597, PGC 100170, PGC 100170, PGC 119230"
Loaded 88 / 88 constellation records successfully for culture "western"
Loaded 85 / 85 constellation art records successfully for culture "western"
Loaded 88 / 88 constellation names
Loading constellation boundary data ... 
Loaded 782 constellation boundary segments
Error in Asterism  "TA6" : can't find star with coordinates 2.14697 / 8.55097
ERROR reading asterism lines record at line  88 for culture "western"
Loaded 81 / 82 asterism records successfully for culture "western"
WARNING - asterism abbreviation "TA6" not found when loading asterism names
Loaded 71 / 72 asterism names
stel.OpenGLArray: Disabling VAO usage because of Intel driver bugs
stel.OpenGLArray: Vertex Array Objects are not supported on your hardware (this is not an error)
Initializing basic GL shaders... 
Creating GUI ...
Loaded plugin "Exoplanets"
[Exoplanets] No Exoplanets section exists in main config file - creating with defaults
[Exoplanets] Version of the format of the catalog: 1
[Exoplanets] loading catalog file: "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\modules\\Exoplanets\\exoplanets.json"
Loaded plugin "MeteorShowers"
[MeteorShowersMgr] Loading catalog file: "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\modules\\MeteorShowers\\showers.json"
Loaded plugin "Novae"
[Novae] no Novae section exists in main config file - creating with defaults
[Novae] version of the catalog: 1
[Novae] loading catalog file: "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\modules\\Novae\\novae.json"
Loaded plugin "Oculars"
Ocular plugin - press Command-O to toggle eyepiece view mode. Press ALT-o for configuration.
Oculars::validateIniFile ocular.ini exists at:  "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\modules\\Oculars\\ocular.ini" . Checking version...
Oculars::validateIniFile found existing ini file version  3.1
Loaded plugin "Satellites"
[Satellites] loading catalog file: "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
Satellite has invalid orbit: "ALTAIR PATHFINDER" "42711"
Loaded plugin "SolarSystemEditor"
Trying to copy ssystem_minor.ini to "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\data\\ssystem_minor.ini"
  OpenType support missing for "Verdana", script 11
  OpenType support missing for "MS Shell Dlg 2", script 11
  OpenType support missing for "Arial", script 11
  OpenType support missing for "MS UI Gothic", script 11
  OpenType support missing for "SimSun", script 11
  OpenType support missing for "Verdana", script 12
  OpenType support missing for "MS Shell Dlg 2", script 12
  OpenType support missing for "Arial", script 12
  OpenType support missing for "MS UI Gothic", script 12
  OpenType support missing for "SimSun", script 12
  OpenType support missing for "Verdana", script 13
  OpenType support missing for "MS Shell Dlg 2", script 13
  OpenType support missing for "Arial", script 13
  OpenType support missing for "MS UI Gothic", script 13
  OpenType support missing for "SimSun", script 13
  OpenType support missing for "Verdana", script 14
  OpenType support missing for "MS Shell Dlg 2", script 14
  OpenType support missing for "Arial", script 14
  OpenType support missing for "MS UI Gothic", script 14
  OpenType support missing for "SimSun", script 14
  OpenType support missing for "Verdana", script 16
  OpenType support missing for "MS Shell Dlg 2", script 16
  OpenType support missing for "Arial", script 16
  OpenType support missing for "MS UI Gothic", script 16
  OpenType support missing for "SimSun", script 16
  OpenType support missing for "Verdana", script 17
  OpenType support missing for "MS Shell Dlg 2", script 17
  OpenType support missing for "Arial", script 17
  OpenType support missing for "MS UI Gothic", script 17
  OpenType support missing for "SimSun", script 17
  OpenType support missing for "Verdana", script 19
  OpenType support missing for "MS Shell Dlg 2", script 19
  OpenType support missing for "Arial", script 19
  OpenType support missing for "MS UI Gothic", script 19
  OpenType support missing for "SimSun", script 19
  OpenType support missing for "Verdana", script 20
  OpenType support missing for "MS Shell Dlg 2", script 20
  OpenType support missing for "Arial", script 20
  OpenType support missing for "MS UI Gothic", script 20
  OpenType support missing for "SimSun", script 20
Downloading file "https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat"
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
Error downloading file QUrl("https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat") :  "Error creating SSL context ()"
[Satellites] starting Internet update...
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
[Satellites] FAILED to download "https://www.prismnet.com/~mmccants/tles/classfd.zip" Error: "Error creating SSL context ()"
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
[Satellites] FAILED to download "https://www.amsat.org/amsat/ftp/keps/current/nasabare.txt" Error: "Error creating SSL context ()"
[Satellites] "42711" "ALTAIR PATHFINDER" has invalid orbit and will be removed.
[Satellites] purging objects that were not updated...
Satellite removed: "42711" "ALTAIR PATHFINDER"
[Satellites]  1 satellites proposed for removal,  1  removed,  1538  remain.
[Satellites] writing to: "C:\\Users\\mskob\\AppData\\Roaming\\Stellarium\\modules\\Satellites\\satellites.json"
[Satellites] update finished. 1 / 1539 updated, 0 added, 1 missing or removed. 1823 source entries parsed.
Downloading file "https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat"
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
Error downloading file QUrl("https://github.com/Stellarium/stellarium-data/releases/download/stars-2.0/stars_4_1v0_2.cat") :  "Error creating SSL context ()"

Thanks for the support.
