### ISSUE TITLE
Realistic moon phase

### ISSUE THREAD

**Issue by bystanderzzz** [Stellarium/stellarium#914]
A realistic moon phase show, as seen in the sky, is missing.
Now, the user can see the realistic lunar phase, only by zooming in, on the moon.

**Comment by gzotti** [comment]
What do you want? You can enlarge the moon artificially in the GUI. However, then it is not realistic any longer.

**Comment by bystanderzzz** [comment]
**Before focusing on the moon,** the software shows me some circle, as the moon.
That's not what I see in the real sky ...

**Comment by gzotti** [comment]
Would you care to spend a few minutes familiarizing yourself with the many options of the program?

**Comment by vvasuki** [comment]
I've used stellarium with delight a lot - but I too have the same problem and don't know a solution. (Want to see moon phase without having to zoom in.)

**Comment by gzotti** [comment]
It is not possible with current screen technology to show a realistic phase made from a Moon with 5 pixels diameter and the bright glare which the moon makes in wide-angle views. (Just try to make a photo with a wide-angle lens.) Therefore you have the option to enlarge the moon to show both, phase and glare effect.

**Comment by bystanderzzz** [comment]
Well, I can't shoot the sun, and I can't take a shot of Deneb (for example) either, but the software tries to show them in a realistic way.
Furthermore, if I select a location on one of Mars' moons, the software will show Mars in a realistic way.
The same goes for all other planets.
For some reason, on the Earth and on the Moon, the software doesn't work that way.
And finally:
There is no "not possible". There is "very difficult".
Anyway, nobody owes me anything.
Thank you

**Comment by gzotti** [comment]
If you select a location on one of Mars' moons, Mars takes up a considerable fraction of the sky. The same goes for all other planets. The other respective moons will likewise appear small/point-like when you don't zoom in.

Simply disabling the lunar "halo" so that the lunar sphere is rendered visible with 3-5px diameter looks likewise stupidly unrealistic, because the moon is then not prominent enough. 

If you want to concentrate on the Moon, zoom in. If you want to see the whole sky with a lunar phase visible, enlarge it. These are the options. Who can do it better is invited to send a pull request with really working code that looks fully convincing.

**Comment by 10110111** [comment]
I was going to create a new issue when I saw this one. This seems to be asking for the same thing I wanted to ask: an option to show the Moon as crescent when it looks so in the sky. Here's a photo I'd like to be able to reproduce (the sky part of it, of course; click to view in full size):

![IMG-20200225-WA0001](https://user-images.githubusercontent.com/6376882/75541080-54726500-5a2e-11ea-9acd-d3eea8cf334b.jpg)

This one was taken by a phone and sent to me via WhatsApp, so the resolution and compression artifacts are ugly, but I hope you get the point: even in this crappy-quality photo the Moon crescent can be seen as crescent, not as a blurry point.

> Simply disabling the lunar "halo" so that the lunar sphere is rendered visible with 3-5px diameter looks likewise stupidly unrealistic, because the moon is then not prominent enough.

I think this is simply because the Moon is rendered in the same non-realistic mode as when enlarged: too bright earthshine and very dull sunlit crescent (compared to real-life photos) — combined with lack of antialiasing. Not sure why I can't even force MSAA via the nvidia driver though, so can't easily check whether there'd be any useful effect.

**Comment by alex-w** [comment]
Other similar request: #861

**Comment by alex-w** [comment]
@bystanderzzz please check version 0.20.3-50e9bca0fd: https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot

**Comment by bystanderzzz** [comment]
Well, that's better. thank you.
